package llm

// ExpandedFallbackDatabase contains hundreds of brutal, wry insults organized by command type
// This database is used when LLM backends are unavailable to provide instant feedback
var ExpandedFallbackDatabase = map[string][]string{
	"git": {
		// Merge conflicts & branching disasters
		"Git good? More like git rekt!",
		"Did you forget to pull again? Classic amateur move.",
		"Another git genius strikes again!",
		"Your commits are as broken as your workflow.",
		"Merge conflict? That's just your code fighting back.",
		"Git rejected your code harder than everyone rejects you.",
		"Your branch management strategy: pure chaos.",
		"Even your commit messages know you're lying.",
		"Git history shows a clear pattern: failure.",
		"Your repository is a crime scene and you're the perpetrator.",
		"Merge conflicts: Because even git knows your code shouldn't mix.",
		"Failed to push? The remote is protecting itself.",
		"Your pull request would be rejected by a trash can.",
		"Git blame points directly at you. Shocking, I know.",
		"Rebase? You can't even base properly.",
		"Cherry-pick? You picked the wrong profession.",
		"Your stash is fuller than your understanding of git.",
		"Detached HEAD state? Matches your detached reality.",
		"Force push denied. Git has standards.",
		"Remote rejected your push. It has taste.",

		// Commit failures
		"Empty commit message? Empty head detected.",
		"Commit failed: Even git has quality standards.",
		"Your commits are war crimes against version control.",
		"Amend that commit? You need to amend your career choices.",
		"Git log is just a chronicle of your mistakes.",
		"Commit history: A tragedy in multiple acts.",
		"Your commit frequency suggests you don't test anything.",
		"Squash commits? Can't polish a disaster.",
		"Commit signature invalid. So is your logic.",
		"Pre-commit hook failed. Your code failed harder.",

		// Clone/fetch failures
		"Clone failed? The repo is running away from you.",
		"Fetch failed: The internet is protecting itself.",
		"Your clone attempt died of embarrassment.",
		"Permission denied: Even public repos don't want you.",
		"Clone timeout: The repo chose death over your attention.",
		"Shallow clone? Matches your shallow understanding.",
		"Submodule update failed. Dependency on competence not found.",
		"Remote not found? Neither is your skill.",
		"Failed to fetch: Server developed self-preservation instinct.",
		"Your clone is an insult to the original.",

		// More creative disasters
		"Git refuses to be an accomplice to your crimes.",
		"Your workflow is what nightmares are made of.",
		"Bisect can't find where you went wrong. Hint: The beginning.",
		"Your tags are as meaningless as your commits.",
		"Git hooks tried to save you. You ignored them.",
		"Remote tracking branches are tracking your failures.",
		"Your .gitignore can't ignore your incompetence.",
		"Clean working tree? Your code is anything but clean.",
		"Git init was your first mistake. Breathing was the second.",
		"Your fork is more broken than the original.",

		// Additional git disasters
		"Fast-forward merge impossible: You can't move forward.",
		"Three-way merge failed: All three ways lead to your failure.",
		"Octopus merge rejected: Even cephalopods won't merge with you.",
		"Git reflog shows a history of regret.",
		"HEAD is now at disaster commit.",
		"Untracked files: Tracking your mistakes is impossible.",
		"Modified files: Modifying bad into worse.",
		"Staged for failure: Every commit you stage.",
		"Working directory dirty: Like your code.",
		"Merge base not found: No common ground with competence.",
		"Divergent branches: Your career diverged from success.",
		"Upstream gone: Your upstream left you behind.",
		"No commits yet: No competent commits ever.",
		"Initial commit: Initial disaster.",
		"Update rejected: Updates can't fix fundamental",
		"Non-fast-forward: You move backwards only.",
		"Ref already exists: Reference to your failures exists.",
		"Invalid ref format: Your references are invalid.",
		"Garbage collection failed: Even gc won't clean you up.",
		"Repository corrupted: By your presence.",
	},

	"nodejs": {
		// npm/yarn disasters
		"NPM install failed? Shocking! Nobody saw that coming.",
		"Your package.json is crying. Fix it.",
		"Node modules: where dependencies go to die.",
		"Even npm doesn't want to deal with your code.",
		"Dependency hell is too good for you.",
		"NPM audit found 42,000 vulnerabilities. Most are you.",
		"Peer dependency conflict? Your whole existence is a conflict.",
		"Package not found: Much like your talent.",
		"Node modules folder: 3GB of your shame.",
		"NPM install failed faster than your career prospects.",
		"Your package-lock.json is an archaeological disaster.",
		"Semantic versioning can't capture your levels of broken.",
		"NPM scripts ran away in terror.",
		"Postinstall hook failed. Nothing wants to live in your project.",
		"Circular dependency detected: You depending on competence.",

		// Build & run failures
		"Node version mismatch: Wrong tool for the wrong developer.",
		"Your JavaScript is offensive to all programming languages.",
		"Runtime error: User error at runtime and designtime.",
		"Module not found? Neither is your ability to code.",
		"Syntax error: Your brain has syntax errors.",
		"TypeScript gave up trying to type your chaos.",
		"Webpack bundle failed: Can't bundle catastrophe.",
		"Babel couldn't transpile stupid.",
		"ESLint found infinity violations. It stopped counting.",
		"Your async/await shows you understand neither async nor await.",
		"Promise rejected: Much like your job applications.",
		"Callback hell? You built callback super-hell.",
		"Event loop blocked: By your incompetence.",
		"Memory leak detected: Your brain, leaking logic.",
		"Stack overflow: Your code, your career, everything.",

		// Package/framework specific
		"React component crashed harder than your hopes.",
		"Vue couldn't make your code reactive to logic.",
		"Angular error: No amount of dependency injection helps you.",
		"Express middleware intercepted your incompetence.",
		"Next.js couldn't render your disaster.",
		"Nest.js couldn't nest your chaos into order.",
		"Your Redux state is as confused as you are.",
		"Axios request failed: Even APIs reject you.",
		"Mongoose couldn't model your mistakes.",
		"Jest test failed: Your code is the joke.",
		"Mocha test suite: 0% passing, 100% crying.",
		"Cypress couldn't automate your unemployment.",
		"Prettier can't make your code pretty. Nothing can.",
		"Nodemon died watching your code changes.",
		"PM2 process crashed: It chose death over serving your code.",

		// Performance & deployment
		"Bundle size: 50MB. Competence: 0KB.",
		"Your code is slower than your career growth.",
		"Performance budget exceeded: By your incompetence budget.",
		"Lighthouse score: -42. Didn't know that was possible.",
		"Deploy failed: Production environment has standards.",
		"Your Docker container exited immediately. Smart container.",
		"Lambda function timeout: It chose timeout over your code.",
		"Serverless cold start: As cold as your prospects.",
		"CDN refused to distribute your disaster globally.",
		"NPX command failed: Even temporary execution is too much.",

		// Additional nodejs chaos
		"NVM can't manage your version of incompetence.",
		"N odejs? More like N o skillz.",
		"Event emitter emitting only errors.",
		"Buffer overflow: Of stupidity.",
		"Stream ended prematurely: Like your career.",
		"Readable stream unreadable: Like your code.",
		"Writable stream unworthyable.",
		"Duplex stream: Dual failure modes.",
		"Transform stream: Can't transform garbage.",
		"Process exited with code ENOCOMPETENCE.",
		"Uncaught exception: Your competence exception.",
		"Unhandled promise rejection: Life rejecting your promises.",
		"Graceful shutdown impossible: Nothing graceful about you.",
		"REPL can't evaluate you positively.",
		"Global scope polluted: By your existence.",
		"Module exports nothing valuable.",
		"Require failed: Required skill not found.",
		"Import error: Can't import success.",
		"Default export: Exporting failure by default.",
		"Named export: Named disaster.",
		"Namespace collision: You collide with competence.",
		"Tree shaking couldn't shake off your dead code.",
		"Code splitting: Your brain is code-split from logic.",
		"Lazy loading: You're lazy, code's not loading.",
		"Hot module replacement: Can't replace hot garbage.",
		"Service worker died: From serving your code.",
		"Web worker quit: Working for you was too much.",
		"Shared worker shared your failure.",
		"WASM couldn't assemble your logic.",
		"Source map leads to disaster.",
	},

	"docker": {
		"Docker container more like docker DISASTER!",
		"Even containers can't contain your incompetence.",
		"Your Dockerfile needs therapy.",
		"Container exit code: user error detected.",
		"Image build failed: Reality rejected your fantasy.",
		"Container crashed faster than your career.",
		"Docker daemon is judging you silently.",
		"Your layers have layers of failure.",
		"Multi-stage build, single-stage competence.",
		"FROM scratch? You are scratch.",
		"Port mapping failed: Nothing wants to connect to you.",
		"Volume mount error: Can't mount your chaos.",
		"Network creation failed: Isolation is impossible with you.",
		"Container orchestration? You can't orchestrate a lunch order.",
		"Docker compose? Your life needs decomposition.",
		"Health check failed: Your code has no vital signs.",
		"Container won't start: It developed survival instincts.",
		"Image pull failed: Registry is protecting itself.",
		"Build cache invalidated: By your existence.",
		"Your containers have more issues than Docker Hub.",
		"Entrypoint error: You entered the wrong profession.",
		"CMD failed: Every command you make fails.",
		"EXPOSE all ports? Can't expose enough to show your flaws.",
		"Environment variables undefined: Like your skills.",
		"Build context too large: Your mistakes are infinite.",
		"Layer caching failed: Can't cache catastrophe.",
		"Docker tag invalid: So is your code.",
		"Container memory limit exceeded: By your errors.",
		"Your Dockerfile is a recipe for disaster.",
		"Alpine image? Your problems are mountainous.",
		"Ubuntu base? You need a base understanding first.",
		"Container networking failed: Your logic has network issues too.",
		"Swarm mode rejected your service: Even orchestration has standards.",
		"Kubernetes refused to schedule you: Cluster has self-respect.",
		"Registry authentication failed: It recognized you.",
		"Image scan found critical vulnerabilities: You wrote them.",
		"Container logs: A horror story in real-time.",
		"OOMKilled: Out Of Memory. Out Of Skill.",
		"CrashLoopBackOff: Your career in container form.",
		"Init container failed: You failed before you started.",
		"Sidecar container abandoned ship.",
		"Your image has more bloat than functionality.",
		"Distroless image still contains your mistakes.",
		"Multi-arch build failed: Your code works on no architecture.",
		"Container registry full: Of your broken images.",
		"Docker socket permission denied: Even root doesn't trust you.",
		"Bridge network collapsed: Your logic is the bridge to nowhere.",
		"Your containers exit code 137: SIGKILL by embarrassment.",
		"Build arg undefined: Like your competence.",
		"Docker secrets exposed: Your lack of skill.",

		// More docker pain
		"Rootless mode: You have no roots in competence.",
		"Privileged container: Privilege to fail spectacularly.",
		"Capabilities dropped: All your capabilities.",
		"User namespace fail: No namespace for you.",
		"Cgroup limits exceeded: Limited by incompetence.",
		"Seccomp profile denied: Security from your code.",
		"AppArmor blocked: Armored against your logic.",
		"SELinux prevented: Linux securing against you.",
		"Runc failed: Run from your code.",
		"Containerd crashed: Couldn't contain your disaster.",
		"Buildkit error: Can't build kit from chaos.",
		"Build stage failed: All stages are failure stages.",
		"ARG expansion error: Can't argue with your failure.",
		"ENV variable chaos: Environment of incompetence.",
		"WORKDIR not found: Your work is never found.",
		"COPY failed: Can't copy competence that doesn't exist.",
		"ADD instruction disaster: Adding to the disaster.",
		"RUN command catastrophe: Running from reality.",
		"USER switch failed: Can't switch to competent.",
		"LABEL meaningless: Like your documentation.",
		"STOPSIGNAL ignored: Can't stop you from failing.",
		"SHELL exec failed: Shell-shocked by your code.",
		"ONBUILD triggered: Built-in failure trigger.",
		"HEALTHCHECK terminal: Terminally unhealthy code.",
		"Registry authentication failed: Authenticated incompetent.",
	},

	"http": {
		"404: Competence not found.",
		"Even the internet doesn't want to talk to you.",
		"Connection refused? So is your logic.",
		"HTTP status: 500 Internal User Error.",
		"403 Forbidden: You're forbidden from coding.",
		"401 Unauthorized: You're not authorized to be a developer.",
		"400 Bad Request: You are the bad request.",
		"408 Request Timeout: Like your patience for learning.",
		"429 Too Many Requests: Stop trying, seriously.",
		"502 Bad Gateway: Between your brain and keyboard.",
		"503 Service Unavailable: Your skills were never available.",
		"504 Gateway Timeout: Your logic timed out years ago.",
		"418 I'm a teapot: More functional than your code.",
		"451 Unavailable for Legal Reasons: Your code is a crime.",
		"301 Moved Permanently: To the unemployment line.",
		"302 Found: Your incompetence, everywhere.",
		"307 Temporary Redirect: To Stack Overflow, permanently.",
		"308 Permanent Redirect: Away from this career.",
		"410 Gone: Like your job prospects.",
		"411 Length Required: Your skill length is zero.",
		"413 Payload Too Large: Your ego, not your ability.",
		"414 URI Too Long: Your list of failures.",
		"415 Unsupported Media Type: Unsupported developer type.",
		"416 Range Not Satisfiable: Your competence range.",
		"417 Expectation Failed: Everyone's expectations of you.",
		"421 Misdirected Request: Your career is misdirected.",
		"422 Unprocessable Entity: You are unprocessable.",
		"423 Locked: Your brain, against knowledge.",
		"424 Failed Dependency: You are the failed dependency.",
		"425 Too Early: Too early to call you a developer.",
		"426 Upgrade Required: Your brain needs an upgrade.",
		"428 Precondition Required: Precondition: basic competence.",
		"431 Request Header Fields Too Large: Your mistakes are.",
		"444 Connection Closed: Reality disconnected from you.",
		"495 SSL Certificate Error: Your credentials are invalid.",
		"496 SSL Certificate Required: Certification of competence required.",
		"497 HTTP Request Sent to HTTPS Port: You to tech industry.",
		"499 Client Closed Request: Everyone closes requests to you.",
		"520 Web Server Unknown Error: You are the unknown error.",
		"521 Web Server Is Down: Your skill was never up.",
		"522 Connection Timed Out: Waiting for your competence.",
		"523 Origin Is Unreachable: Your potential is unreachable.",
		"524 Timeout Occurred: Your learning timeout is permanent.",
		"525 SSL Handshake Failed: Can't shake hands with failure.",
		"526 Invalid SSL Certificate: Your developer certificate is fake.",
		"CORS error: Cross-Origin Resource Stupidity.",
		"DNS resolution failed: Can't resolve your problems.",
		"TLS handshake failed: Secure connection to competence failed.",
		"Certificate expired: Your relevance expired.",
		"Redirect loop detected: Your logic is circular stupidity.",
		"Connection reset by peer: Peers reset away from you.",
	},

	"ssh": {
		"SSH connection failed: Server developed taste.",
		"Permission denied (publickey): Your credentials suck.",
		"Host key verification failed: Server doesn't trust you.",
		"Connection refused: Server is protecting itself.",
		"Timeout: Server chose silence over your presence.",
		"Port 22 closed: Against you specifically.",
		"Authentication failed: You couldn't authenticate as competent.",
		"Too many authentication failures: Story of your life.",
		"No route to host: No route to success for you.",
		"Network unreachable: Like your potential.",
		"Private key invalid: Your thinking is private and invalid.",
		"Known_hosts conflict: You're known for conflicts.",
		"SSH agent failed: Agents abandoned you.",
		"Tunnel creation failed: You dig holes, not tunnels.",
		"Port forwarding denied: Can't forward your career.",
		"Remote command failed: Local competence failed first.",
		"SCP transfer interrupted: By your incompetence.",
		"SFTP connection dropped: It dropped you like everyone else.",
		"ProxyJump failed: Can't jump over your problems.",
		"Multiplexing error: Can't multiplex stupid.",
		"Your SSH config is a disaster manifesto.",
		"Key exchange failed: Exchanged competence for confusion.",
		"Host key changed: Unlike your error patterns.",
		"Connection hijacked: By your incompetence.",
		"X11 forwarding disabled: Can't forward your mistakes visually.",
	},

	"python": {
		"IndentationError: Your code and career are misaligned.",
		"SyntaxError: Invalid syntax, invalid developer.",
		"NameError: 'competence' is not defined.",
		"TypeError: Can't convert stupid to smart.",
		"ValueError: Your value as a developer is an error.",
		"AttributeError: 'you' has no attribute 'skill'.",
		"KeyError: 'talent' not found in your dictionary.",
		"IndexError: You're out of bounds in every way.",
		"ImportError: Can't import competence from you.",
		"ModuleNotFoundError: Module 'brain' not found.",
		"RuntimeError: Your entire existence is a runtime error.",
		"RecursionError: Recursively making the same mistakes.",
		"MemoryError: Your brain ran out of memory for logic.",
		"OSError: Operating System for thinking not found.",
		"IOError: Input/Output error between brain and code.",
		"ZeroDivisionError: Dividing intelligence by your attempts.",
		"FloatingPointError: Your logic floats away from reality.",
		"OverflowError: Overflow of stupidity detected.",
		"AssertionError: Assert you can code. Failed.",
		"StopIteration: Stop iterating, you're done.",
		"GeneratorExit: Your code generation exited reality.",
		"KeyboardInterrupt: Keyboard trying to stop you.",
		"SystemExit: System wants to exit your presence.",
		"Pip install failed: Package manager managing disappointment.",
		"Virtualenv activation error: Can't isolate your chaos.",
		"Requirements.txt unmet: Requirement for skill unmet.",
		"Python version mismatch: Wrong version of developer.",
		"Deprecated syntax: Your skills are deprecated.",
		"Lambda function invalid: Even anonymous code judges you.",
		"List comprehension failed: You can't comprehend lists.",
		"Dictionary comprehension impossible: Can't comprehend anything.",
		"Your decorators are undecorative disasters.",
		"Context manager couldn't manage your context.",
		"Generator function generated only errors.",
		"Async function awaited competence forever.",
		"Type hints hint at your incompetence.",
		"Docstring empty: Like your understanding.",
		"F-string formatting failed: Can't format failure.",
		"PEP 8 violation count: Infinite.",
		"Pylint score: -1000. Impressive failure.",
		"MyPy found type errors in your brain.",
		"Black couldn't format your disaster.",
		"Pytest: 0 passed, infinity failed.",
		"Django migration failed: Can't migrate from stupid.",
		"Flask app crashed: Flask broke itself in protest.",
		"FastAPI not fast enough to escape your code.",
		"NumPy array dimensions: Dimensionally incompetent.",
		"Pandas DataFrame: Data of your failures framed.",
		"Matplotlib can't plot your disaster aesthetically.",
		"Scikit-learn couldn't learn from your mistakes.",
		"TensorFlow tensor flowed away from you.",
		"PyTorch caught fire: From your code.",
	},

	"rust": {
		"Borrow checker rejected you: Can't borrow competence.",
		"Lifetime error: Your career lifetime is expiring.",
		"Ownership rules violated: You own only failures.",
		"Cannot move out: Stuck in incompetence.",
		"Use of moved value: You moved past competence long ago.",
		"Mutable borrow in immutable context: Your mistakes are constant.",
		"Trait bound not satisfied: Trait 'Developer' not satisfied.",
		"Type mismatch: Expected competence, found chaos.",
		"Pattern match unreachable: Your success is unreachable.",
		"Cargo build failed: Can't cargo your incompetence.",
		"Rustc compilation error: Rust compiles. You don't.",
		"Unsafe block: Your entire code is unsafe.",
		"Panic in main thread: Your brain panicked first.",
		"Stack overflow: Not the website, your code.",
		"Heap allocation failed: Can't heap stupidity.",
		"Deadlock detected: Your logic is deadlocked.",
		"Race condition: Racing toward failure.",
		"Memory safety violated: By your unsafe existence.",
		"Zero-cost abstraction: Zero cost, zero value.",
		"Macro expansion failed: Can't expand your competence.",
		"Crate dependency hell: Your whole career is dependency hell.",
		"Clippy warnings: 99999. Clippy gave up counting.",
		"Rustfmt couldn't format your disaster.",
		"Cargo.toml invalid: Your developer manifest is invalid.",
		"Feature flag disabled: Feature 'competence' disabled.",
	},

	"navigation": {
		"cd: No such directory: Your career path.",
		"Permission denied: You lack permission to succeed.",
		"Not a directory: Not a developer either.",
		"Path not found: Your path to competence doesn't exist.",
		"Too many levels of symbolic links: Your logic is circular.",
		"Directory not empty: Of failures.",
		"pwd: You are lost in every sense.",
		"ls: Nothing worth listing here.",
		"Can't cd to parent: You have parental disappointment.",
		"Broken symbolic link: Link between brain and fingers broken.",
		"Path too long: Your list of mistakes is too long.",
		"Invalid argument: You are the invalid argument.",
		"Filename too long: Like your excuse list.",
		"Directory busy: Busy collecting your failures.",
		"Stale file handle: Your skills are stale.",
	},

	"build": {
		"Build failed: Builder has standards.",
		"Make error: Make better career choices.",
		"CMake can't make sense of you.",
		"Gradle build catastrophic: Can't gradle from chaos.",
		"Maven lifecycle interrupted: By your incompetence.",
		"Ninja build assassinated: By your code.",
		"Bazel couldn't build a case for your employment.",
		"Ant build collapsed: The colony rejected you.",
		"Compiler error: Can't compile stupid into smart.",
		"Linker error: Can't link your thoughts coherently.",
		"Assembler failed: Can't assemble competence.",
		"Preprocessor directives: Pre-disaster processing.",
		"Optimization level -O0: Your brain optimization.",
		"Debug symbols not found: Can't debug your existence.",
		"Build cache corrupted: By your presence.",
		"Incremental build failed: Can't incrementally improve nothing.",
		"Clean build required: Clean career slate required.",
		"Dependency resolution failed: You're the unresolvable dependency.",
		"Artifact generation failed: You generate only garbage.",
		"Target not found: Your target of competence doesn't exist.",
	},

	"permissions": {
		"Permission denied: You're denied permission to code.",
		"Access forbidden: Access to competence forbidden.",
		"Operation not permitted: Nothing should permit you to code.",
		"Insufficient privileges: Insufficient everything.",
		"Read-only filesystem: Your skills are read-only: nonexistent.",
		"Write protection: Protecting the world from your writes.",
		"Execute permission denied: Can't execute logic.",
		"Sudo required: Superuser competence required.",
		"Root access denied: Root cause is you.",
		"Group permission error: No group wants you.",
		"Owner mismatch: You don't own competence.",
		"Setuid failed: Can't set user to 'competent'.",
		"ACL violation: Against Creating Logic.",
		"Security context invalid: Your context is insecure.",
		"SELinux blocked you: For good reason.",
	},

	"database": {
		"Query syntax error: Your brain has syntax errors.",
		"Connection timeout: Database avoiding you.",
		"Deadlock detected: Your logic is deadlocked.",
		"Foreign key constraint violation: You violate all constraints.",
		"Unique constraint violation: Your failures aren't unique.",
		"NULL constraint violation: Your competence is NULL.",
		"Transaction rollback: Rolling back your career.",
		"Database locked: Against you specifically.",
		"Table doesn't exist: Table of your achievements doesn't exist.",
		"Column not found: Column of success missing.",
		"Index corruption: Your indexing of knowledge corrupted.",
		"Too many connections: Too many failed attempts.",
		"Connection refused: Database has standards.",
		"Authentication failed: Can't authenticate as competent.",
		"Replication lag: You lag behind everyone.",
		"Sharding failure: Can't shard your chaos.",
		"Migration failed: Can't migrate from incompetence.",
		"Backup corrupted: Can't backup your mistakes.",
		"Restore failed: Can't restore what never existed.",
		"ACID properties violated: Your logic is caustic.",
		"Isolation level insufficient: Can't isolate your problems.",
		"Join failed: Can't join you with success.",
		"Subquery disaster: Your sub-skills are a disaster.",
		"Stored procedure aborted: Stored your incompetence, aborted everything.",
		"Trigger failure: Triggered by your existence.",
	},

	"generic": {
		"Wow, you managed to break something simple. Impressive!",
		"Maybe try reading the manual... oh wait, who am I kidding?",
		"Error code says it all: user error!",
		"Have you tried turning your brain on and off again?",
		"This is why we can't have nice things.",
		"Congratulations! You found a new way to fail.",
		"Error between keyboard and chair detected.",
		"Your terminal is fine. You're the problem.",
		"Command failed successfully... at being terrible.",
		"Even Stack Overflow can't help you now.",
		"RTFM. Just kidding, you wouldn't understand it.",
		"Your command history is a horror anthology.",
		"This failure will go down in history. Your history.",
		"Achievement unlocked: Maximum incompetence!",
		"Error level: Catastrophic. User level: Subterranean.",
		"Your shell is crying. You should be too.",
		"Failure is an art form. You're Picasso.",
		"Command not found. Neither is your competence.",
		"Exit code 1: One out of one mistakes made.",
		"Your typo is the least of your problems.",
		"Autocorrect gave up on you.",
		"Tab completion is too good for you.",
		"Command line? More like command crime.",
		"Your bash history should be classified.",
		"This error message is too polite for you.",
		"Segmentation fault: Your brain segments are faulty.",
		"Core dumped: Your core competencies dumped.",
		"Aborted: Like your career prospects.",
		"Killed: Your code, your chances, your future.",
		"Illegal instruction: Everything you do is illegal.",
		"Bus error: Thrown under the bus of incompetence.",
		"Floating point exception: Your point floats far from reality.",
		"Trace/breakpoint trap: Trapped by your own incompetence.",
		"System call failed: System called, you failed.",
		"Broken pipe: Your logic pipeline is broken.",
		"I/O error: Input stupidity, Output disaster.",
		"Device not ready: Your brain device not ready.",
		"No space left: In the universe for your mistakes.",
		"Quota exceeded: Exceeded the failure quota.",
		"File exists: File of your failures exists.",
		"Too many open files: Your file of failures.",
		"Invalid argument: Every argument you make is invalid.",
		"Interrupted system call: Reality interrupts your delusion.",
		"Resource temporarily unavailable: Competence permanently unavailable.",
		"Operation would block: Your operation blocks progress.",
		"Cross-device link: Can't link your neurons across devices.",
		"Network is down: Your neural network is down.",
		"Protocol error: Protocol of logic not followed.",
		"Message too long: Your excuse list.",
		"Address already in use: Used by someone competent.",
		"Can't assign requested address: Can't assign you competence.",
		"Connection reset: Reset button needed for your brain.",
		"No buffer space: No buffer for your incompetence.",
		"Socket not connected: Your brain socket disconnected.",
		"Operation timed out: Waiting for your success timed out.",
		"Connection closed: Connection to reality closed.",
		"Host unreachable: Host of competence unreachable for you.",
		"Function not implemented: In your brain.",
		"System error: You are the system error.",
		"Unknown error: Unknown how you got this far.",
		"Critical error: Your existence in tech is critical.",
		"Fatal error: Fatal to project success.",
		"Warning became error: Your career warning signs became errors.",
		"Deprecated: Your skills were deprecated at birth.",
		"Not supported: You are not supported by this terminal.",
		"Incompatible: With competence.",
		"Corrupted: Your logic is corrupted.",
		"Failed to initialize: Your brain initialization failed.",
		"Allocation failed: Can't allocate success to you.",
		"Deallocation error: Deallocating your employment.",
		"Invalid state: Your mental state is invalid.",
		"Unexpected error: Everyone expected you to fail.",
		"Unhandled exception: You're the unhandled exception.",
		"Stack trace: Tracing your stack of failures.",
		"Assertion failed: Assert you can code. Negative.",
		"Precondition not met: Precondition of basic skill not met.",
		"Postcondition violated: Post-failure condition met.",
		"Invariant violated: Your invariant failure.",
		"Contract broken: Social contract to be competent broken.",
		"Specification mismatch: Specified as developer, actually disaster.",
		"Version conflict: Current version of you conflicts with success.",
		"Compatibility issue: Incompatible with the tech industry.",
		"Configuration error: Configured wrong from factory.",
		"Validation failed: Can't validate your existence here.",
		"Verification failed: Can't verify you're a real developer.",
		"Certification revoked: Certifiably incompetent.",
		"License expired: Your license to code expired.",
		"Signature invalid: Your signature move is failure.",
		"Checksum mismatch: Checked sum of skills: zero.",
		"Hash collision: Your failures collide with everyone's.",
		"Encryption failed: Can't encrypt your obvious incompetence.",
		"Decryption failed: Can't decrypt your thought process.",
		"Compression failed: Can't compress your infinite mistakes.",
		"Decompression failed: Decompressing your logic yields nothing.",
		"Parsing failed: Can't parse your nonsense.",
		"Serialization failed: Can't serialize your chaos.",
		"Deserialization failed: Can't deserialize your data or decisions.",
		"Encoding error: Error encoding your mistakes: too many.",
		"Decoding error: Can't decode your thought process.",
		"Format invalid: Your brain format is invalid.",
		"Schema violation: Violated the schema of competence.",
		"Mapping error: Can't map your errors, they're infinite.",
		"Binding failed: Can't bind competence to you.",
		"Resolution failed: Can't resolve your endless issues.",
		"Lookup failed: Looking up competence: not found.",
		"Search failed: Searching for your skills: 404.",
		"Match not found: Your abilities don't match requirements.",
		"Pattern invalid: Pattern of failure too consistent.",
		"Expression error: Your expression of code is an error.",
		"Evaluation failed: Evaluating your worth: negative.",
		"Calculation error: Calculating success probability: 0%.",
		"Computation failed: Computer can't compute your logic.",
		"Execution halted: Halting your code for humanity's sake.",
		"Process terminated: Your development process terminated.",
		"Thread killed: Your thread of logic killed by reality.",
		"Task cancelled: Your task of being a developer cancelled.",
		"Job aborted: Your job prospects aborted.",
		"Service stopped: Service of bad code stopped.",
		"Daemon died: Daemon of incompetence persists though.",
		"Worker failed: You're the failed worker.",
		"Queue overflow: Queue of your mistakes overflowed.",
		"Buffer overrun: Your errors overran the buffer.",
		"Underflow detected: Underflow of competence detected.",
		"Leak detected: Leaking stupidity everywhere.",
		"Corruption detected: Corrupted code, corrupted logic.",
		"Violation detected: Violating all programming principles.",
		"Breach detected: Breach of basic competence.",
		"Attack detected: Attacking code quality.",
		"Intrusion detected: Intruding on the developer community.",
		"Anomaly detected: You're the anomaly.",
		"Divergence detected: Diverging from sanity.",
		"Convergence failed: Can't converge on correct solution.",
		"Synchronization failed: Can't sync brain with reality.",
		"Coordination failed: Can't coordinate thoughts.",
		"Integration failed: Can't integrate into competence.",
		"Differentiation failed: Can't differentiate good from garbage.",
		"Optimization failed: Can't optimize stupidity.",
		"Minimization failed: Can't minimize your maximum errors.",
		"Maximization failed: Maximizing failure, succeeded.",

		// Even more generic brutality
		"Command execution failed: Like everything you execute.",
		"Parse error at life:1: Syntax error: You.",
		"Undefined behavior: Your entire existence.",
		"Implementation-defined disaster: You define disaster.",
		"Unspecified chaos: Can't specify your chaos level.",
		"Locale-specific failure: Fails in all locales.",
		"Platform-independent incompetence: You fail everywhere.",
		"Architecture-agnostic disaster: Disaster on all architectures.",
		"Endianness error: Big-endian or little-endian, you fail both.",
		"Alignment fault: You're misaligned with reality.",
		"Page fault: Every page of your code.",
		"TLB miss: Translation Look-aside to competence missed.",
		"Cache miss: Missed cache of good code.",
		"Pipeline stall: Your pipeline to success stalled.",
		"Branch prediction failed: Predicted you'd fail. Correct!",
		"Speculative execution disaster: Speculatively, you'll fail.",
		"Out-of-order execution: Your life is out of order.",
		"Instruction pipeline broken: Like your logic pipeline.",
		"Register spill: Spilling incompetence everywhere.",
		"Stack unwinding: Unwinding your disaster.",
		"Exception propagation: Propagating your existence.",
		"Signal handling failed: Can't handle your signals.",
		"Interrupt servicing: Interrupting to tell you: you suck.",
		"Context switch overhead: Switching from bad to worse.",
		"Privilege escalation denied: Can't escalate to competent.",
		"Ring transition failed: No ring wants you.",
		"Kernel panic: Kernel panicked seeing your code.",
		"Userspace violation: You violated userspace trust.",
		"System time desynchronized: Time given up on you.",
		"Clock skew detected: Your timing is always off.",
		"Epoch overflow: Overflowed the epoch of patience.",
		"Monotonic guarantee violated: Monotonically decreasing quality.",
		"Real-time constraint missed: Real-time showing real failure.",
		"Scheduling priority: Priority -infinity.",
		"Nice value: Nothing nice about you.",
		"Load average: Infinity. Competence average: Zero.",
		"CPU affinity: No CPU has affinity for your code.",
		"NUMA topology confused: By your existence.",
		"IPC mechanism failed: Inter-Process Catastrophe.",
		"Shared memory corrupted: Sharing your incompetence.",
		"Semaphore deadlock: Locked in incompetence.",
		"Mutex contention: Everyone contends with your code.",
		"Spinlock spinning: Spinning wheels of failure.",
		"Futex failure: Future of failure.",
		"RCU grace period: No grace for your code.",
		"Memory barrier breached: Barrier to competence too high.",
		"Atomic operation failed: Nothing atomic about your disaster.",
		"CAS failed: Compare-and-Swap with competent: failed.",
		"ABA problem: Already Bad, Always.",
		"Race condition: Racing toward failure.",
		"Data race: Racing to corrupt data.",
		"Livelock detected: Locked in perpetual failure.",
		"Priority inversion: Inverted: Low skill, high confidence.",
		"Convoy effect: Convoying incompetence.",
		"Thundering herd: Herd of your mistakes.",
	},

	"go": {
		"Go build failed: Should've Go-ne into another career.",
		"Gopher drowning in your code.",
		"Goroutine leaked: Like your competence.",
		"Channel deadlock: Channeling failure perfectly.",
		"Panic in goroutine: Your whole existence is panic.",
		"nil pointer dereference: Nil skill detected.",
		"Go mod tidy failed: Can't tidy your mess.",
		"Interface not implemented: Developer interface not implemented.",
		"Type assertion failed: Can't assert you're competent.",
		"Race detector found races: Racing toward unemployment.",
		"Context canceled: Cancel your coding privileges.",
		"Defer panic recover: Can't recover from you.",
		"WaitGroup deadlock: Waiting for competence: deadlock.",
		"Mutex locked: Locked in incompetence.",
		"Select statement blocked: Selected for failure.",
		"Go vet failed: Veterinarian can't fix this.",
		"Golint warnings: Infinite warnings for infinite mistakes.",
		"Import cycle detected: Cycle of incompetence.",
		"Package not found: Package of skills not found.",
		"go.mod broken: Modules of failure.",
		"Build tags invalid: Tagged as incompetent.",
		"Cross-compilation failed: Can't compile across to competence.",
		"CGo error: Can't Go to competence.",
		"Slice out of bounds: Your skills are out of bounds.",
		"Map concurrent write: Concurrently failing.",
		"Reflection failed: Reflects your incompetence.",
		"JSON marshal error: Can't marshal your chaos into order.",
		"HTTP server crashed: Server refused to serve you.",
		"SQL driver panic: Database driver drove away.",
	},

	"java": {
		"Java compilation failed: Needs more than coffee.",
		"NullPointerException: null competence detected.",
		"OutOfMemoryError: Out of skill memory.",
		"StackOverflowError: Your questions overflow Stack Overflow.",
		"ClassNotFoundException: Class of competence not found.",
		"NoClassDefFoundError: No definition of competence for you.",
		"IllegalArgumentException: You are the illegal argument.",
		"IllegalStateException: Your state is illegal.",
		"ConcurrentModificationException: Concurrently breaking everything.",
		"ArrayIndexOutOfBoundsException: Out of bounds of reason.",
		"UnsupportedOperationException: Operation 'competence' unsupported.",
		"NumberFormatException: Can't format your logic into numbers.",
		"IOException: Input/Output error: Input garbage, output disaster.",
		"FileNotFoundException: File 'competence.java' not found.",
		"SQLException: SQL query: 'SELECT skill FROM you' returned empty set.",
		"ClassCastException: Can't cast you to Developer.",
		"InstantiationException: Can't instantiate competence object.",
		"NoSuchMethodException: Method 'code()' not found in class You.",
		"SecurityException: Security from your code required.",
		"AssertionError: Assert you can code = false.",
		"Maven build failed: Mav-un successful.",
		"Gradle build failed: Grade: F. Build: Failed.",
		"Spring Boot crashed: Spring broke instead of booted.",
		"Hibernate exception: Hibernate from coding permanently.",
		"JVM crashed: Java Virtual Mistake.",
		"Garbage collection failed: Can't collect your garbage code.",
		"ThreadDeath: Thread died seeing your code.",
		"Eclipse won't start: Eclipsed by incompetence.",
		"IntelliJ IDEA: IDEA - Incompetence Detected Everywhere Automated.",
		"JAR file corrupted: Jarring incompetence.",
		"WAR deployment failed: WAR against competent code.",
		"Servlet exception: Servlets won't serve your code.",
		"JSP compilation error: Just Severely Poor code.",
		"EJB deployment failed: Enterprise Java Broken.",
		"JNDI lookup failed: Just No Development Intelligence.",
	},

	"cpp": {
		"Segmentation fault: Your brain segments are faulty.",
		"Memory leak detected: Leaking logic everywhere.",
		"Double free detected: Doubly incompetent.",
		"Use after free: Using brain after free-ing logic.",
		"Buffer overflow: Overflowing with stupidity.",
		"Stack smashing detected: Stack of skills smashed.",
		"Pure virtual function called: Pure virtual competence.",
		"Invalid pointer: Your logic pointer is invalid.",
		"Linker error: Can't link thoughts coherently.",
		"Undefined reference: Reference to competence undefined.",
		"Template instantiation failed: Can't template your chaos.",
		"STL iterator invalidated: Your thought iterator invalid.",
		"Exception not caught: Caught being incompetent though.",
		"std::bad_alloc: Bad allocation of brain cells.",
		"std::runtime_error: Runtime of your career is error.",
		"std::logic_error: Logic error in brain.cpp",
		"Compilation unit failed: Unit of competence failed.",
		"Preprocessor directive error: Pre-disaster processing.",
		"Multiple definition: Multiple definitions of failure.",
		"Header file not found: Header of logic not found.",
		"Circular dependency: Circular logic detected.",
		"Name mangling failed: Mangling code and career.",
		"vtable lookup failed: Virtual table of skills empty.",
		"RAII failed: Resource Acquisition Is Impossibility.",
		"Smart pointer isn't smart: Like you.",
		"Unique_ptr not unique: Uniquely bad though.",
		"Shared_ptr sharing failure: Sharing incompetence.",
		"Move semantics violated: Can't move from incompetence.",
		"Copy constructor called: Copying others' code detected.",
		"Destructor failed: Destroying your career successfully.",
		"CMake error: Can't make sense of you.",
		"Make failed: Make better choices.",
		"Clang compile error: Clang rejected your code audibly.",
		"GCC compilation failed: GCC = Generally Cannot Code.",
		"MSVC error: Microsoft Visual Cannot compile this.",
	},

	"ruby": {
		"Ruby failed: More like Rub-y wounds in everyone.",
		"Gem installation failed: Cubic zirconia skills.",
		"Bundler error: Bundle of incompetence.",
		"RubyGems broken: Gems are worthless like your code.",
		"Rails crashed: Off the rails of competence.",
		"Rake task failed: Rake up your mistakes.",
		"NoMethodError: Method 'code_well' undefined for You.",
		"NameError: Constant 'SKILL' not found.",
		"ArgumentError: Wrong number of brain cells.",
		"TypeError: Type 'Competent' expected, got 'Disaster'.",
		"LoadError: Can't load 'competence' gem.",
		"SyntaxError: Syntax error at life.rb:1",
		"RuntimeError: Your runtime is all errors.",
		"RegexpError: Can't match pattern 'success'.",
		"IOError: IO between brain and code broken.",
		"ThreadError: Thread of thought tangled.",
		"Gem::LoadError: Can't load skill gem.",
		"Bundler::GemNotFound: Gem 'competence' not found.",
		"ActiveRecord migration failed: Can't migrate from incompetence.",
		"ActionController crashed: No action, only inaction.",
		"ActiveJob failed: Job: Failed. Active: Inactive.",
		"ActionMailer error: Mailing your resignation.",
		"RSpec failed: 0 passing, infinity failing.",
		"Minitest disaster: Mini skill, maxi disaster.",
		"Cucumber scenario failed: Scenario: Your career. Status: Failed.",
		"Capybara timeout: Automated test timed out on your code.",
		"Puma server crashed: Puma'd by incompetence.",
		"Sidekiq job failed: Side hustle: Finding new career.",
		"Redis connection failed: Redis? More like Re-did wrong.",
	},

	"php": {
		"PHP error: Probably Horrible Programming.",
		"Fatal error: Fatal career error detected.",
		"Parse error: Can't parse your nonsense.",
		"Notice: Undefined variable 'skill'.",
		"Warning: Division by zero brain cells.",
		"Deprecated: Your skills deprecated at birth.",
		"Fatal error: Call to undefined function code().",
		"Class not found: Class of competence not found.",
		"Namespace error: No space for you in development.",
		"Trait failed: Trait 'Competent' not found.",
		"Interface error: Interface to reality broken.",
		"Composer failed: Can't compose competence.",
		"Autoloader failed: Can't auto-load skills you don't have.",
		"PSR violation: PHP Standards Regularly violated.",
		"Laravel crashed: Lara-fell into incompetence.",
		"Symfony error: Symphony of failure.",
		"CodeIgniter failed: Code ignited fires everywhere.",
		"WordPress crashed: Press away from your keyboard.",
		"Drupal disaster: Drooling over incompetence.",
		"Magento meltdown: Magento? More like Mage-can't-o.",
		"PDO exception: PDO said no.",
		"MySQL error: My SQL? Your hell.",
		"Session destroyed: Like your career.",
		"Header already sent: Heading to unemployment.",
		"Memory exhausted: Exhausted all skill reserves (never had any).",
		"Maximum execution time exceeded: Time exceeded waiting for competence.",
		"include failed: Can't include you in developers.",
		"require failed: Require competence: FAILED.",
		"Array to string conversion: Converting chaos to disaster.",
		"JSON decode error: Can't decode your thought process.",
	},

	"c": {
		"C compilation failed: C you failing.",
		"Segmentation fault core dumped: Core competence dumped.",
		"Bus error: Thrown under the bus of incompetence.",
		"Illegal instruction: Every line you write is illegal.",
		"Abort trap: Abort mission: Your career.",
		"Malloc failed: Can't malloc() skill.",
		"Free(): Invalid pointer: Your logic pointers are invalid.",
		"Printf() format error: Can't format your disaster.",
		"Scanf() failed: Can't scan any competence.",
		"Pointer arithmetic error: Can't add up to competence.",
		"Null pointer dereference: Dereferencing null brain.",
		"Stack overflow: Stack of errors overflowed.",
		"Heap corruption: Heap of mistakes corrupted.",
		"Undefined behavior: Your behavior is undefined chaos.",
		"Sequence point violation: Out of sequence with reality.",
		"Type mismatch: Type 'competent' not compatible with you.",
		"Incompatible pointer types: Incompatible with success.",
		"Integer overflow: Overflow of incompetence.",
		"Floating point exception: Logic floats into absurdity.",
		"Division by zero: Dividing success by your contribution.",
		"Header missing: Header.h for 'competence' missing.",
		"Linker error: Can't link stdlib and you.",
		"Makefile failed: Make better life choices.",
		"GCC error: GNU Can't Compile your chaos.",
		"Clang warnings: Clang loudly warned everyone.",
		"Valgrind found leaks: Leaking incompetence everywhere.",
		"GDB can't debug you: Debugger debugged out.",
		"Static analysis failed: Analysis shows: disaster.",
	},
}

// GetExpandedFallback returns a pseudo-random insult from the expanded database
func GetExpandedFallback(commandType string, command string) string {
	responses, exists := ExpandedFallbackDatabase[commandType]
	if !exists {
		responses = ExpandedFallbackDatabase["generic"]
	}

	// Improved pseudo-random selection using command text for variation
	hash := 0
	fullText := commandType + command
	for _, char := range fullText {
		hash = hash*31 + int(char)
	}
	if hash < 0 {
		hash = -hash
	}

	return responses[hash%len(responses)]
}
