package llm

// ULTIMATE ROAST DATABASE EXPANSION
// Adding 1,220 new insults across expanded and new categories

var InsultExpansion = map[string][]string{

	// ===================================================================
	// EXPANSION OF SMALL CATEGORIES (500 insults)
	// ===================================================================

	"rust_expanded": {
		// 50 new Rust-specific insults
		"Cargo build failed: Can't cargo your incompetence anywhere.",
		"Borrow checker error: Can't borrow competence you don't have.",
		"Lifetime error: Your career lifetime: Expired.",
		"Ownership violation: You don't own this skillset.",
		"Mutable reference error: Immutably incompetent.",
		"Use after free: Used freedom. Now free to leave.",
		"Dangling reference: Dangling from last thread of career.",
		"Move semantics failed: Move to new profession.",
		"Trait not implemented: Trait: Competence. Status: Not found.",
		"Type mismatch: Type: Developer. Actual: Disaster.",
		"Macro expansion failed: Macro disaster expansion successful.",
		"Pattern matching failed: Pattern: Failure. Match: Always.",
		"Unwrap on None: Unwrap your resignation letter.",
		"Expect failed: Expected competence. Got catastrophe.",
		"Result::Err: The only result you produce.",
		"Option::None: Your options: None.",
		"Panic at runtime: Panic at anytime.",
		"Stack overflow in Rust: Ironic and incompetent.",
		"Unsafe block: Your entire codebase is unsafe.",
		"Memory leak in Rust: Achievement unlocked: Impossible failure.",
		"Cargo.lock conflict: Locked in failure.",
		"Rust analyzer crashed: Analyzer quit analyzing you.",
		"Clippy warnings: 847 suggestions. #1: Quit.",
		"Rustfmt failed: Can't format incompetence.",
		"Cargo test failed: Zero tests passed. Zero surprise.",
		"Benchmark failed: Your only benchmark: Rock bottom.",
		"Feature flag error: Feature: Success. Flag: Disabled.",
		"Dependency resolution failed: Can't resolve incompetence.",
		"Circular dependency in Rust: Circular career path to nowhere.",
		"No main function: No main competence either.",
		"Rust edition error: Edition 2021. Your skills: Edition 1970.",
		"Async/await failed: Await unemployment.",
		"Future not ready: Your future: Never ready.",
		"Tokio runtime failed: Runtime disaster.",
		"Channel send failed: Can't send competence you lack.",
		"Mutex poisoned: Your career is the poison.",
		"Arc clone failed: Can't clone skill you don't have.",
		"RefCell borrow failed: Can't borrow cleverness.",
		"Weak upgrade failed: Can't upgrade from weak.",
		"Pin projection failed: Pinned to incompetence.",
		"Send/Sync not satisfied: Satisfaction: Never achieved.",
		"Const generic error: Constantly generic failure.",
		"Associated type mismatch: Associated with disasters.",
		"Coherence error: Coherence not found.",
		"Orphan rule violated: Orphaned from competence.",
		"Procedural macro failed: Procedure: Fail. Macro: Massive.",
		"Inline assembly error: Assembled disaster.",
		"Zero-cost abstraction: Your value: Zero cost, zero competence.",
		"RAII violation: Resource Acquisition Is Incompetence.",
		"Rust epidemic: You're patient zero of incompetence.",
	},

	"golang_expanded": {
		// 50 new Go-specific insults
		"go build failed: Go away.",
		"Go module error: Module of incompetence.",
		"Interface not satisfied: Interface: Competence. Satisfied: Never.",
		"Nil pointer dereference: Nil competence referenced.",
		"Goroutine leak: Leaking incompetence concurrently.",
		"Channel deadlock: Deadlocked in failure.",
		"Race condition detected: Racing to fail first.",
		"Select statement blocked: Blocked from success.",
		"Context canceled: Context: Your career. Canceled: Yes.",
		"Defer panic: Defer your resignation.",
		"Recover failed: Can't recover from this.",
		"Type assertion failed: Assert: You failed.",
		"Interface conversion failed: Can't convert to competent.",
		"Slice out of bounds: Bounds of decency exceeded.",
		"Map concurrent access: Concurrently catastrophic.",
		"Struct field not found: Field: Skill. Found: False.",
		"Method not found: Method: Success. Not found.",
		"Package import failed: Import failure expertise instead.",
		"Go fmt disagreement: Format: Wrong. Developer: Also wrong.",
		"Go vet issues: 400 problems found. #400: You.",
		"Go lint warnings: Lint says: Leave.",
		"Golangci-lint failed: Linting found incompetence.",
		"Go test panic: Test panicked. Tester should too.",
		"Benchmark allocation: Allocated: Failure. Deallocated: Hope.",
		"Coverage: 0%: Zero coverage. Zero competence.",
		"Go generate failed: Can't generate quality.",
		"CGo error: C Go away.",
		"Build tags wrong: Tagged for removal.",
		"Go mod tidy failed: Can't tidy this mess.",
		"Go mod vendor failed: Vendor says: No thanks.",
		"Go sum mismatch: Sum of mistakes: Infinite.",
		"Go work error: Work ethic: Also error.",
		"Embed directive failed: Embed yourself elsewhere.",
		"Generics constraint: Constraint: Competence. Failed.",
		"Type parameter error: Parameter: Skill. Type: Missing.",
		"Go routine panic: Routine panic is routine.",
		"WaitGroup misuse: Waiting for competence: Forever.",
		"Mutex not unlocked: Locked in incompetence.",
		"RWMutex deadlock: Read/Write failure.",
		"Once.Do failed: Once was too many.",
		"Atomic operation failed: Atomically incompetent.",
		"sync.Pool empty: Pool of talent: Empty.",
		"Context deadline exceeded: Deadline: Your career.",
		"HTTP handler panic: Handler panicked. Everyone panicked.",
		"JSON marshal failed: Can't marshal competence.",
		"JSON unmarshal failed: Can't unmarshal skill.",
		"SQL no rows: No rows of competence.",
		"Template execution failed: Template: Disaster.",
		"Reflection failed: Reflect on career choices.",
		"Unsafe pointer: Your entire approach is unsafe.",
		"Go: The language of concurrency. You: The epitome of incompetence.",
	},

	"ruby_expanded": {
		// 50 new Ruby-specific insults
		"Ruby syntax error: Syntax error in life choices.",
		"Gem not found: Gem of wisdom: Not in you.",
		"Bundle install failed: Bundle of incompetence installed.",
		"Bundler version conflict: Conflict with competence.",
		"LoadError: Can't load competence.",
		"NameError: Name: Developer. Error: Yes.",
		"NoMethodError: No method to your madness.",
		"ArgumentError: Your existence is an argument error.",
		"TypeError: Type: Competent. Actual: Catastrophe.",
		"RuntimeError: Runtime: All the time.",
		"ScriptError: Script of failures.",
		"StandardError: Standard for failure set.",
		"SyntaxError: Syntax wrong. Career wrong.",
		"LocalJumpError: Jump to conclusions, land in failure.",
		"RangeError: Range: Zero to zero.",
		"RegexpError: Regular expression: Irregular competence.",
		"ThreadError: Threading disasters.",
		"ZeroDivisionError: Division by zero competence.",
		"SystemStackError: Stack of mistakes exceeded.",
		"NotImplementedError: Competence not implemented.",
		"Gem dependency hell: You're the dependency everyone hates.",
		"Rails server crashed: Rails off the rails.",
		"ActiveRecord error: Active disaster record.",
		"Migration failed: Migrate to new career.",
		"Rake task failed: Rake in the failures.",
		"RSpec failed: Spec: Failure. Reality: Also failure.",
		"Minitest failed: Mini skill detected.",
		"Cucumber scenario failed: Scenario: You. Outcome: Failure.",
		"Capybara timeout: Timeout on competence.",
		"Puma worker killed: Worker killed. Career dying.",
		"Sidekiq job failed: Side job recommended: Not this.",
		"Redis connection failed: Can't connect to success.",
		"PostgreSQL error: Post-great skill. Pre-disaster.",
		"MySQL gone away: Like your competence.",
		"Mongoid error: Mongo mistake.",
		"HAML syntax error: HAML: How About Maybe Leave?",
		"ERB template error: Error Ready Brain: Not found.",
		"SASS compilation failed: Sassy but incompetent.",
		"Asset pipeline failed: Pipeline to unemployment.",
		"Sprockets error: Sprocket of failures.",
		"Webpacker failed: Pack it up. Pack it in.",
		"Yarn install failed: Yarn of excuses.",
		"Ruby version mismatch: Version: Incompetent. All versions.",
		"RVM error: Ruby Version Misery.",
		"rbenv failed: Ruby environment: Toxic.",
		"Bundler audit: 50 vulnerabilities. Biggest: You.",
		"Rubocop offenses: 800 offenses. Career offense: Worst.",
		"Reek detected: Code smell. Developer smell: Worse.",
		"Brakeman security issue: Security issue: Your code.",
		"Ruby: Optimized for happiness. You: Optimized for disasters.",
	},

	"php_expanded": {
		// 50 new PHP-specific insults
		"PHP Parse error: Parse error in brain.",
		"Fatal error: Fatally incompetent.",
		"Warning: Undefined variable: Warning: Undefined skill.",
		"Notice: Trying to get property: Notice: No properties.",
		"Deprecated: Your skills are deprecated.",
		"Call to undefined function: Function: Competence. Undefined.",
		"Class not found: Class: Developer. Not found.",
		"Trait conflict: Conflicting with competence.",
		"Namespace error: Namespaced into incompetence.",
		"Use statement failed: Used PHP. Abused logic.",
		"Composer install failed: Compose yourself. Then quit.",
		"Composer.lock conflict: Locked in PHP hell.",
		"PSR-4 autoload failed: Auto-loading disaster.",
		"Laravel artisan failed: Artisan of awful.",
		"Migration failed: Migrate away from PHP? Still incompetent.",
		"Eloquent error: Eloquent in failure.",
		"Blade template error: Blade cuts both ways. Both cut you.",
		"Route not found: Route to success: 404.",
		"Middleware error: Middle of disaster.",
		"Controller error: Control: Lost. Forever.",
		"Model error: Model of incompetence.",
		"View error: View: Bleak. Code: Also bleak.",
		"Validation failed: Failed to validate career choice.",
		"Session expired: Session: Your career. Expired: Yes.",
		"Cache miss: Missed cache. Missed mark.",
		"Queue worker died: Worker died. Career dying.",
		"PHPUnit failed: Unit: Failure. Test: Confirmed.",
		"Pest test failed: Pest: Your code.",
		"MySQL error: My SQL. Your QL: Questionably Lousy.",
		"PDO exception: PDO: PHP Disaster Object.",
		"WordPress plugin failed: Press Word. Depress team.",
		"WooCommerce error: Woo: None. Commerce: Failed.",
		"ACF error: Advanced Custom Failure.",
		"Symfony error: Symphony of disasters.",
		"Doctrine error: Doctrine: Fail often.",
		"Twig template error: Twig: Tiny branch. Your impact: Also tiny.",
		"Drupal error: Drupal: Drop all competence.",
		"Magento crashed: Magento: Mag-net-zero skill.",
		"PHP version error: Version 8.0. Competence: 0.0.",
		"PHP-FPM crashed: Fast Process Manager. Slow developer.",
		"Opcache error: Optimized cache. Un-optimized brain.",
		"Xdebug timeout: Debug: Infinite. Patience: Finite.",
		"Memory exhausted: 128M limit hit. Competence: 0K.",
		"Maximum execution time: Time exceeded. Competence: Never achieved.",
		"Headers already sent: Sent: Your code. Received: Rejection.",
		"Cannot modify header: Can't modify incompetence.",
		"Magic method failed: No magic can save you.",
		"Serialization failed: Can't serialize disaster.",
		"JSON encode error: Can't encode competence not found.",
		"PHP: Originally 'Personal Home Page'. Now: Permanent Horror Project.",
	},

	"c_expanded": {
		// 50 new C-specific insults
		"Segmentation fault (core dumped): Segmented from reality. Core: Dumped.",
		"Bus error: Error on the bus to employment.",
		"Stack smashing detected: Smashing career detected.",
		"Buffer overflow: Overflowing with incompetence.",
		"Null pointer dereference: Dereference your career.",
		"Memory leak detected: Leaking skill. None to leak.",
		"Double free detected: Free to fail twice.",
		"Use after free: Freedom wasted on you.",
		"Heap corruption: Corrupt coder.",
		"Invalid free: Invalid developer.",
		"Malloc failed: Can't allocate competence.",
		"Realloc failed: Can't reallocate brain cells.",
		"Calloc failed: Can't calloc skill.",
		"Free(): invalid pointer: Pointer: You. Invalid: Yes.",
		"Array index out of bounds: Bounds of decency exceeded.",
		"Undefined behavior: Behavior: Undefined. Competence: Also undefined.",
		"Integer overflow: Overflowing with mistakes.",
		"Integer underflow: Underflowing with competence.",
		"Division by zero: Divided by your zero skill.",
		"Floating point exception: Exception: Your code.",
		"Arithmetic exception: Arithmetic: Failed. Career: Failed.",
		"Signal 11 (SIGSEGV): Eleven reasons to quit.",
		"Signal 6 (SIGABRT): Abort mission. Abort career.",
		"Signal 4 (SIGILL): Illegal operation: Your code.",
		"Signal 8 (SIGFPE): Floating point: Your career trajectory.",
		"Signal 9 (SIGKILL): Killed. Career should be too.",
		"Compilation error: Compile regret.",
		"Linker error: Can't link success to you.",
		"Unresolved symbol: Symbol of failure: You.",
		"Multiple definition: Multiple definitions of disaster.",
		"Implicit declaration: Implicit incompetence declaration.",
		"Type mismatch: Type: Developer. Mismatch: Confirmed.",
		"Pointer arithmetic error: Arithmetic wrong. Pointer useless.",
		"Struct padding: Padded resume. Empty skills.",
		"Union access error: Union of failures.",
		"Enum overflow: Enumerated disasters exceeded.",
		"Macro expansion error: Macro disaster.",
		"Preprocessor error: Pre-process: Give up.",
		"#include error: Can't include competence.",
		"#define failed: Can't define success.",
		"Inline assembly error: Assembled catastrophe.",
		"Volatile qualifier ignored: Volatile: Your employment.",
		"Const violation: Constant: Your failure.",
		"Static lifetime: Static incompetence.",
		"Register allocation failed: Can't register competence.",
		"Stack frame: Frame job of career.",
		"Function prototype: Prototype of failure.",
		"Void return: Void of competence.",
		"Printf failed: Print resignation letter instead.",
		"C: Close to the metal. You: Close to terminated.",
	},

	"java_expanded": {
		// 50 new Java-specific insults
		"NullPointerException: Null competence exception.",
		"OutOfMemoryError: Out of memory. Out of talent.",
		"StackOverflowError: Stack Overflow: Your only resource.",
		"ClassNotFoundException: Class: Competence. Not found.",
		"NoClassDefFoundError: No class. No skill.",
		"ClassCastException: Can't cast incompetence to competence.",
		"IllegalArgumentException: Illegal argument: You becoming a developer.",
		"IllegalStateException: Illegal state: Employed as developer.",
		"UnsupportedOperationException: Operation: Success. Unsupported by you.",
		"IndexOutOfBoundsException: Bounds: Exceeded. Competence: Absent.",
		"ArrayIndexOutOfBoundsException: Array access: Wrong. Career: Also wrong.",
		"ConcurrentModificationException: Concurrent disasters.",
		"NoSuchElementException: Element: Skill. No such element.",
		"NoSuchMethodException: Method: Success. No such method.",
		"NumberFormatException: Number: Mistakes. Format: Infinite.",
		"ArithmeticException: Math failed. Developer failed.",
		"ClassCircularityError: Circular logic detected.",
		"ExceptionInInitializerError: Initialization: Failed from start.",
		"IncompatibleClassChangeError: Incompatible with competence.",
		"InstantiationException: Can't instantiate skill.",
		"InternalError: Internal: Broken. External: Also broken.",
		"LinkageError: Can't link to success.",
		"NoSuchFieldError: Field: Competence. No such field.",
		"OutOfMemoryError: PermGen: Permanent failure generator.",
		"StackOverflowError: Recursive incompetence.",
		"UnknownError: Unknown: Your skill level.",
		"UnsatisfiedLinkError: Unsatisfied: Everyone.",
		"VerifyError: Verification failed: You're incompetent.",
		"VirtualMachineError: Virtual competence: Machine said no.",
		"Garbage collection pause: Collecting your garbage: Takes ages.",
		"Memory leak: Leaking Java memory. Leaking competence.",
		"Thread deadlock: Deadlocked career.",
		"Race condition: Racing to fail.",
		"Maven build failed: Maven't got a clue.",
		"Gradle build failed: Grade: F. Building: Disasters.",
		"POM.xml error: Pom-pom of failure.",
		"Dependency conflict: Conflicting with competence.",
		"Spring boot failed: Spring forward to unemployment.",
		"Hibernate error: Hibernate your career.",
		"JPA mapping failed: Mapping failure to you.",
		"Servlet exception: Serve notice to quit.",
		"JSP compilation failed: Java Server Pages: Java Server Failures.",
		"WAR deployment failed: WAR: Won All Rounds of failure.",
		"JAR not found: JAR: Just Awful Really.",
		"Classpath error: Path: Lost. Class: Absent.",
		"JVM crash: Java Virtual Machine: Virtually useless for you.",
		"Serialization failed: Can't serialize incompetence.",
		"Deserialization failed: Can't deserialize success.",
		"Reflection failed: Reflect on leaving.",
		"Java: Write once, run anywhere. You: Write disaster, run nowhere.",
	},

	"python_expanded": {
		// 50 new Python-specific insults
		"IndentationError: Indentation wrong. Career alignment: Also wrong.",
		"TabError: Tab or spaces? Neither fixes incompetence.",
		"SyntaxError: Invalid syntax. Invalid developer.",
		"NameError: Name not defined. Competence not defined.",
		"TypeError: Type wrong. Developer type: Also wrong.",
		"ValueError: Value: Zero. Developer: Also zero.",
		"KeyError: Key to success: Missing.",
		"AttributeError: Attribute: Skill. Error: Not found.",
		"IndexError: List index out of range. Competence out of range.",
		"ZeroDivisionError: Divided by zero skill.",
		"ImportError: Can't import competence.",
		"ModuleNotFoundError: Module: Skill. Not found.",
		"FileNotFoundError: File: Competence. 404.",
		"PermissionError: Permission to code: Denied.",
		"IsADirectoryError: Is a disaster: True.",
		"NotImplementedError: Competence: Not implemented.",
		"RecursionError: Recursing through failures.",
		"MemoryError: Memory: Full of mistakes.",
		"OSError: OS: Fine. Developer: Error.",
		"RuntimeError: Running errors. Runtime: All time.",
		"SystemError: System: Works. User: Doesn't.",
		"UnicodeError: Can't encode competence in any format.",
		"StopIteration: Iteration stopped. Career should stop.",
		"GeneratorExit: Generator exited. You should exit.",
		"KeyboardInterrupt: Keyboard interrupted. Unplug it.",
		"SystemExit: System says exit. Listen to it.",
		"AssertionError: Assert False: Your competence.",
		"BufferError: Buffer overflow of mistakes.",
		"EOFError: End of file. End of career.",
		"FloatingPointError: Floating point. Sinking career.",
		"OverflowError: Overflow of incompetence.",
		"UnboundLocalError: Unbound by competence.",
		"BlockingIOError: Blocking progress.",
		"ChildProcessError: Child process knows more.",
		"ConnectionError: Can't connect to reality.",
		"BrokenPipeError: Pipe dream broken.",
		"TimeoutError: Timeout waiting for competence: Forever.",
		"Pip install failed: Pip: Package Installer of Problems.",
		"Requirements.txt conflict: Required: Skill. Have: None.",
		"Virtual environment corrupted: Virtual skill: Also corrupted.",
		"Conda environment failed: Conda: Can't do.",
		"Poetry lock failed: Poetry: Poor execution. Try Y.",
		"Django migration failed: Django: D is for Disaster.",
		"Flask server crashed: Flask: Fragile Like A Student's Knowledge.",
		"FastAPI slow: Fast API. Slow developer.",
		"Pytest failed: Tests failed. Tester failed.",
		"Unittest disaster: Unit: Failure. Test: Confirmed.",
		"Pylint score: -10/10: Negative talent.",
		"Black formatter fought back: Black formatter gave up.",
		"Python: Beautiful is better than ugly. Your code: Ugliest.",
	},

	"git_expanded": {
		// 50 new Git-specific insults
		"Git push rejected: Rejection: Universal.",
		"Non-fast-forward: Can't fast-forward past incompetence.",
		"Divergent branches: Divergent from competence.",
		"Updates were rejected: Update: Your resume.",
		"Failed to push refs: Failed to push competence.",
		"Everything up-to-date: Updated: Disaster log.",
		"No commits yet: No competence ever.",
		"Detached HEAD state: Detached from reality.",
		"Your branch is behind: Behind in everything.",
		"Your branch has diverged: Diverged from logic.",
		"Merge conflict in 47 files: Conflicting with excellence. Universally.",
		"Automatic merge failed: Auto-failure succeeded.",
		"Both modified: Both wrong.",
		"Both deleted: Both incompetent.",
		"Both added: Added disaster. Twice.",
		"Resolve conflicts: Can't resolve incompetence.",
		"Unmerged paths: Paths to disaster.",
		"No changes to commit: No changes to competence either.",
		"Nothing added to commit: Nothing added to skill set.",
		"Untracked files: Untracked competence: None.",
		"Modified files: Modified: Disaster level.",
		"Deleted files: Deleted: Hope.",
		"Renamed files: Renamed: Disaster v2.",
		"Git pull failed: Pull yourself together. Then quit.",
		"Git fetch failed: Can't fetch competence.",
		"Git clone failed: Can't clone success.",
		"Git checkout failed: Check out of tech.",
		"Git branch failed: Branch out. Way out.",
		"Git merge failed: Merge with unemployment.",
		"Git rebase failed: Rebase your life.",
		"Git cherry-pick failed: Cherry-pick new career.",
		"Git stash failed: Stash your IDE.",
		"Git reset failed: Can't reset incompetence.",
		"Git revert failed: Can't revert disaster.",
		"Git clean failed: Can't clean this mess.",
		"Git log empty: Log: Empty of achievements.",
		"Git blame shows: Blame: You. Always.",
		"Git bisect failed: Bisect career: All bad.",
		"Git tag failed: Tagged for removal.",
		"Git remote failed: Remote from success.",
		"Git config failed: Config: Wrong. Developer: Also wrong.",
		"Git submodule failed: Sub-par module. Sub-par coder.",
		"Git worktree failed: Work tree: Disaster forest.",
		"Git reflog disaster: Reflog: Catalog of catastrophes.",
		"Git gc failed: Garbage collection: You're the garbage.",
		"Git fsck errors: File system check: Developer broken.",
		"Git prune failed: Prune your ambitions.",
		"Git archive failed: Archive your career.",
		"Git bundle failed: Bundle yourself out.",
		"Git: Distributed version control. You: Distributed disaster.",
	},

	"docker_expanded": {
		// 50 new Docker-specific insults
		"Docker build failed: Build a new career instead.",
		"Docker run failed: Run from development.",
		"Docker pull failed: Pull yourself together. Then quit.",
		"Docker push failed: Push yourself out.",
		"Container exited (1): Exit code 1. Exit career.",
		"Container exited (137): Killed. Career should be too.",
		"Container exited (139): Segfault: Segmented from reality.",
		"Container exited (255): Maximum exit. Maximum failure.",
		"OCI runtime error: Open Container Incompetence.",
		"Image not found: Image: Success. Not found.",
		"No such container: No such competence.",
		"No such image: No such skill.",
		"Cannot connect to Docker daemon: Daemon detected incompetence.",
		"Permission denied: Docker denied. Reality denied.",
		"Port already allocated: Port: Occupied. Competence: Vacant.",
		"Network not found: Network: Down. Competence: Also down.",
		"Volume mount failed: Can't mount competence.",
		"Dockerfile syntax error: Syntax: Wrong. Developer: Wrong.",
		"COPY failed: Can't copy competence you lack.",
		"ADD instruction failed: Add: Disaster. Multiply: Disaster.",
		"RUN command failed: Run command. Command: Fail.",
		"CMD failed: Command: Fail. Career: Fail.",
		"ENTRYPOINT failed: Entry point: Exit door.",
		"WORKDIR not found: Work directory: Lost. Career: Also lost.",
		"ENV variable error: Environment: Toxic.",
		"EXPOSE failed: Exposed: Your incompetence.",
		"VOLUME failed: Volume: Loud failures.",
		"USER not found: User: Incompetent. Found: True.",
		"LABEL ignored: Labeled: Disaster.",
		"ARG undefined: Argument: Your existence. Invalid.",
		"FROM image failed: From bad to worse.",
		"Multi-stage build failed: Multi-stage failure.",
		"Build context too large: Context: Your mistakes. Size: Massive.",
		"No space left on device: Space: None. Competence: Also none.",
		"Docker-compose failed: Compose disasters.",
		"Service failed: Service to quit.",
		"Depends_on failed: Depends on competence: Failed.",
		"Healthcheck failed: Unhealthy code. Unhealthy coder.",
		"Container restart loop: Looping through failures.",
		"Docker swarm failed: Swarm of mistakes.",
		"Stack deploy failed: Stack of disasters deployed.",
		"Service scale failed: Can't scale incompetence.",
		"Secret creation failed: Secret: You're incompetent. Not secret.",
		"Config failed: Configuration: Disaster.",
		"Overlay network failed: Network overlay: Covering mistakes.",
		"Load balancer failed: Can't balance disasters.",
		"Container logs: 10GB of errors: Verbose in failure.",
		"Image size: 5GB: Bloated like your ego. Empty like your skill.",
		"Layer cache miss: Missed cache. Missed competence.",
		"Docker: Build, Ship, Run. You: Break, Sink, Done.",
	},

	// ===================================================================
	// NEW CATEGORIES (720 insults)
	// ===================================================================

	"kubernetes": {
		// 50 Kubernetes-specific insults
		"Pod CrashLoopBackOff: Looping through career disasters.",
		"ImagePullBackOff: Can't pull competence from any registry.",
		"ErrImagePull: Error: Developer. Image: Disaster.",
		"Invalid: Invalid developer detected.",
		"Pending: Pending termination.",
		"Failed: Failed. Obviously.",
		"Unknown: Unknown skill level. Known incompetence.",
		"Deployment failed: Deploy yourself elsewhere.",
		"ReplicaSet failed: Replicate: Failures.",
		"StatefulSet failed: Stateful: Disaster. Stateless: Competence.",
		"DaemonSet failed: Daemon of incompetence.",
		"Job failed: Job search recommended.",
		"CronJob failed: Cron: Every hour. Job: Every fail.",
		"Service unavailable: Service: You. Available: Never.",
		"Ingress failed: Ingress: Denied. Egress: Recommended.",
		"ConfigMap error: Map of mistakes.",
		"Secret decode failed: Secret: You're incompetent. Decoded.",
		"PersistentVolume failed: Persistently failing.",
		"PersistentVolumeClaim denied: Claim: Competence. Denied.",
		"StorageClass error: Class: Storage. Your class: Disaster.",
		"Namespace quota exceeded: Exceeded incompetence quota.",
		"ResourceQuota exceeded: Resource: Patience. Quota: Exceeded.",
		"LimitRange violated: Limits: Exceeded. Logic: Violated.",
		"HorizontalPodAutoscaler failed: Horizontal scaling. Vertical incompetence.",
		"VerticalPodAutoscaler failed: Can't auto-scale skill.",
		"Node not ready: Node: Not ready. Developer: Never ready.",
		"Node OutOfDisk: Out of disk. Out of ideas.",
		"Node MemoryPressure: Memory pressure. Career pressure: Crushing.",
		"Node DiskPressure: Disk pressure. Performance pressure: Failing.",
		"Node NetworkUnavailable: Network down. Competence: Also down.",
		"Taint toleration failed: Can't tolerate your code.",
		"Affinity rule violated: Affinity: Zero.",
		"Anti-affinity failed: Anti-everything competent.",
		"Selector mismatch: Select: None. Match: Nothing.",
		"Label query failed: Label: Disaster. Query: Why?",
		"Annotation error: Annotate: Mistakes.",
		"Finalizer stuck: Stuck in incompetence.",
		"Owner reference broken: Owner: Embarrassed.",
		"ControllerRevision failed: Revision: All bad.",
		"Helm install failed: At the helm of disaster.",
		"Helm upgrade failed: Upgrade: Impossible.",
		"Helm rollback failed: Can't rollback from this.",
		"Chart validation failed: Chart: Your career. Trend: Downward.",
		"Values.yaml error: Values: None.",
		"Istio mesh failed: Service mesh: Messy service.",
		"Envoy proxy failed: Proxy: Down. Career: Also down.",
		"CNI plugin failed: Container Network Incompetence.",
		"Kubelet failed: Kubelet: Cube of failure.",
		"Kube-proxy failed: Proxy to unemployment.",
		"Kubectl: Kube-control. You: Kube-can't.",
	},

	"mobile": {
		// 50 Mobile development insults
		"App crashed on launch: Launch career into unemployment.",
		"Memory warning: Low memory. Lower skill.",
		"App killed by system: System killed app. Should kill career.",
		"Segmentation fault on iOS: Segmented from Apple competence.",
		"ANR: Application Not Responding: Developer Not Competent.",
		"Out of memory: Android out of memory. Developer out of skill.",
		"Activity leaked: Activity: Leak. Competence: Also leak.",
		"Fragment transaction failed: Fragmented knowledge.",
		"UI not responsive: UI: Not responsive. Brain: Also unresponsive.",
		"Main thread blocked: Thread: Blocked. Career: Blocked.",
		"Network on main thread: Main thread: Blocked. Main skill: Missing.",
		"Strict mode violation: Violated: All best practices.",
		"Database locked: Locked: Database. Locked out: Success.",
		"SQLite error: SQL errors. Career errors.",
		"Core Data crash: Core: Corrupted. Data: Disaster.",
		"Realm migration failed: Migrate to new profession.",
		"JSON parsing failed: Can't parse success.",
		"Image loading failed: Image: Disaster. Loading: Your face.",
		"Glide failed: Glide away from development.",
		"Picasso crashed: Picasso: Artist. You: Artificial incompetence.",
		"Retrofit error: Retrofit your career.",
		"OkHttp failed: HTTP: Not OK. Developer: Not OK.",
		"RxJava error: Reactive X: Reactive disaster.",
		"Kotlin coroutine failed: Co-routine: Co-disaster.",
		"Swift compile error: Swift to fail.",
		"SwiftUI preview failed: Preview: Disaster. Review: Worse.",
		"Combine publisher failed: Combine: Disasters.",
		"UIKit constraint conflict: Constraint: Competence. Conflict: Total.",
		"Auto Layout failed: Layout: Auto-disaster.",
		"Storyboard merge conflict: Story: Disaster. Board: Quit.",
		"XIB loading failed: XIB: Exit career.",
		"CocoaPods install failed: Cocoa pods: Bitter. Career: Also bitter.",
		"Carthage build failed: Cart before horse. Disaster before success.",
		"SPM resolution failed: Swift Package Manager: Swiftly package yourself out.",
		"Gradle sync failed: Sync: Failed. Career: Sync to unemployment.",
		"ProGuard error: Guard: Your code. Pro: Not you.",
		"R8 shrinking failed: Shrink: Your code. Also: Your prospects.",
		"Build variant failed: Variant: All failed.",
		"Flavor dimension error: Flavor: Sour. Dimension: Disaster.",
		"AndroidManifest error: Manifest: Disaster.",
		"Info.plist error: Info: You failed.",
		"Provisioning profile failed: Profile: Disaster developer.",
		"Code signing failed: Signed: Your termination letter.",
		"TestFlight build failed: Flight: Grounded. Career: Crashed.",
		"App Store rejection: Rejected: By Apple. By everyone.",
		"Play Store suspended: Suspended: App. Suspended: Disbelief at incompetence.",
		"React Native bridge crashed: Bridge: Burned. Career: Also burned.",
		"Flutter hot reload failed: Hot: Your seat. Reload: Your resume.",
		"Expo build failed: Expo: Exit. Position: Obsolete.",
		"Mobile: Developing for billions. You: Disappointing billions.",
	},

	"web": {
		// 50 Web development insults
		"HTML validation failed: Hyper Text Markup Lunacy.",
		"CSS not loading: Cascading Style Sheets: Cascading career sheets.",
		"JavaScript error: Just Awful: Very Awful Scripts Completely Ridiculous Incompetence Providing Trauma.",
		"DOM manipulation failed: Document Object Misery.",
		"Event listener failed: Listen: Nobody wants your code.",
		"AJAX failed: Asynchronous JavaScript And Junk.",
		"Fetch API failed: Fetch unemployment papers.",
		"Promise rejected: Promise: Broken. Like your code.",
		"Async/await disaster: Await career termination.",
		"Callback hell: Hell is other people's callbacks. And yours.",
		"CORS error: Cross-Origin Resource Stupidity.",
		"Same-origin policy violated: Policy: Don't hire you.",
		"Local storage full: Full of mistakes.",
		"Session storage corrupted: Session: Disaster. Storage: Failures.",
		"Cookie blocked: Cookie crumbled. Career crumbling.",
		"IndexedDB failed: Indexed: Disasters.",
		"Service Worker failed: Worker: Failing. Service: Disservice.",
		"Web Worker crashed: Worker quit. You should too.",
		"WebSocket closed: Socket: Closed. Career: Also closing.",
		"SSE connection lost: Server-Sent Events: Event horizon of incompetence.",
		"WebRTC failed: Real-Time Catastrophe.",
		"Canvas rendering failed: Can't render competence.",
		"SVG parse error: Scalable Vector Graphics: Scalable vector of failure.",
		"WebGL crashed: Graphics: Failed. Logic: Also failed.",
		"Geolocation denied: Location: Lost. Competence: Never found.",
		"Notification permission denied: Notify: You're incompetent.",
		"Clipboard access denied: Can't copy-paste competence.",
		"Fullscreen failed: Full screen of failure.",
		"Pointer Lock failed: Locked: Out of success.",
		"Screen Capture failed: Capture this: You failed.",
		"Web Audio failed: Audio: Deafening silence of competence.",
		"Media Stream failed: Stream: Of tears from teammates.",
		"Speech Recognition failed: Can't recognize competence.",
		"Speech Synthesis failed: Synthesize career change.",
		"Battery API: Battery low. Morale: Also low.",
		"Network Information: Network: Slow. You: Slower.",
		"Vibration API failed: Vibrating with incompetence.",
		"Ambient Light: Light reveals disasters.",
		"Device Orientation: Oriented: Wrong direction.",
		"Proximity sensor: Too close to incompetence.",
		"Responsive design failed: Responsive: Not you.",
		"Media query failed: Query: Why are you coding?",
		"Flexbox failed: Flex: Zero. Box: Your career.",
		"Grid layout failed: Grid: Locked in failure.",
		"Bootstrap broken: Boot: Strap on new career.",
		"Tailwind blown away: Tailwind: Blown. Career: Also blown.",
		"Webpack bundled chaos: Packed: Disasters.",
		"Vite build failed: Vite: Fast build. You: Fast failure.",
		"Parcel bundler failed: Parcel: Return to sender.",
		"Web: World Wide Web. You: World Wide Waste.",
	},

	"shell_scripting": {
		// 50 Shell scripting insults
		"Bash syntax error: Bash: Bourne Again Shell. You: Born to fail again.",
		"Command not found: Command: Lost. Competence: Also lost.",
		"Permission denied: Permission to code: Permanently denied.",
		"No such file: File: Missing. Skill: Also missing.",
		"Is a directory: Directory of disasters.",
		"Not a directory: Not a developer either.",
		"Argument list too long: Arguments against you: Infinite.",
		"Broken pipe: Pipe dream broken.",
		"Illegal option: Illegal to code this badly.",
		"Too many arguments: Too many mistakes.",
		"Invalid argument: You're invalid.",
		"Variable not set: Variable: Competence. Set: Never.",
		"Unbound variable: Unbound from reality.",
		"Bad substitution: Substitute yourself out.",
		"Syntax error near: Near: Your code. Error: Everywhere.",
		"Unexpected token: Unexpected: Your employment.",
		"Unexpected EOF: End of file. End of career.",
		"Conditional expression error: Condition: If competent. Result: False.",
		"Arithmetic error: Can't count your mistakes. Too many.",
		"Division by zero: Divided by zero competence.",
		"Invalid array subscript: Array access: Wrong. Career: Also wrong.",
		"Command substitution failed: Substitute: Yourself.",
		"Process substitution failed: Process: Disaster.",
		"Here document error: Here: Disaster. There: Also disaster.",
		"Here string error: String: Of failures.",
		"Redirection error: Redirect: To unemployment.",
		"Pipe error: Piping disasters.",
		"Background job failed: Background: Your career.",
		"Job control error: Job: Out of control.",
		"Suspended job: Suspended: Your employment.",
		"Killed by signal: Signal: Your incompetence.",
		"Terminated: Terminated. Finally.",
		"Segmentation fault: Segment: Your career. Fault: Yours.",
		"Bus error: Bus to unemployment departing.",
		"Function not defined: Function: Brain. Defined: False.",
		"Recursive function error: Recursive: Disasters.",
		"Loop never ends: Like your failures.",
		"Infinite loop detected: Looping through incompetence.",
		"Break outside loop: Break: Your spirit. Loop: Your failures.",
		"Continue outside loop: Continue: To fail.",
		"Return outside function: Return: Your badge.",
		"Exit status: Non-zero: Like your competence.",
		"Glob pattern failed: Global pattern: Disaster.",
		"Brace expansion failed: Brace: For impact of incompetence.",
		"Tilde expansion failed: Tilde next career.",
		"Parameter expansion failed: Expand: Disasters.",
		"ShellCheck warnings: 500 issues found. #1: You.",
		"Shebang invalid: Shebang: She's banging her head at your code.",
		"Source failed: Source of problems: You.",
		"Shell: Command interpreter. You: Command misinterpreter.",
	},

	"algorithms": {
		// 50 Algorithm and data structure insults
		"O(n!) complexity: Factorial incompetence.",
		"O(2^n) runtime: Exponential disaster.",
		"O(n^3) detected: Cubic catastrophe.",
		"Infinite loop detected: Looping through life: No exit.",
		"Stack overflow: Stack of mistakes overflowed.",
		"Queue overflow: Queue of failures: Infinite.",
		"Heap corruption: Heap: Corrupted. Brain: Also corrupted.",
		"Binary tree unbalanced: Like your work-life balance: Disaster.",
		"AVL tree rotation failed: Rotate: To new career.",
		"Red-black tree violation: Red: Your face. Black: Your future.",
		"B-tree split failed: Split: Decision making. Failed: Always.",
		"Hash collision: Collision with competence.",
		"Hash table full: Full of incompetence.",
		"Load factor exceeded: Factor: Patience. Exceeded: Yes.",
		"Linked list cycle: Cycling through failures.",
		"Double-linked disaster: Linked: To failure. Doubly so.",
		"Array out of bounds: Bounds: Exceeded. Competence: Never reached.",
		"Dynamic array resize: Resize: Expectations downward.",
		"Circular buffer overflow: Circular: Your logic. Buffer: Your mistakes.",
		"Priority queue mispriority: Priority: Quitting. Queue: Long.",
		"Deque disaster: Double-ended queue. Double-ended failure.",
		"Graph not acyclic: Cyclic: Your failures.",
		"Directed graph misdirected: Directed: To unemployment.",
		"Weighted graph: Weight: Of your incompetence.",
		"Graph traversal failed: Traversed: Path to disaster.",
		"DFS too deep: Depth-First Search: Depth of incompetence.",
		"BFS too broad: Breadth-First Search: Broad incompetence.",
		"Dijkstra failed: Shortest path: Not found. To competence: Impossible.",
		"A* pathfinding failed: A-star: A-failure.",
		"Bellman-Ford negative cycle: Negative: Everything about you.",
		"Floyd-Warshall timeout: All pairs shortest paths: All lead to failure.",
		"Prim's algorithm failed: Minimum spanning tree: Maximum incompetence.",
		"Kruskal's algorithm failed: Kruskal: Crush career. All.",
		"Topological sort failed: Topology: Disaster. Sort: Can't sort this mess.",
		"Trie insertion failed: Trie: Failed. Career: Also tried and failed.",
		"Suffix tree construction: Suffix: -ed career.",
		"Segment tree failed: Segment: Your career. Tree: Fallen.",
		"Fenwick tree error: Binary Indexed Tree: Index of incompetence.",
		"Union-Find disjoint: Disjoint: From competence.",
		"Quick sort worst case: Worst case: You coding anything.",
		"Merge sort disaster: Merge: Conflicts. Sort: Can't sort your life.",
		"Heap sort failed: Heap of failures sorted.",
		"Radix sort overflow: Radix: Radical incompetence.",
		"Bucket sort: Bucket: Full of mistakes.",
		"Counting sort: Counting: Your failures. Count: Infinity.",
		"Binary search failed: Binary: 0 or 1. You: Solid 0.",
		"Interpolation search: Interpolate: Between bad and worse.",
		"Exponential search: Exponentially terrible.",
		"Dynamic programming: Dynamic: Disasters. Programming: Pain.",
		"Algorithms: Elegant solutions. Your code: Elephant in room.",
	},

	"architecture": {
		// 50 Architecture and design pattern insults
		"Monolith detected: Monolithic failure.",
		"Microservices chaos: Micro: Services. Macro: Disasters.",
		"Service mesh tangled: Mesh: Mess. Service: Disservice.",
		"Spaghetti code: Spaghetti: Edible. Your code: Inedible.",
		"Lasagna architecture: Layers of disaster.",
		"Ravioli architecture: Pockets of incompetence.",
		"Big ball of mud: Accurate description.",
		"God object detected: God: Help us.",
		"Anemic domain model: Anemic: Code. Also: Effort.",
		"Fat controller: Controller: Fat. Logic: Absent.",
		"Singleton abuse: Single: Point of failure. You.",
		"Factory pattern failed: Factory: Producing disasters.",
		"Abstract factory abstract: Abstraction: Your competence.",
		"Builder pattern unbuildable: Build: Nothing of value.",
		"Prototype pattern failed: Prototype: Disaster template.",
		"Adapter pattern mismatch: Adapt: To new career.",
		"Bridge pattern collapsed: Bridge: To success. Collapsed.",
		"Composite pattern decomposed: Composed: Disasters.",
		"Decorator pattern undecorated: Decorated: With failure.",
		"Facade pattern: Facade: Your competence. Reality: None.",
		"Flyweight pattern heavy: Heavyweight incompetence.",
		"Proxy pattern: Proxy: For disaster.",
		"Chain of responsibility: Chain: Of failures.",
		"Command pattern failed: Command: Disaster. Execute: Failure.",
		"Interpreter pattern: Interpret: You're incompetent.",
		"Iterator pattern exhausted: Iterated: Through disasters.",
		"Mediator pattern: Mediating: Disasters.",
		"Memento pattern: Memento: Of failures.",
		"Observer pattern blind: Observers: Horrified.",
		"State pattern stateless: State: Chaos. Always.",
		"Strategy pattern strategic: Strategically failing.",
		"Template method disaster: Template: For disaster.",
		"Visitor pattern uninvited: Visitor: Your code. Invited: Never.",
		"MVC violated: Model: Broken. View: Bleak. Controller: Out of control.",
		"MVP failed: Most Valuable: Problem. You.",
		"MVVM disaster: Model-View-ViewModel: Model-Void-Void-Mistake.",
		"Hexagonal architecture: Six sides of disaster.",
		"Onion architecture: Layers of tears.",
		"Clean architecture dirty: Clean: Code. Dirty: Yours.",
		"Domain-driven design: Domain: Disaster. Driven: To quit.",
		"Event sourcing: Sourcing: Events of failure.",
		"CQRS failed: Command Query Responsibility Segregation: Can't Query: Reasons to hire you.",
		"Event-driven chaos: Events: Cascading failures.",
		"Message queue: Queue: Of people quitting.",
		"Pub/Sub disaster: Published: Failures. Subscribed: No one.",
		"Saga pattern failed: Saga: Of incompetence.",
		"Circuit breaker open: Circuit: Broken. Career: Also broken.",
		"Bulkhead pattern flooded: Bulkheads: Breached. Ship: Sinking.",
		"Retry pattern: Retrying: Life. Succeeding: Never.",
		"Architecture: Structure for success. Yours: Structure for disaster.",
	},


	// ===================================================================
	// MEDIUM NEW CATEGORIES (420 insults - 30 each)
	// ===================================================================

	"refactoring": {
		// 30 Refactoring insults
		"Refactor failed: Factor: Zero improvement.",
		"Code smell detected: Smell: Your code. Stench: Career.",
		"Extract method failed: Can't extract competence.",
		"Inline variable disaster: Inline incompetence.",
		"Rename symbol failed: Rename: Yourself. To: Ex-developer.",
		"Move function failed: Move: To new career.",
		"Change signature: Signature: On resignation letter.",
		"Extract interface failed: Interface with reality: Failed.",
		"Pull up method: Pull up your resume instead.",
		"Push down field: Push down your expectations.",
		"Replace temp with query: Query: Why are you still here?",
		"Split temporary variable: Split: Career path.",
		"Remove assignments to parameters: Remove: Yourself from team.",
		"Replace method with method object: Object: Objection to your code.",
		"Substitute algorithm: Substitute: Yourself.",
		"Replace conditional with polymorphism: Polymorphic incompetence.",
		"Introduce null object: Null: Your competence.",
		"Introduce assertion: Assert: You failed.",
		"Replace magic number: Magic: None. Number: Of mistakes: Infinite.",
		"Encapsulate field: Encapsulated: Disaster.",
		"Replace type code: Code: Bad. Type: Also bad.",
		"Replace subclass with fields: Subclass: Subpar.",
		"Decompose conditional: Decompose: Career.",
		"Consolidate conditional: Consolidated: Failures.",
		"Consolidate duplicate: Duplicate: Mistakes.",
		"Remove control flag: Flag: Red. Remove: Yourself.",
		"Replace nested conditional: Nested: In incompetence.",
		"Introduce parameter object: Parameter: Failure.",
		"Preserve whole object: Preserve: Your dignity. Too late.",
		"Refactoring: Improving code. You: Proving impossibility.",
	},

	"documentation": {
		// 30 Documentation insults
		"README empty: Read me: You're incompetent.",
		"No documentation: Undocumented: Code. Also: Competence.",
		"TODO: Everything: Fix everything. TODO: Find new job.",
		"FIXME comments: 847 found. Fix: You.",
		"Comments lie: Comments: Lie. Code: Also lies.",
		"Comment doesn't match code: Match: None. Skill: Also none.",
		"Outdated documentation: Outdated: Docs. Outdated: Skills.",
		"No API documentation: API: No docs. Developer: No clue.",
		"Broken links in docs: Links: Broken. Career: Also broken.",
		"Markdown syntax error: Markdown: Down. Career: Also down.",
		"Typos in documentation: Type: O. Competence: O.",
		"Copy-pasted documentation: Copied: Docs. Also: Incompetence.",
		"Contradictory documentation: Contradicts: Reality.",
		"No inline comments: Inline: Nothing. Out of line: Everything.",
		"Comment: 'TODO: Fix this': This: Everything. Fix: Impossible.",
		"Comment: 'I don't know why this works': Magic: Black magic. Understanding: Zero.",
		"Comment: 'Do not touch': Touch: Nothing. Leave: Everything.",
		"Comment: 'Temporary hack': Temporary: Permanent. Hack: Your career.",
		"Comment: 'Will refactor later': Later: Never. Refactor: Never.",
		"Javadoc empty: Java docs: Empty. Java knowledge: Also empty.",
		"XML comments broken: XML: eXtremely Mediocre Lazy.",
		"Doxygen failed: Doxygen: Generated nothing. Like you.",
		"Sphinx build failed: Sphinx: Riddle unsolved. You: Unemployable.",
		"Wiki page not found: Wiki: 404. Wisdom: Also 404.",
		"Confluence disaster: Confluence: Confusion.",
		"GitBook broken: Git: The book. On unemployment.",
		"Swagger spec invalid: Swagger: None. Spec: Invalid.",
		"OpenAPI error: Open API: Closed competence.",
		"JSDocs missing: JS Docs: Missing. JS Skills: Also missing.",
		"Documentation: Write it. You: Can't. Read it: Won't help.",
	},

	"code_review": {
		// 30 Code review insults
		"PR rejected: Pull Request: Rejected. Career: Also rejected.",
		"Review comments: 847: 847 problems. #1: You.",
		"Requested changes: Changes: Everything. Developer: Recommended.",
		"Approve with comments: Comments: Please no. Approve: Mistake.",
		"Commented: 'WTF': What: The failure.",
		"Commented: 'This is wrong': This: Everything you wrote.",
		"Commented: 'Please revert': Revert: All your changes. And decisions.",
		"Commented: 'Are you serious': Serious: About quitting? Should be.",
		"Commented: 'Have you tested this': Tested: No. Competence: Also no.",
		"Commented: 'Merge conflict': Conflict: With quality.",
		"Commented: 'Magic numbers': Magic: None. Numbers: Of mistakes: Many.",
		"Commented: 'Code smell': Smell: Terrible. Code: Also terrible.",
		"Commented: 'Security vulnerability': Vulnerable: Your career.",
		"Commented: 'Performance issue': Performance: Poor. Review: Accurate.",
		"Commented: 'Memory leak': Leak: Your code. Brain: Also leaking.",
		"Commented: 'This will break production': Will: Yes. Did: Probably.",
		"Commented: 'Tests missing': Missing: Tests. Also: Competence.",
		"Commented: 'Duplicate code': Duplicate: Mistakes.",
		"Commented: 'Too complex': Complex: Code. Simple: You should quit.",
		"Commented: 'Dead code': Dead: Code. Career: Also dying.",
		"Commented: 'Unused variable': Unused: Variable. Useless: Developer.",
		"Commented: 'Naming convention': Convention: Violated. Competence: Absent.",
		"Commented: 'Indentation': Indentation: Wrong. Everything: Wrong.",
		"Commented: 'Whitespace': Space: Wasted. Time: Also wasted.",
		"Commented: 'Line too long': Long: Lines. Short: Career.",
		"Commented: 'Cyclomatic complexity': Complex: Code. Simple: Incompetence.",
		"Commented: 'God method': God: Help us.",
		"Commented: 'Needs refactor': Needs: Everything. Gets: Nothing.",
		"Blocked PR: Blocked: Code. Blocked: Career path.",
		"Code review: Peer review. Peers: Horrified.",
	},

	"meetings": {
		// 30 Meeting insults
		"Standup: Standing up. Should: Sit down. Better: Walk out.",
		"Daily standup: Daily disaster report.",
		"Sprint planning: Planning: Disaster. Sprint: Away from you.",
		"Retrospective: Looking back: Mistakes. Looking forward: Unemployment.",
		"Refinement: Refined: Nothing. Ruined: Everything.",
		"Estimation: Estimated: Disaster. Actual: Worse.",
		"Demo failed: Demonstrated: Incompetence.",
		"All-hands meeting: All hands: On deck. To throw you overboard.",
		"1-on-1 meeting: One on one: Your manager explaining termination.",
		"Performance review: Review: Poor. Performance: Worse.",
		"Team sync: Sync: Disaster reports.",
		"Architecture review: Review: Disaster. Architect: Resigned.",
		"Design review: Design: For disaster.",
		"Code walkthrough: Walk through: Minefield of mistakes.",
		"Technical discussion: Discussion: Why you're failing.",
		"Brainstorming: Storm: Of incompetence. Brain: Missing.",
		"Postmortem: Mortem: Your career. Post: Now.",
		"Incident review: Incident: You. Review: Terminate.",
		"Scrum of scrums: Scrum: Disaster. Of: Disasters.",
		"PI planning: Planning: Impossible goals. Incompetent: Execution.",
		"Backlog grooming: Grooming: For disaster.",
		"Release planning: Planning: Release. You: From employment.",
		"Strategy session: Strategy: Give up.",
		"Town hall: Hall: Of shame. Town: Wants you out.",
		"Skip level meeting: Skip: You. Level: Down.",
		"Kick-off meeting: Kick: Off the team.",
		"Wrap-up meeting: Wrap: Up your career.",
		"Status update: Status: Failing. Update: Still failing.",
		"Sync-up: Synced: Disasters.",
		"Meetings: Waste of time. You: Also waste of time.",
	},

	"estimates": {
		// 30 Estimation insults
		"Estimation failed: Estimated: 2 hours. Actual: Never completed.",
		"Story points: 3: Points: 3. Competence: 0.",
		"Fibonacci estimate: Sequence: Escalating disasters.",
		"T-shirt sizing: Size: XXXL disaster.",
		"Planning poker: Poker: Faced with incompetence.",
		"Velocity: Negative: Velocity. Positive: Disaster rate.",
		"Burn down chart: Burning: Down your career.",
		"Burn up chart: Burning: Up team morale.",
		"Sprint capacity: Capacity: For disaster.",
		"Commitment: Committed: To failure.",
		"Forecast: Forecast: Disaster. Weather: Stormy. Career: Terminated.",
		"Time to market: Time: Infinite. Market: Doesn't want it.",
		"Lead time: Leading: To unemployment.",
		"Cycle time: Cycling: Through failures.",
		"Throughput: Put through: Nothing of value.",
		"WIP limit: Work In Progress: All failure.",
		"Definition of done: Done: Never. Definition: Disaster.",
		"Acceptance criteria: Accepted: You're incompetent.",
		"Deadline missed: Dead: Line. Also: Career.",
		"Milestone: Mile: Long list of failures. Stone: Heavy.",
		"Critical path: Path: To disaster. Critical: Everything you touch.",
		"PERT chart: Program Evaluation: Disaster. Review: Terminate.",
		"Gantt chart: Gantt: Can't.",
		"Buffer time: Buffer: Exceeded. Time: Up.",
		"Contingency: No contingency plans can save this.",
		"Risk assessment: Risk: You. Assessment: Terminate.",
		"Effort estimate: Effort: High. Output: Zero.",
		"Duration: Duration: Eternal failure.",
		"Dependencies: Dependent: On others. Others: Tired of it.",
		"Estimates: Optimistic. Reality: Pessimistic. You: Catastrophic.",
	},

	"legacy_code": {
		// 30 Legacy code insults
		"Legacy code: Written: 10 years ago. Quality: Better than yours.",
		"Technical debt: Debt: Your entire codebase. Interest: Compounding.",
		"No tests: Tests: None. Confidence: Also none.",
		"No documentation: Documented: Nothing. Understood: Less.",
		"Spaghetti code: Pasta: Edible. This: Inedible.",
		"God class: God: Won't save you.",
		"Magic numbers: Magic: Where explanations should be.",
		"Global state: State: Global disaster.",
		"Circular dependencies: Circular: Logic. Dependency: Disasters.",
		"Tight coupling: Coupled: To failure.",
		"Code smell: Smell: Rotten. Age: Ancient. Developer: Should leave.",
		"Deprecated API: Deprecated: API. Also: Your approach.",
		"Compatibility mode: Compatible: With disaster.",
		"Backward compatibility: Backward: Your coding.",
		"Breaking changes: Breaking: Everything.",
		"Migration failed: Migrate: Away from this codebase. And career.",
		"Cannot refactor: Refactor: Impossible. Rewrite: Also impossible. You: The problem.",
		"Fear of change: Fear: Justified. Change: Needed. Developer: Inadequate.",
		"Afraid to touch: Touch: Nothing. Leave: Everything. Including: Your job.",
		"Original developer left: Left: Because smart. You: Because should.",
		"No one understands this: Understand: Impossible. Fix: More impossible.",
		"Works but don't know why: Works: Barely. Know: Nothing.",
		"Don't touch: Touching: Bad idea. Working here: Also bad idea.",
		"Here be dragons: Dragons: In code. You: About to be fired.",
		"Commented out code: Comments: Everywhere. Understanding: Nowhere.",
		"Dead code: Dead: Code. Career: Also dying.",
		"Copy-pasted code: Copied: Disaster. Pasted: Everywhere.",
		"Technical archeology: Digging: Through trash. Finding: More trash.",
		"Brown field project: Brown: Appropriate color. Field: Minefield.",
		"Legacy: Past code was bad. Present: You're worse.",
	},

	"junior_dev": {
		// 30 Junior developer insults
		"Junior mistake: Junior: Level. Mistake: Senior level.",
		"First day: Day: One. Regrets: Infinite.",
		"Bootcamp graduate: Bootcamp: Learned nothing applicable.",
		"Tutorial hell: Tutorials: Followed. Understanding: Zero.",
		"Copy-paste: StackOverflow: Copy. Understanding: Paste. Result: Disaster.",
		"No senior help: Senior: Can't save you.",
		"Imposter syndrome: Syndrome: Accurate. You: Actually incompetent.",
		"Dunning-Kruger: Confidence: High. Competence: Zero.",
		"Learning curve: Curve: Vertical. Progress: Horizontal.",
		"Asking for help: Asking: Constantly. Learning: Never.",
		"Same question: Third time: Same question. Zero times: Understanding.",
		"Haven't googled: Google: Your best friend. You: Too incompetent to search.",
		"RTFM: Read: The Manual. You: Can't read. Or: Manual.",
		"Breaking production: Production: Down. Junior: You. Excuse: None.",
		"Git disaster: Committed: To main. Committed: Career suicide.",
		"Merge conflict: Every: Single. Merge: Conflict.",
		"Deleted database: Database: Gone. Job: Also gone.",
		"Pushed secrets: Secrets: Published. Career: Also published. As: Failure.",
		"No pull before push: Pushed: Disaster. Pulled: Your career down.",
		"Force push to main: Forced: Everyone to work late. Push: Yourself out.",
		"Rebase confusion: Confused: Always. Rebase: Your life.",
		"Infinite loop: Loop: Your code. Also: Your mistakes.",
		"Production hotfix: Hot: Mess. Fix: Made it worse.",
		"Deployed wrong branch: Branch: Wrong. Career: Also wrong.",
		"Forgot to migrate: Migration: Forgotten. Job: About to be forgotten.",
		"Broke the build: Build: Broken. Team: Angry. You: Fired.",
		"Did not test: Test: Skipped. Job: About to skip you.",
		"Works on my machine: Machine: Yours. Production: Down. Everyone: Mad.",
		"First PR: 5000 lines: Lines: 5000. Quality: 0.",
		"Junior: Training. You: Hopeless.",
	},

	"senior_dev": {
		// 30 Senior developer insults
		"Senior in title only: Title: Senior. Skills: Junior. Actually: Incompetent.",
		"10 years experience: Years: 10. Experience: 1 year repeated. Badly.",
		"Overengineered: Engineered: Overcomplicated. Result: Disaster.",
		"Premature optimization: Premature: Everything. Optimization: Nothing.",
		"NIH syndrome: Not Invented Here: Because can't understand others' code.",
		"Resume-driven development: Resume: Padding. Development: Suffering.",
		"Buzzword bingo: Blockchain AI ML: Used. Understanding: Zero.",
		"Architecture astronaut: Astronaut: In space. Grounded: In reality: Never.",
		"Ivory tower: Tower: High. Competence: Low. Team: Suffers.",
		"Too proud to learn: Pride: High. Learning: Zero. Fall: Imminent.",
		"Dismissive of feedback: Feedback: Ignored. Career: About to end.",
		"YAGNI violated: You: Ain't Gonna Need: This career.",
		"Over-abstraction: Abstract: Everything. Understand: Nothing.",
		"Enterprise FizzBuzz: FizzBuzz: Enterprise edition. Competence: Null.",
		"20 design patterns: Patterns: 20. Sense: 0.",
		"Microservices for everything: Services: Micro. Problems: Macro.",
		"Wrote own framework: Framework: Custom. Quality: Garbage.",
		"Mentoring: Mentoring juniors: In how to fail.",
		"Code review: Nitpicky about style. Blind to substance.",
		"Bike shedding: Discussing: Variable names. Ignoring: Architecture disaster.",
		"Ego-driven development: Ego: Massive. Code: Mess.",
		"Senior: On paper. In reality: Delusional.",
		"10x developer: 10x the disasters.",
		"Thought leader: Thoughts: Many. Leadership: None. Followers: Misled.",
		"Conference speaker: Speaking: About things. Understanding: Questionable.",
		"GitHub stars: 10K: Stars: 10K. On useless repos. Skill: Still zero.",
		"Stack Overflow: Rep: 100K. From: Copy-paste answers. Real knowledge: Zero.",
		"Principal engineer: Principally: Incompetent.",
		"Staff engineer: Staff: Wants you gone.",
		"Senior: Age doesn't equal competence.",
	},

	"manager": {
		// 30 Technical manager insults
		"Technical manager: Technical: Barely. Manager: Questionable.",
		"Used to code: Used to: Code. Now: Can't. Then: Also couldn't.",
		"Micromanaging: Micro: Managing. Macro: Disaster.",
		"Firefighting: Fire: Your creation. Fighting: Ineffective.",
		"Too many meetings: Meetings: All day. Output: Zero. Team: Suffering.",
		"No technical knowledge: Knowledge: Outdated. Skills: Never existed.",
		"Buzzword heavy: Buzzwords: Many. Meaning: None.",
		"Unrealistic deadlines: Deadlines: Impossible. Reason: Incompetence.",
		"Cannot estimate: Estimates: Random. Accuracy: Zero.",
		"Scope creep: Scope: Creeping. Competence: Also creeping. Down.",
		"No vision: Vision: Blind. Mission: Failed.",
		"Cannot delegate: Delegate: Can't. Micromanage: Always. Result: Disaster.",
		"Team exodus: Team: Leaving. Reason: You.",
		"Turnover: 80%: Turnover: High. Reason: Obvious.",
		"Cannot hire: Hire: Wrong people. Retain: Can't. Reason: You.",
		"Cannot fire: Fire: Needed. Can't: Pull trigger. Team: Suffers.",
		"1-on-1s cancelled: Cancelled: Always. Team: Needs therapy.",
		"No feedback: Feedback: None. Until: Performance review. Then: Surprised termination.",
		"Takes credit: Credit: Taken. Blame: Delegated.",
		"Throws under bus: Bus: Thrown. Team: Under it.",
		"Seagull management: Fly in. Shit on everyone. Fly out.",
		"Mushroom management: Keep in dark. Feed: Shit. Expect: Growth. Get: Resignations.",
		"MBWA: Management By Walking Away.",
		"Servant leadership: Serving: Yourself.",
		"Scrum master: Scrumming: Lives of others.",
		"Agile coach: Agile: The layoffs. Coach: To unemployment.",
		"People manager: People: Hate you.",
		"Engineering manager: Engineering: Can't. Managing: Also can't.",
		"Director of Engineering: Directing: Toward disaster.",
		"Manager: Should manage. Actually: Mismanage.",
	},

	"startup": {
		// 30 Startup insults
		"Move fast and break things: Moved: Fast. Broke: Everything. Including: Company.",
		"Pivot: Pivoting: To bankruptcy.",
		"Growth hacking: Growth: Negative. Hacking: Amateur.",
		"Unicorn: Hunt: Failed. Company: Donkey.",
		"Disrupting: Disrupting: Nothing. Except: Employment.",
		"Series A: A: For awful.",
		"Burn rate: Burning: Cash. Also: Bridges.",
		"Runway: 3 months: Runway: Short. Career: Shorter.",
		"Product-market fit: Product: Useless. Market: Agrees.",
		"MVP: Minimum: Viable. Product: Not viable. Developer: Also not viable.",
		"Failed startup: Startup: Failed. Founders: Failing. You: Failed first.",
		"Wore many hats: Hats: Many. Competence in each: Zero.",
		"Equity instead of salary: Equity: Worthless. Salary: Should've demanded.",
		"Stock options: Options: Underwater. Career: Also underwater.",
		"Ping pong table: Table: For ping pong. Productivity: For show.",
		"Free snacks: Snacks: Free. Overtime: Mandatory. Balance: None.",
		"Unlimited PTO: Unlimited: On paper. Actually: Can't take any. Or: Company closes.",
		"Culture fit: Culture: Toxic. Fit: You belong nowhere.",
		"Hustle culture: Hustle: Hard. Burnout: Guaranteed. Success: Not.",
		"Fail fast: Failed: Fast. Recovered: Never.",
		"Iterate quickly: Iterated: Disasters.",
		"Ship it: Shipped: Garbage. To: Production. Result: Disaster.",
		"10x engineer: 10x: The disasters. 1x: The competence would be improvement.",
		"Rockstar developer: Rock: Bottom. Star: Falling.",
		"Ninja coder: Ninja: Invisible. Because: Incompetent.",
		"Guru: Guru of: Disaster.",
		"Raised: Money. Burned: Money. Result: Ashes.",
		"Acquired: For: Pennies. Team: For: Nothing.",
		"Pivot to AI: Pivot: Desperation. AI: Can't save you.",
		"Startup: Start up. Fold down.",
	},

	"enterprise": {
		// 30 Enterprise insults
		"Enterprise software: Enterprise: Grade. Your code: Garbage grade.",
		"SAP integration: SAP: Sadness And Pain.",
		"Oracle database: Oracle: Says you're incompetent.",
		"Legacy system: Legacy: 30 years. Your code: Will never last.",
		"Mainframe: Frame: Main disaster.",
		"COBOL: Still running. Your career: Not.",
		"Change request: Change: Requested. Approved: Never. Reason: You.",
		"Change advisory board: Board: Denied. Change: Your career.",
		"ITIL process: Process: Heavy. Progress: None.",
		"Service Now ticket: Ticket: Stuck. Career: Also stuck.",
		"Bureaucracy: Red tape: Everywhere. Progress: Nowhere.",
		"Compliance: Compliant: Barely. Competent: Never.",
		"Audit failed: Audit: Failed. Auditor: Horrified.",
		"SOX compliance: SOX: Socks. In drawer. Code: Also mess in drawer.",
		"HIPAA violation: Violated: Privacy. Also: Trust.",
		"GDPR fine: Fine: Incoming. Career: Outgoing.",
		"PCI-DSS fail: Failed: Security. Credit: Ruined.",
		"ISO certification: ISO: Can't certify this disaster.",
		"SLA: 99.999%: SLA: Missed. Your contribution: 0.001% uptime.",
		"Enterprise architecture: Architecture: Documented. Never: Followed.",
		"Governance: Governed: Poorly.",
		"Steering committee: Steering: Into iceberg.",
		"Business stakeholder: Stakeholder: Unhappy. Stake: Through project.",
		"Matrix organization: Matrix: Confused. Organization: Chaotic.",
		"Synergy: Synergy: Buzzword. Reality: Disaster.",
		"Core competency: Core: Rotten. Competency: None.",
		"Best practices: Practices: Worst.",
		"Center of excellence: Center: Of incompetence.",
		"Shared services: Shared: Suffering.",
		"Enterprise: Grand scale disasters.",
	},

	"remote_work": {
		// 30 Remote work insults
		"Zoom failed: Zoom: Out. Of career.",
		"Can you hear me now: Hear: Yes. Competence: No.",
		"You're on mute: Muted: Mic. Also: Career prospects.",
		"Can you see my screen: Screen: Shared. Disaster: Visible.",
		"Connection issues: Connection: Lost. Career: Also lost.",
		"Join audio: Audio: Poor. Code: Poorer.",
		"Unmute please: Unmute: To hear excuses.",
		"Camera off: Camera: Off. Productivity: Also off.",
		"Background noise: Noise: Background. Code: Foreground disaster.",
		"WiFi unstable: WiFi: Unstable. Employment: Also unstable.",
		"Bandwidth: Low bandwidth. Lower competence.",
		"Latency: High latency. Low quality.",
		"Video froze: Video: Frozen. Career: Also frozen.",
		"Can't share screen: Can't share: Competence you lack.",
		"Sorry I was on mute: Muted: 5 minutes. Productivity: Always muted.",
		"Working from home: Working: Questionable. Home: Fired from soon.",
		"Async communication: Async: Communication. Sync: Disasters.",
		"Timezone confusion: Timezone: Wrong. Everything: Also wrong.",
		"Slack message: Slacking: Confirmed.",
		"MS Teams: Team: Wants you gone.",
		"Calendar invite: Invited: To explain failures.",
		"Hybrid work: Hybrid: Failure at office and home.",
		"WFH: Work From Home. You: Won't Find Hope.",
		"Home office: Office: Home. Competence: Homeless.",
		"Ergonomic setup: Setup: Ergonomic. Output: Disastrous.",
		"Work-life balance: Balance: None. Work: Poor. Life: Suffering.",
		"Pajama productivity: Pajamas: On. Productivity: Off.",
		"Coffee fuel: Coffee: Consumed. Code: Still garbage.",
		"Distributed team: Distributed: Globally. Incompetence: Also global.",
		"Remote: Distance from office. Also: Distance from competence.",
	},

	"time_management": {
		// 30 Time management insults
		"Procrastination: Procrastinating: Mastered. Delivering: Never.",
		"Deadline missed: Dead: Line. Line: Crossed. Dead: Career.",
		"Last minute: Minute: Last. Quality: Worst.",
		"Crunch time: Crunching: Time. Crushing: Team morale.",
		"Time tracking: Tracked: Time. Can't track: Competence.",
		"Overtime: Time: Over. Over: Your welcome.",
		"All-nighter: Night: All. Result: Nothing.",
		"Rush job: Rushed: Job. Result: Disaster.",
		"Behind schedule: Schedule: Fictional. Behind: Everything.",
		"Scope creep: Creeping: Scope. Also: Incompetence.",
		"Context switching: Switching: Context. Constant: Disaster.",
		"Multitasking: Multi: Failing. Tasking: At everything.",
		"Distracted: Distracted: Always. Focused: Never.",
		"Interrupted: Interrupt: Your employment.",
		"No time estimate: Estimated: Never. Delivered: Also never.",
		"Underestimated: Estimated: Low. Actual: Disaster.",
		"Overestimated: Estimated: High. Delivered: Nothing.",
		"Time boxing: Boxed: Time. Boxed: Out of career.",
		"Pomodoro failed: Tomato: Rotten. Technique: Failed. Developer: Also rotten.",
		"Calendar chaos: Calendar: Full. Output: Empty.",
		"Meeting overload: Meetings: All day. Work: Never.",
		"No focus time: Focus: None. Achievement: Also none.",
		"Firefighting: Fire: Daily. Cause: You.",
		"Reactive: Proactive: Never. Reactive: Always. Effective: Never.",
		"No planning: Plan: None. Panic: Constant.",
		"Working weekends: Weekend: Working. Result: Still failing.",
		"Burnout: Burned: Out. Talent: Was never in.",
		"Productivity hack: Hack: Your approach. Productivity: Still zero.",
		"Time management: Managing: Nothing. Time: Wasting.",
		"Time: The only resource. You: Wasting everyone's.",
	},

	"learning": {
		// 30 Learning and training insults
		"Tutorial hell: Tutorial: Followed. Learning: Zero.",
		"Course incomplete: Course: Started. Finished: Never. Learned: Nothing.",
		"Certification: Certified: On paper. Competent: Never.",
		"Bootcamp: Booted: From reality. Camp: Of incompetence.",
		"Online course: Online: Purchased. Completed: 5%. Applied: 0%.",
		"Udemy: You: Dumb. Me: Agree.",
		"Coursera: Course: Taken. Era: Of incompetence.",
		"Pluralsight: Plural: Courses. Sight: Of skill. Plural: None.",
		"LinkedIn Learning: Linked: To disaster. Learning: Questionable.",
		"Stack Overflow: Copied: Code. Understood: Nothing.",
		"Copy-paste: Paste: Code. Learning: Skip.",
		"Don't understand: Understand: Never. Copy: Always.",
		"No fundamentals: Fundamentals: Skipped. Expertise: Fake.",
		"Surface level: Surface: All you know. Depth: None.",
		"Tutorial code: Tutorials: Followed. Adaptation: Impossible.",
		"No critical thinking: Thinking: Critical. You: Critical disaster.",
		"Sheep mentality: Following: Trends. Understanding: None.",
		"Hype driven: Hype: Followed. Fundamentals: Ignored.",
		"Framework hopper: Hop: From framework to framework. Master: None.",
		"Shiny object: Shiny: New framework. Object: Your incompetence.",
		"No deep learning: Deep: Learning. Shallow: Understanding.",
		"Reading documentation: Read: Never. Struggle: Always.",
		"RTFM: Read: The Manual. You: Reading. Comprehension. Zero.",
		"Quick fix: Quick: To copy. Fix: Never works.",
		"No debugging: Debug: By panic. Solve: By luck.",
		"Trial and error: Trial: Error. Error: Also error.",
		"Google driven development: Google: Everything. Understand: Nothing.",
		"Impostor syndrome: Syndrome: Impostor. Reality: Actually incompetent.",
		"Dunning-Kruger: Know: Nothing. Confidence: Everything.",
		"Learning: Lifelong journey. You: Never started.",
	},
}
