package llm

// InsultExpansionV2 - ROUND 2: 1000+ MORE INSULTS!
// Themed categories + Generic savage insults for unlimited roasting power
var InsultExpansionV2 = map[string][]string{

	// ==================== NEW THEMED CATEGORIES ====================

	// TESTING (50 insults)
	"testing": {
		"Your tests are so flaky, they come with a dandruff warning.",
		"'It works on my machine' - the battle cry of someone who's never heard of testing.",
		"You write tests like someone who's never seen their code fail. Spoiler: it will.",
		"Your test coverage is 0%. Your confidence should match.",
		"Writing tests after deployment is like buying insurance after the accident.",
		"Your mocks are so fake, they make reality TV look authentic.",
		"'I'll write tests later' - Famous last words from 2019.",
		"Your E2E tests take longer than the heat death of the universe.",
		"You unit test like someone who doesn't understand what a 'unit' is.",
		"Your integration tests integrate nothing except your incompetence.",
		"Test-driven development? You're more like test-avoiding development.",
		"Your assertions assert nothing except your confusion.",
		"100% test coverage, 0% brain coverage.",
		"You treat test fixtures like horoscopes - vague and unreliable.",
		"Your test data is more fictional than your job title.",
		"Writing one test per file doesn't mean you're thorough, it means you're lazy.",
		"Your snapshot tests snapshot your incompetence perfectly.",
		"'Tests are passing!' Yeah, so is gas. Both stink.",
		"You mock everything except your own skill level, which is the real joke.",
		"Your test pyramid is upside down, just like your career trajectory.",
		"Flaky tests are just your code's way of saying 'I give up.'",
		"You write tests like someone who's afraid of finding bugs.",
		"Your code-to-test ratio is 1000:1. The 1 is a TODO comment.",
		"Testing in production isn't a strategy, it's a cry for help.",
		"Your regression tests regress faster than your skills.",
		"'It's not a bug, it's a feature' - said no test ever.",
		"Your test isolation is so bad, they're forming support groups.",
		"You treat CI failures like spam emails - ignored and deleted.",
		"Your parametric tests have one parameter: failure.",
		"'Green tests!' - Because you forgot to actually test anything.",
		"Your before/after hooks are more tangled than your headphones.",
		"Test doubles? You can't even get test singles to work.",
		"Your tests are so slow, they qualify for disability benefits.",
		"Mocking the database doesn't mean you can mock quality.",
		"Your test suite has more red flags than a Soviet parade.",
		"'All tests passed!' - Said the person who never ran them.",
		"Your edge cases have edge cases. None are tested.",
		"You test like someone who's never heard of edge cases.",
		"Your happy path is the only path you know. Reality disagrees.",
		"Integration? The only thing integrating is your failure across systems.",
		"Your smoke tests just produce actual smoke.",
		"End-to-end? Your tests end before they begin.",
		"'Works on my machine' should be your LinkedIn headline.",
		"Your test environment is production. Your users are not amused.",
		"Mutation testing would die of boredom analyzing your code.",
		"Your test strategy is 'hope and pray.' God is busy.",
		"You write tests like they're optional homework. They're not.",
		"Your code coverage tool died of sadness at 3%.",
		"Tested in production, failed in production, surprised in production.",
		"Your tests test nothing except the patience of your CI server.",
	},

	// SECURITY (50 insults)
	"security": {
		"Your security model is 'security through obscurity.' You're very obscure.",
		"Hardcoding credentials? Bold strategy for your inevitable data breach.",
		"Your password validation accepts '12345'. So does everyone's exploit.",
		"SQL injection? You're basically leaving the door open and yelling 'ROB ME!'",
		"Your CORS policy is '*'. So is your future unemployment status.",
		"Authentication? You spell it 'authentication optional.'",
		"Your JWT secrets are in the repo. So is your career endpoint.",
		"XSS vulnerabilities in 2025? That's not retro, that's negligent.",
		"You treat HTTPS like it's optional. Your users treat your app the same way.",
		"Your API keys are in the frontend. Hackers are sending thank-you notes.",
		"Rate limiting? You've never heard of it, and now you're DDoS'd.",
		"Your sessions never expire. Neither will your security incidents.",
		"Sanitizing user input? You've heard of it, just never done it.",
		"Your access controls have more holes than Swiss cheese.",
		"CSRF tokens? You thought those were Star Wars characters.",
		"Your security headers are missing like your job security.",
		"Bcrypt? You're still using MD5 like it's 2005.",
		"Your secrets manager is a .env file in the repo. Professional.",
		"2FA? You barely have 1FA working.",
		"Your OAuth implementation makes OAuth 1.0 look secure.",
		"Privilege escalation? Your app starts at root. Bold.",
		"Your cookie flags are all wrong. So is everything else.",
		"OWASP Top 10? You're speedrunning all 10 simultaneously.",
		"Your encryption key is 'password123'. Creative.",
		"Directory traversal attacks work because you forgot paths exist.",
		"Your session management is managed by hope and prayer.",
		"Input validation? You validate nothing except your incompetence.",
		"Your security audit would be 1 page: 'Everything is broken.'",
		"Storing passwords in plaintext? It's bold, I'll give you that.",
		"Your firewall rules are 'allow all.' So are your vulnerabilities.",
		"Content Security Policy? You have a content insecurity policy.",
		"Your dependencies have 847 critical CVEs. You have 0 updates.",
		"SQL injection, XSS, and CSRF walk into your API. All three succeed.",
		"Your threat model is 'nobody will find us.' They will.",
		"Security by default? You're insecure by design.",
		"Your API accepts any token. Including 'token'.",
		"Logging sensitive data? That's not debugging, that's a breach waiting to happen.",
		"Your permissions system is 'everyone is admin.' Chaos achieved.",
		"You disabled SSL verification to fix a bug. You created a bigger one.",
		"Your security questions are more secure than your actual security.",
		"Penetration testing? Your app penetrates itself daily.",
		"Your VPN is exposed to the internet. That defeats the purpose.",
		"You trust client-side validation. Hackers don't.",
		"Your secrets are in environment variables... printed in logs.",
		"Role-based access? Everyone's role is 'superuser.'",
		"Your authentication flow has more bypasses than a triple bypass surgery.",
		"You thought security was a feature, not a requirement. Wrong.",
		"Your encryption algorithm is ROT13. Twice. For 'extra security.'",
		"HTTPS redirect? You're serving credentials over HTTP like it's 1999.",
		"Your security model is a house of cards in a hurricane.",
	},

	// PERFORMANCE (50 insults)
	"performance": {
		"Your app is so slow, users think their internet is broken.",
		"O(n²) complexity? You're running O(n!) in production like a maniac.",
		"Your query selects * from everything. So does your unemployment letter.",
		"Loading spinners are not a feature, they're a symptom.",
		"Your API response time is measured in geological epochs.",
		"Caching? You've heard of it, just never implemented it.",
		"Your N+1 queries have N+1 problems.",
		"Premature optimization is the root of all evil. You have the opposite problem.",
		"Your database indexes are missing like your performance targets.",
		"Pagination? You load 10,000 rows and call it 'fast.'",
		"Your memory leaks are so bad, Chrome looks efficient.",
		"Lazy loading? You're eagerly loading everything like it's Black Friday.",
		"Your bundle size is larger than the Apollo 11 codebase.",
		"Debouncing? You've triggered this function 847 times in 1 second.",
		"Your websocket is polling every 100ms. That's not real-time, that's real dumb.",
		"CDN? You're serving 50MB of assets from a potato server in your basement.",
		"Your images are uncompressed 8K PNGs. For a 32px icon.",
		"Code splitting? You're code bloating.",
		"Your render time makes dial-up look fast.",
		"Memoization? You're recalculating the same thing 1000 times per render.",
		"Your database has no indexes. Your performance has no future.",
		"Throttling API calls? You're DDoSing your own server.",
		"Your waterfall chart looks like actual waterfalls. Slow ones.",
		"Tree shaking? Your bundle has the whole forest.",
		"Your critical rendering path is more critical than ICU.",
		"Async/await? You're blocking the event loop like it's a protest.",
		"Your TTI is 45 seconds. That's Time To Insanity.",
		"Lighthouse score: 12. Out of 100. In all categories.",
		"Your SQL joins join everything except your brain cells.",
		"Full table scans in production? That's not brave, that's broken.",
		"Your cache invalidation strategy is 'never cache anything.'",
		"Virtual scrolling? You're rendering 10,000 DOM nodes like it's nothing. It's something. It's bad.",
		"Your worker threads are working overtime compensating for your code.",
		"Compression? Your responses are larger than the requests.",
		"Your API calls are nested 15 levels deep. That's not architecture, that's archaeology.",
		"Prefetching? You're postfetching everything after the user gives up.",
		"Your heap size grows faster than your skill set (which is static).",
		"GC pauses are so long, users think the app crashed.",
		"You're using .filter().map().filter().map(). Just use one loop, genius.",
		"Your database query planner gave up. So should you.",
		"Batch requests? You're making 847 individual API calls per page load.",
		"Your regex is so complex, it causes ReDoS attacks on itself.",
		"HTTP/2? You're still on HTTP/1.1 with keep-alive disabled.",
		"Your LCP is 'Longest Career Plummet.'",
		"You're streaming 4K video over a REST API. Frame by frame. In JSON.",
		"Your app uses 8GB of RAM to display 'Hello World.'",
		"Infinite scroll? You loaded everything at once. That's finite disaster.",
		"Your for-loops have for-loops. Nested 5 levels deep.",
		"Web workers? Your main thread is working hard enough failing.",
		"Your performance budget is 'unlimited resources.' Reality disagrees.",
	},

	// CLOUD PROVIDERS (50 insults)
	"cloud": {
		"Your AWS bill is higher than your salary. Both are mistakes.",
		"'Serverless' doesn't mean brainless, but you're testing that theory.",
		"Your Lambda function costs more than running it on a mainframe.",
		"EC2 instances running 24/7 for a cron job that runs once a week. Efficient.",
		"Your S3 bucket is public. So is your incompetence.",
		"'Cloud native' means you're natively confused.",
		"Your CloudFormation template is 5000 lines of regret.",
		"You're using t2.micro for a production database. Bold and stupid.",
		"Your region selection was 'random.' So are your outages.",
		"Auto-scaling? You manually restart instances at 3 AM.",
		"Your IAM policy is 'AdministratorAccess' for everyone. Security 101: failed.",
		"Reserved instances? You're paying on-demand prices for 5 years of mistakes.",
		"Your Kubernetes cluster has 1 pod. Running nginx. Overkill achievement unlocked.",
		"Multi-region failover? You're single-region failover. To failure.",
		"Your VPC configuration is so wrong, even AWS is confused.",
		"Spot instances for production databases? That's not cost-saving, that's career-ending.",
		"Your CloudWatch alarms alarm nobody because you disabled them.",
		"Elastic Beanstalk? More like elastic blunder.",
		"You're running a monolith on 50 microservices. That's not distributed, that's disturbed.",
		"Your SQS queue is backing up like your career prospects.",
		"DynamoDB partition keys? You chose the worst one possible.",
		"Your RDS instance has no backups. Neither does your employment.",
		"Terraform state in S3 with no locking? You enjoy corrupted infrastructure.",
		"Your ECS task definition uses 'latest' tag. Production loves surprises!",
		"Load balancer for a single instance? That's not redundancy, that's stupidity.",
		"Your API Gateway costs more than your actual servers.",
		"CloudFront caching? You set TTL to 0. That's not a CDN, that's a proxy.",
		"Your billing alerts trigger after you're already bankrupt.",
		"Serverless Aurora? You're paying for serverless prices with full-time regret.",
		"Your security groups allow 0.0.0.0/0 on all ports. Hackers thank you.",
		"Cross-region replication? You can't get single-region working.",
		"Your EKS cluster costs $500/month before you deploy anything.",
		"SNS/SQS? You're using polling instead of events like it's 2010.",
		"Your cloud architecture was designed in a fever dream.",
		"Fargate prices making you rethink life choices yet?",
		"Your NAT gateway costs more than your coffee budget. Both keep you awake at night.",
		"You deployed to the wrong region. For 6 months. Nobody noticed.",
		"Your CloudTrail logs are disabled. So is your situational awareness.",
		"Elastic IPs you forgot to release are billing you into oblivion.",
		"Your Route53 routing is more lost than your career.",
		"You're using Step Functions for a simple if/else. Overcomplicated is your brand.",
		"Your EBS volumes are gp2. In 2025. Living in the past.",
		"Cost optimization? You're cost maximization.",
		"Your tags are a mess, just like your infrastructure.",
		"Multi-AZ deployment? You're single-AZ and hoping for the best.",
		"Your backups backup nothing except your mistakes.",
		"CloudFormation drift detected. So is your competence drift.",
		"You're running Windows Server on EC2. Why do you hate yourself?",
		"Your data transfer costs are 80% of your bill. Design better.",
		"AWS Well-Architected Framework? You're AWS Poorly-Architected Disaster.",
	},

	// DEVOPS (50 insults)
	"devops": {
		"Your CI/CD pipeline is CI (Continuous Instability) / CD (Continuous Disasters).",
		"'Works on my machine' - Time to ship your machine.",
		"Your deployment process is 47 manual steps. All error-prone.",
		"Blue-green deployment? You're red-dead deployment.",
		"Your rollback strategy is 'panic and pray.'",
		"Infrastructure as Code? You have Infrastructure as Chaos.",
		"Your monitoring monitors nothing except your failure rate.",
		"Automated deployments? You're manually SSH'ing into production at 2 AM.",
		"Your Docker images are 5GB each. That's not containerization, that's bloatware.",
		"'Latest' tag in production? You like living dangerously.",
		"Your CI builds take 2 hours. By then, the code is already outdated.",
		"Zero downtime deployment? You're all-downtime deployment.",
		"Your secrets are in plain text in your pipeline. Bold move.",
		"GitOps? You're doing GitOuch.",
		"Your health checks check nothing except the server's pulse (it's dead).",
		"Immutable infrastructure? You're mutating everything including your job security.",
		"Your deploy script is 'git pull && restart.' Professional.",
		"Container orchestration? You can barely orchestrate a 'hello world.'",
		"Your Jenkins instance has 847 failed jobs and 0 successful deploys.",
		"Canary deployment? Your canary died immediately. So will your app.",
		"Your Ansible playbook is a playbook on how to fail.",
		"Service mesh? You have service mess.",
		"Your artifact versioning is 'final-final-v2-ACTUALLY-FINAL.'",
		"Observability? You can't observe your own mistakes.",
		"Your logging strategy is 'grep production logs and hope.'",
		"Feature flags? You deploy directly to production and fix in prod.",
		"Your pipeline fails 90% of the time. The 10% are false positives.",
		"Helm charts? You're steering into an iceberg.",
		"Your backup restoration has never been tested. It won't work.",
		"Configuration drift? Your environments are quantum superpositions.",
		"Your deployment frequency is 'whenever someone is brave enough.'",
		"GitLab CI, GitHub Actions, Jenkins, CircleCI running simultaneously. None working.",
		"Your Docker layers are cached from 2019.",
		"Environment parity? Dev is Ubuntu, prod is Alpine, staging is Windows. Why.",
		"Your smoke tests create actual smoke.",
		"Continuous Integration? You're continuously disintegrating.",
		"Your build cache is poisoned. So is your architecture.",
		"Release tags? Your tags are more random than your variable names.",
		"Your deployment windows are 'Friday at 5 PM.' Career suicide.",
		"Terraform apply with no plan? You enjoy infrastructure surprises.",
		"Your pipeline secrets expired 6 months ago. So did your deployments.",
		"Post-deployment validation? You validate in production with users.",
		"Your rollback takes longer than moving forward. Both end in failure.",
		"Artifact repository? You're committing binaries to git.",
		"Your deployment announcement is 'oops, we pushed to prod.'",
		"Shadow IT is more organized than your DevOps practices.",
		"Your monitoring dashboard is a blank screen. Accurate representation.",
		"Deployment checklist? You have a deployment prayer.",
		"Your infrastructure provisioning is 'ClickOps' in the AWS console.",
		"DevOps culture? You have DevOops culture.",
	},

	// MONITORING (50 insults)
	"monitoring": {
		"Your monitoring is so bad, you learn about outages from Twitter.",
		"Alerting? Your users alert you when things break.",
		"Your dashboard shows nothing except your incompetence.",
		"Prometheus metrics? You're collecting nothing except problems.",
		"Your SLA is 'Sometimes It Works.' Not very reassuring.",
		"Grafana graphs graphing your declining career trajectory.",
		"Your on-call rotation is 'whoever picks up the phone.'",
		"Alert fatigue? You get 847 alerts per hour, all ignored.",
		"Your monitoring tool monitors the monitoring tool. Both are down.",
		"Distributed tracing? You can't even trace single requests.",
		"Your error rate is 50%. Your monitoring catches 0%.",
		"Synthetic monitoring? You have synthetic competence.",
		"Your runbooks are outdated, incomplete, and fictional.",
		"APM tools show your app is slow. Users didn't need a tool for that.",
		"Your metrics have metrics. None are useful.",
		"Log aggregation? Your logs are scattered like your focus.",
		"Uptime monitoring says 99.9%. It's lying. So are you.",
		"Your alerting thresholds are 'when everything is on fire.'",
		"SLI, SLO, SLA? You have NFI (No F***ing Idea).",
		"Your incident response time is 'after the incident is over.'",
		"CloudWatch dashboards that watch nothing except your failures.",
		"Your metrics retention is 1 hour. So is your memory of past mistakes.",
		"Anomaly detection? The only anomaly is that anything works.",
		"Your pager goes off at 3 AM every day. Time to fix your code, not your alarm.",
		"Service level objectives? Your only objective is survival.",
		"Error budgets? You're over budget in everything including errors.",
		"Your monitoring costs more than your actual infrastructure.",
		"Real User Monitoring? Real users have abandoned your app.",
		"Your baseline metrics baseline disaster.",
		"Alerting rules that alert on everything, action on nothing.",
		"Your MTTR is measured in days. Mean Time To Resume is measured in never.",
		"Incident postmortems? You're too busy having new incidents.",
		"Your health checks return 200 OK while everything burns.",
		"Custom metrics tracking custom failures.",
		"Your dashboards are red, yellow, and 'oh no.'",
		"Monitoring best practices? You're practicing worst practices.",
		"Your metric cardinality is exploding. So is your Prometheus.",
		"Alert correlation? You can't correlate cause and effect.",
		"Your logging levels: debug in production, silent in development.",
		"Performance monitoring showing consistent terrible performance.",
		"Your SRE team is you, alone, crying.",
		"Black-box monitoring can't see inside your black box of chaos.",
		"White-box monitoring reveals everything you hoped to hide.",
		"Your telemetry tells a tale of terror.",
		"Service dependency mapping? Everything depends on luck.",
		"Your alert notifications go to a dead email address. Fitting.",
		"Capacity planning? You're planning for failure capacity.",
		"Your monitoring covers 5% of your systems. The wrong 5%.",
		"Time series databases can't capture your timeless incompetence.",
		"Your metrics are vanity metrics: they make you look worse.",
	},

	// DATABASES (50 insults)
	"database_advanced": {
		"Your database normalization stopped at 0NF. Maybe negative.",
		"ACID compliance? Your database is more like BASE (Basically Available, Soft state, Eventually consistent, Eventually broken).",
		"Your foreign keys reference nothing except your poor life choices.",
		"Indexing strategy? SELECT * FROM career_mistakes WHERE indexed = false;",
		"Your JOIN queries join together like a car crash.",
		"Denormalization for performance? You're denormalizing yourself out of a job.",
		"Your transaction isolation level is 'READ UNCOMMITTED CHAOS.'",
		"Deadlocks? Your database locks dead every hour.",
		"Your connection pool is a connection puddle of despair.",
		"Stored procedures storing nothing except technical debt.",
		"Your schema has more circular references than your logic.",
		"Database migrations that migrate away from functionality.",
		"Your primary keys aren't unique. Neither are your mistakes - they're all the same.",
		"Composite indexes? You can't even do simple indexes.",
		"Your query optimizer gave up optimizing your career.",
		"Full outer joins on production tables with billions of rows. Bold.",
		"Your database backups are corrupted. Like your code.",
		"Point-in-time recovery? You can't recover from any point in time.",
		"Replication lag is 6 hours. So is your awareness.",
		"Your CASCADE DELETE deleted the whole database. And your job.",
		"Triggers triggering other triggers in an infinite loop of doom.",
		"Your ORM generates queries that would make SQL Server cry.",
		"N+1 queries? Try N+1000 queries per page load.",
		"Your database transactions are more committed than you are.",
		"Read replicas? You can barely read the primary.",
		"Sharding strategy: throw everything in one shard and hope.",
		"Your database collation is set to 'random chaos.'",
		"Prepared statements? You're concatenating SQL strings like it's 1999.",
		"Your cursors are more outdated than your resume.",
		"Database views viewing other views 15 levels deep.",
		"Your explain plan explains you should change careers.",
		"Materialized views that materialize your incompetence.",
		"Your database charset is a character assassination on yourself.",
		"Referential integrity? You have referential disintegrity.",
		"Your temp tables are more permanent than your employment.",
		"Spatial indexes for your spatial awareness: both are broken.",
		"Your partition tables partition your sanity.",
		"Database locks timing out like your career prospects.",
		"Your SQL injection vulnerabilities have SQL injection vulnerabilities.",
		"Connection strings in the codebase. Professional.",
		"Your database pool is leaking connections like your code leaks bugs.",
		"Optimistic locking? You're pessimistically terrible.",
		"Your WAL logs wall you into a corner of failure.",
		"Eventual consistency? Eventually you'll be unemployed.",
		"Your database backups backup nothing except mistakes.",
		"Multi-master replication where all masters fail simultaneously.",
		"Your CTEs (Common Table Expressions) express common incompetence.",
		"Window functions? Your window of opportunity is closed.",
		"Your database audit logs audit your path to unemployment.",
		"Row-level security? You have career-level insecurity.",
	},

	// SCALABILITY (50 insults)
	"scalability": {
		"Your app scales like a whale trying to climb stairs.",
		"Horizontal scaling? You're vertically failing.",
		"Your architecture scales to exactly 1 user. Maybe.",
		"Load balancing? All the load is on one server crying for help.",
		"Your rate limits are 'unlimited chaos.'",
		"Stateless design? You're statefully confused.",
		"Your caching layer caches nothing except problems.",
		"Microservices? You created a distributed monolith. Worst of both worlds.",
		"Your message queue is backed up to 2019.",
		"Elasticity? Your infrastructure is rigidly broken.",
		"Your CDN doesn't distribute, it consolidates failures.",
		"Service discovery? Your services are lost and undiscoverable.",
		"Your circuit breaker is permanently open. Like your job search.",
		"Backpressure? The only pressure is from your manager to fix this.",
		"Your async processing is sync suffering.",
		"Event-driven architecture? You're event-driven to failure.",
		"Your worker pool is more like a worker puddle.",
		"Database read replicas all reading from broken primary.",
		"Your API versioning is 'break everything with each release.'",
		"Graceful degradation? You degrade disgracefully.",
		"Your retry logic retries infinitely, achieving nothing.",
		"Bulkhead pattern? Your ship is sinking regardless.",
		"Your saga pattern is a saga of poor decisions.",
		"CQRS? You have CQFS (Command Query Failure System).",
		"Your event sourcing sources only disasters.",
		"Serverless at scale? You're servermore at fail.",
		"Your autoscaling scales down during traffic spikes. Genius.",
		"Sticky sessions sticking users to dead servers.",
		"Your load shedding sheds users, not load.",
		"Database connection pooling? You're pooling incompetence.",
		"Your pub/sub publishes problems, subscribers get failures.",
		"Eventual consistency eventually consistent with failure.",
		"Your streaming data streams into /dev/null.",
		"Fan-out pattern fanning out your career flames.",
		"Your aggregate pattern aggregates technical debt.",
		"Data partitioning partitioning your sanity.",
		"Your sharding logic is shard-ed (shattered).",
		"Consistent hashing consistently hashing your career.",
		"Your throttling throttles success.",
		"Distributed caching distributing cache misses.",
		"Your queue consumers consume nothing except resources.",
		"Leader election elects nobody because all nodes are dead.",
		"Your distributed locks lock out functionality.",
		"Consensus algorithms can't reach consensus on your incompetence (it's unanimous).",
		"Your replication factor is 0. Like your success rate.",
		"Data locality? Your data is locally and globally inaccessible.",
		"Your CAP theorem is choosing none of the options.",
		"Multi-tenancy? Single tenant can't even use it.",
		"Your orchestration orchestrates chaos symphonies.",
		"Service mesh meshing together failures beautifully.",
	},

	// ==================== GENERIC SAVAGE INSULTS (500+) ====================
	// These work for ANY failure - the ultimate fallback insults!

	"savage_generic": {
		"I've seen better decision-making from a Magic 8-Ball.",
		"Your code is a warning to future generations.",
		"This is why we can't have nice things. Or working things.",
		"I'd explain what went wrong, but I don't have all week.",
		"Your commit history reads like a tragedy in three acts. All bad.",
		"Somewhere, a computer science professor is crying and they don't know why.",
		"This code is the 'before' picture in every programming tutorial.",
		"I've seen AI hallucinations more coherent than this.",
		"Your approach to programming is 'try random things until something doesn't crash.'",
		"This is what happens when Stack Overflow answers go wrong.",
		"You've invented a new anti-pattern. Congratulations, it's terrible.",
		"Your code comments explain nothing except that you're lost.",
		"I would say you tried your best, but did you though?",
		"This code violates the Geneva Convention on programmer rights.",
		"You're not failing fast, you're failing comprehensively.",
		"Your git blame points to you. Your team agrees.",
		"This is the programming equivalent of a cry for help.",
		"You've achieved something rare: making everyone agree it's bad.",
		"Your code review needs a content warning.",
		"This isn't legacy code yet, but it's already a legacy problem.",
		"You program like someone who's never seen a working program.",
		"Your debugging strategy is 'add print statements and hope.'",
		"I've seen ransomware with better architecture.",
		"Your code is so bad, it's being studied by researchers.",
		"This violates best practices. And worst practices. And all practices.",
		"You're not thinking outside the box. You're outside the galaxy.",
		"Your approach is innovative. Innovatively terrible.",
		"This code will be used in 'what not to do' presentations.",
		"You've created a Rube Goldberg machine of failure.",
		"Your solution is technically a solution like poison is technically a beverage.",
		"I've seen better logic in fever dreams.",
		"Your code is the reason seniors quit and juniors cry.",
		"This is weaponized incompetence in digital form.",
		"You've turned simple problems into complex disasters. Impressive.",
		"Your efficiency is efficiently creating inefficiency.",
		"This code smells. Like a dumpster fire. In summer.",
		"You're speed-running 'How to Get Fired' any%.",
		"Your solution solves nothing except 'how to waste time.'",
		"This is why code review exists. To stop this.",
		"Your architecture is held together by hope and technical debt.",
		"I've seen spaghetti code. This is the entire Italian restaurant.",
		"You've invented a new way to fail. Nobody asked for this.",
		"Your code is a masterclass in what not to do.",
		"This deserves its own error code: 418 I'm a developer (but shouldn't be).",
		"You're not reinventing the wheel, you're un-inventing it.",
		"Your commit message: 'fix stuff.' Your actual commit: 'break everything.'",
		"This code has the same energy as 'hold my beer, watch this.'",
		"You've created job security... for your replacement.",
		"Your solution is a problem looking for a worse problem.",
		"This is the code equivalent of 'task failed successfully.'",
	},

	"savage_generic_2": {
		"I didn't know it was possible to be this wrong, but you found a way.",
		"Your code is proof that infinite monkeys on infinite keyboards produce garbage.",
		"This isn't code, it's a war crime against computers.",
		"You've successfully lowered the bar. Then dug under it.",
		"Your git history is a horror story told in commits.",
		"This code makes GOTO statements look reasonable.",
		"You're not just wrong, you're confidently wrong. Worst combination.",
		"Your solution is the problem's evil twin.",
		"This is the code they show at 'scared straight' programs for CS students.",
		"You've achieved negative productivity. We're worse off than before.",
		"Your code is a perfect example of 'how did this ever work?'",
		"This violates laws I didn't know existed.",
		"You're operating on a level of wrongness previously thought impossible.",
		"Your solution is a cry for help wrapped in syntax errors.",
		"This code aged like milk. Milk that was already expired.",
		"You've created something truly unique: universally hated code.",
		"Your approach to programming is 'chaos as a service.'",
		"This isn't technical debt, it's technical bankruptcy.",
		"You're not in the weeds, you're in the whole overgrown forest.",
		"Your code is a case study in how not to code.",
		"This is what happens when you learn to code from error messages.",
		"You've turned gold into lead. The reverse alchemist.",
		"Your debugging process is 'break it more and see what happens.'",
		"This code is the 'before' in every refactoring example.",
		"You're writing code like it's a ransom note - threatening and incomprehensible.",
		"Your architecture is a house of cards in a wind tunnel.",
		"This is the programming equivalent of friendly fire.",
		"You've achieved what we thought impossible: negative code quality.",
		"Your solution is technically correct in zero universes.",
		"This code will be taught in classes on 'catastrophic failures.'",
		"You're not missing the forest for the trees, you're missing everything.",
		"Your commit should come with a hazmat warning.",
		"This is why aliens don't visit us.",
		"You've created a self-documenting disaster. It documents your incompetence.",
		"Your code is a monument to everything wrong with software.",
		"This isn't a bug, it's a feature-length disaster film.",
		"You're playing 4D chess while everyone else is playing working software.",
		"Your solution makes the problem look good by comparison.",
		"This code is the reason we have code reviews. And therapy.",
		"You've weaponized your incompetence into deployable form.",
		"Your approach is bold. Boldly catastrophic.",
		"This is the code equivalent of 'what could possibly go wrong?' Everything. Everything went wrong.",
		"You've turned a feature request into a support ticket generator.",
		"Your code is so bad, it's good. Jk, it's just bad.",
		"This is what happens when you code first, think never.",
		"You're not just moving fast and breaking things, you're stationary and breaking everything.",
		"Your solution is a Trojan horse of failure.",
		"This code has the structural integrity of wet cardboard.",
		"You've created a distributed system of disappointment.",
		"Your architecture is more tangled than headphone cords.",
	},

	"savage_generic_3": {
		"This code is the butterfly effect of bad decisions.",
		"You're not just digging yourself into a hole, you're mining for rock bottom.",
		"Your solution is like a Swiss Army knife - if all the tools were broken.",
		"This is the code they use to test antivirus software.",
		"You've created an infinite loop of regret.",
		"Your approach to programming is 'fake it till you can't make it.'",
		"This code has more red flags than a Soviet parade. Again.",
		"You're not failing forward, you're falling backwards into progress.",
		"Your solution is the definition of 'technically possible, practically terrible.'",
		"This is what happens when you learn programming from memes.",
		"You've turned elegance into elephant. Big, clumsy, and hard to deal with.",
		"Your code is a perfect storm of poor choices.",
		"This isn't coding, it's controlled demolition. Except uncontrolled.",
		"You're writing code like you're being chased by deadlines and running from quality.",
		"Your solution is a masterpiece. Of disaster.",
		"This code will haunt the repository for generations.",
		"You've created something that works in theory. Wrong theory.",
		"Your approach is revolutionary. Revolving door of failure revolutionary.",
		"This is the code equivalent of a Rube Goldberg machine that doesn't work.",
		"You're not pushing the envelope, you're tearing it to shreds.",
		"Your solution is a surprise. A terrible surprise. Nobody wanted this surprise.",
		"This code is the reason we can't have production access.",
		"You've achieved the impossible: making simple things complicated and complicated things impossible.",
		"Your architecture is a cautionary tale in the making.",
		"This is what happens when you YOLO your way through development.",
		"You're not just missing the point, you're in a different dimension.",
		"Your code is a perfect example of 'it compiles ≠ it works.'",
		"This solution is held together by duct tape, hope, and violations of good taste.",
		"You've created a feedback loop of failure.",
		"Your approach to debugging is 'it's not a bug if I can't reproduce it.'",
		"This code is the before picture. There is no after picture. Nobody fixed it.",
		"You're not just reinventing the wheel, you're inventing a square one.",
		"Your solution is a proof of concept. It proves you have no concept.",
		"This is what happens when you treat warnings as suggestions.",
		"You've created a technical marvel. Marvelously broken.",
		"Your code is a time machine - it sends projects back to the stone age.",
		"This isn't scope creep, it's scope avalanche.",
		"You're writing code like it's a stream of consciousness. An unconscious stream.",
		"Your solution is innovative in all the wrong ways.",
		"This code is the gift that keeps on giving. Giving headaches.",
		"You've turned best practices into worst practices.",
		"Your approach is unique. Uniquely catastrophic.",
		"This is the code equivalent of 'hold my beer and watch me fail.'",
		"You're not just breaking things, you're shattering them into theoretical physics.",
		"Your solution is a monument to overengineering. Or under-thinking. Both.",
		"This code will be remembered. For all the wrong reasons.",
		"You've created a self-fulfilling prophecy of failure.",
		"Your architecture is more fractured than your understanding of it.",
		"This is what happens when you confuse activity with productivity.",
		"You're speed-running the 'developer to unemployed' pipeline.",
	},

	"savage_generic_4": {
		"Your code is a choose-your-own-adventure book where all paths lead to failure.",
		"This isn't just bad code, it's an archaeological site of bad decisions.",
		"You've created a blockchain of blame - fully distributed, transparent failure.",
		"Your solution is like a vegan steakhouse - fundamentally contradictory.",
		"This code is the reason Stack Overflow has a 'what not to do' section.",
		"You're not thinking outside the box, you've lost the box entirely.",
		"Your approach to software is 'move slow and break everything.'",
		"This is the code equivalent of autocorrect disasters.",
		"You've invented a new design pattern: the Anti-Pattern Pattern.",
		"Your solution is a riddle wrapped in an enigma wrapped in a disaster.",
		"This code is so bad, even PHP developers are judging you.",
		"You're not just missing the forest for the trees, you're in the wrong ecosystem.",
		"Your architecture is a Jenga tower during an earthquake.",
		"This is what happens when you treat documentation as fiction.",
		"You've created a perpetual motion machine of failure - it never stops breaking.",
		"Your code is a heist movie where you rob yourself.",
		"This solution is like a screen door on a submarine - conceptually flawed.",
		"You're writing code like it's a game of telephone - garbled and wrong.",
		"Your approach is 'fail fast' except you fail slow and comprehensively.",
		"This code is the reason we have imposter syndrome. Because sometimes we ARE imposters.",
		"You've turned simple logic into advanced chaos theory.",
		"Your solution is a Gordian knot. Except cutting it just makes more knots.",
		"This is what happens when you learn from YouTube tutorials and skip the prerequisites.",
		"You're not just moving the goalposts, you're in a different stadium.",
		"Your code is a mystery novel where the detective is also the murderer.",
		"This solution is a participation trophy for trying. And failing.",
		"You've created a dependency graph that looks like a spider on LSD drew it.",
		"Your approach to programming is 'quantity over quality.' Both are bad.",
		"This code is the software equivalent of a Ponzi scheme - it collapses under scrutiny.",
		"You're not just playing with fire, you're juggling flamethrowers blindfolded.",
		"Your solution is a house of cards built on quicksand during a hurricane.",
		"This is what happens when you confuse correlation with causation with compilation.",
		"You've created a feedback loop where failure breeds more failure.",
		"Your code is a masterclass in how to confuse future you.",
		"This solution is technically impressive. Impressively terrible.",
		"You're writing code like it's mad libs - random and nonsensical.",
		"Your architecture is a labyrinth with no exit and no cheese.",
		"This is the code they show new hires as a warning.",
		"You've turned debugging into an extreme sport.",
		"Your solution is a Swiss cheese of vulnerabilities and gaps.",
		"This code is proof that just because you can doesn't mean you should.",
		"You're not just in over your head, you're in a submarine with screen doors.",
		"Your approach is 'shoot first, aim never, ask questions while unemployed.'",
		"This is what happens when you treat errors as suggestions.",
		"You've created a Tower of Babel where all languages are broken.",
		"Your code is a tragedy in five acts. All happening simultaneously.",
		"This solution is like GPS directions to nowhere.",
		"You're writing code like it's abstract art. Nobody understands it, including you.",
		"Your architecture is more convoluted than tax law.",
		"This is the code equivalent of 'task failed catastrophically.'",
	},

	"savage_generic_5": {
		"Your code is a crime scene and you're the detective, suspect, and victim.",
		"This solution is like bringing a knife to a gunfight. Except the knife is a spoon.",
		"You've created a Murphy's Law simulator - everything that can go wrong, does.",
		"Your approach to programming is 'trial and error' without the learning part.",
		"This code is the reason version control was invented - to track your mistakes.",
		"You're not just burning bridges, you're nuking them from orbit.",
		"Your solution is a Trojan horse that attacks itself.",
		"This is what happens when you copy-paste from Stack Overflow without reading.",
		"You've turned software engineering into software guessing.",
		"Your code is a Renaissance painting of failure - complex, detailed, and in a museum of mistakes.",
		"This solution is like a chocolate teapot - sounds good, utterly useless.",
		"You're writing code like it's a game of Mad Gab - sounds similar, means nothing.",
		"Your architecture is a M.C. Escher drawing - impossible and nauseating.",
		"This is the code equivalent of 'instructions unclear, got X stuck in Y.'",
		"You've created a singularity of incompetence where all light of understanding is consumed.",
		"Your solution is a Schrödinger's cat - simultaneously working and broken until observed (spoiler: it's broken).",
		"This code is the butterfly that caused the hurricane of your career problems.",
		"You're not just missing the boat, you're on the wrong ocean.",
		"Your approach is 'fake it till you... keep faking it.'",
		"This solution is a testament to determination. Determined failure.",
		"You've created a perfect storm of poor architectural choices.",
		"Your code is a ouija board for bugs - they all appear when you run it.",
		"This is what happens when you treat best practices as best suggestions.",
		"You're writing code like it's a ransom note - threatening and incomprehensible. Again. It bears repeating.",
		"Your solution is a maze with no entrance, exit, or cheese. Just walls.",
		"This code will be studied by future generations. As a warning.",
		"You've turned elegant solutions into elegant disasters.",
		"Your architecture is a Picasso - abstract, confusing, and better when you don't look at it.",
		"This is the code equivalent of 'seemed like a good idea at the time.' It wasn't.",
		"You're not just reinventing the wheel, you're inventing a wheel that rolls uphill away from success.",
		"Your solution is a black hole of productivity - consumes everything, produces nothing.",
		"This code is the reason we have standup meetings. To stand up and walk away.",
		"You've created a cascade of failure that would make waterfall methodology jealous.",
		"Your approach to debugging is 'percussive maintenance' - hitting things until they work (they won't).",
		"This solution is like a palindrome - it's the same disaster forwards and backwards.",
		"You're writing code like it's a haiku - brief, confusing, and nobody gets it.",
		"Your architecture is a Russian nesting doll of bad decisions.",
		"This is what happens when you RTFM (Read The Wrong Manual).",
		"You've turned clean code into code that needs industrial cleaning.",
		"Your solution is a magic trick - now you see it work, now it's gone.",
		"This code is the reason we have trust issues with AI. It learned from this.",
		"You're not just on a slippery slope, you're skiing down a cliff.",
		"Your approach is 'move fast and break things.' You achieved the second part.",
		"This solution is like a plot hole in a movie - glaringly obvious and ruins everything.",
		"You've created a snowball effect of bugs rolling into an avalanche.",
		"Your code is a riddle that even the Sphinx gave up on.",
		"This is what happens when you treat programming languages as Mad Libs.",
		"You're writing code like it's a game of broken telephone crossed with a fever dream.",
		"Your architecture is more complex than your excuses for why it doesn't work.",
		"This solution is the 'before' picture in every success story. There is no 'after.'",
	},

	"savage_generic_6": {
		"Your code is an onion - many layers, all making people cry.",
		"This solution is like a boomerang that never comes back. Good riddance.",
		"You've created a philosophical question: 'If code breaks and nobody uses it, is it still terrible?' Yes.",
		"Your approach to programming is 'throw spaghetti at the wall and see what sticks.' Nothing stuck.",
		"This code is a greatest hits album of mistakes.",
		"You're not just in the weeds, you've grown your own forest of confusion.",
		"Your solution is a Venn diagram of things that shouldn't overlap, all overlapping.",
		"This is what happens when you treat compiler warnings like spam email.",
		"You've turned simple if/else into existential crisis.",
		"Your code is a museum exhibit: 'Early 21st Century Incompetence, circa 2025.'",
		"This solution is like a map with no scale, no legend, and wrong directions.",
		"You're writing code like it's improv comedy. Not funny, just uncomfortable.",
		"Your architecture is a Jackson Pollock painting - chaotic splatter with no discernible structure.",
		"This is the code equivalent of 'close enough' when close enough is nowhere near enough.",
		"You've created a cascade effect where one failure triggers all the others.",
		"Your solution is a paradox - it shouldn't exist, yet here we are.",
		"This code is the reason rubber duck debugging was invented. The duck quit.",
		"You're not just missing the target, you're shooting in the wrong direction.",
		"Your approach is 'shoot for the moon, land in a dumpster.'",
		"This solution is a symphony of errors conducted by incompetence.",
		"You've turned programming into a spectator sport. Spectators are horrified.",
		"Your code is a time capsule of bad decisions.",
		"This is what happens when you learn to code from error messages alone.",
		"You're writing code like it's a game of Jenga where every piece is critical and all of them fall.",
		"Your architecture is a house built on sand during high tide.",
		"This solution is like a bicycle with square wheels - technically a bicycle, practically useless.",
		"You've created a domino effect of failure. All dominoes fell. None were supposed to.",
		"Your code is a plot twist nobody wanted - unexpected and disappointing.",
		"This is the reason we invented 'delete' buttons.",
		"You're not just barking up the wrong tree, you're in the wrong forest on the wrong planet.",
		"Your solution is a riddle wrapped in bad code wrapped in worse decisions.",
		"This code will live in infamy.",
		"You've turned version 1.0 into version 0.1. Backwards progress.",
		"Your approach to software is 'move slowly and break everything anyway.'",
		"This solution is like a jigsaw puzzle where none of the pieces fit and some are from different puzzles.",
		"You're writing code like it's a rough draft. Except rough drafts are better.",
		"Your architecture is a Frankenstein's monster of frameworks stitched together.",
		"This is what happens when you confuse 'working' with 'compiling.'",
		"You've created a black box system. Even you don't know what's inside. Hint: failure.",
		"Your code is a masterpiece in the genre of 'what were they thinking?'",
		"This solution is technically a solution in the same way burning down the house solves an ant problem.",
		"You're not just off the rails, you've left the station, the tracks, and the concept of transportation.",
		"Your approach is 'quantity over quality' and you're failing at both.",
		"This is the code they use in 'before and after' transformation stories. It's the 'before.'",
		"You've turned edge cases into the main event.",
		"Your solution is a Murphy's Law demonstration project.",
		"This code is why we have impostor syndrome. Sometimes the impostor is real.",
		"You're writing code like it's a collaborative fiction project where everyone writes the worst ending.",
		"Your architecture is more convoluted than a conspiracy theory.",
		"This is the solution equivalent of 'technically correct is the worst kind of correct.' Except it's not even technically correct.",
	},

	// ==================== EVEN MORE SAVAGE INSULTS (300+ more!) ====================

	"brutal_truth": {
		"The truth is, your code is bad and you should feel bad.",
		"Nobody wants to work with your code. This includes future you.",
		"Your code is the reason we have code reviews. To prevent this.",
		"If honesty is the best policy, honestly, you should reconsider your career.",
		"Your contribution to this project is making it worse.",
		"The best thing about your code is the delete button.",
		"You're not learning from your mistakes because you don't recognize them as mistakes.",
		"Your confidence is inversely proportional to your competence.",
		"Every time you commit, an angel loses its wings.",
		"Your code is a liability, not an asset.",
		"The team would be more productive if you did literally nothing.",
		"Your debugging makes things worse. Stop helping.",
		"You've been doing this for years and somehow getting worse.",
		"Your code comments lie better than you do.",
		"You're the reason we can't have nice things or nice codebases.",
		"Your commits are like Russian roulette, except all chambers are loaded.",
		"If ignorance is bliss, you must be ecstatic about your code.",
		"Your code quality is a rounding error away from zero.",
		"You're not junior anymore, you're just bad.",
		"Your legacy will be the code that had to be rewritten.",
		"The only thing you optimize is disappointment.",
		"You treat best practices like they're best suggestions. They're not.",
		"Your architecture decisions are case studies in what not to do.",
		"You're proof that experience doesn't equal expertise.",
		"Your code reviews consist of 'approved' and regret.",
		"You write code like you're allergic to quality.",
		"The gap between your self-assessment and reality is astronomical.",
		"Your solutions create more problems than they solve.",
		"You're the weakest link. Goodbye.",
		"Your code is the 'before' picture in every improvement story.",
		"You've mastered the art of looking busy while being useless.",
		"Your technical debt accrues faster than student loans.",
		"You're not thinking outside the box, you've lost the box and all sense of direction.",
		"Your code is a warning label come to life.",
		"You make simple things complicated and complicated things impossible.",
		"The only thing agile about your development is how quickly it falls apart.",
		"You're reinventing the wheel into a square.",
		"Your problem-solving creates problems that need solving.",
		"You code like documentation is optional. It shows.",
		"Your git history is a horror anthology.",
		"You're not refactoring, you're just moving the mess around.",
		"Your tests test nothing except patience.",
		"You've weaponized incompetence into deployable software.",
		"Your expertise is in creating job security for your replacement.",
		"You're the reason we have 'are you sure?' confirmation dialogs.",
		"Your code is a monument to wasted time and resources.",
		"You treat warnings as decorations, not warnings.",
		"Your approach to software is 'hope as a strategy.'",
		"You're not having a bad day, you're having a bad career.",
		"The best code review for your work is 'git reset --hard.'",
	},

	"workflow_disasters": {
		"Your workflow is more broken than your code, and that's saying something.",
		"CI/CD? You have CI (Continuous Incompetence) / DD (Definitely Broken).",
		"Your pipeline has more leaks than the Titanic.",
		"Your deployment strategy is 'YOLO' and it shows.",
		"You treat production like a testing environment. Users disagree.",
		"Your workflow is so manual, it belongs in a museum.",
		"Automation? You're automating failure.",
		"Your release process is held together by hope and duct tape.",
		"You deploy on Fridays. You monster.",
		"Your hotfix process is 'fix it live and pray.'",
		"You have a workflow. It's terrible.",
		"Your branching strategy is 'everything in main, always.'",
		"Code freeze? You're in a perpetual code meltdown.",
		"Your merge strategy is 'accept all changes and hope.'",
		"You version your software like 'final-final-v2-ACTUAL.'",
		"Your deployment checklist is a prayer.",
		"You do code reviews after deployment. Backwards genius.",
		"Your staging environment is 'let's see what happens in prod.'",
		"You treat rollbacks like myths. They're about to become reality.",
		"Your release notes are 'stuff changed, idk.'",
		"You have zero automated tests and infinite confidence.",
		"Your workflow documentation is 'ask Bob' and Bob quit.",
		"You deploy without approval because you know it would be denied.",
		"Your feature flags are stuck in the 'always on' position.",
		"You cherry-pick commits like you're picking cherries blindfolded.",
		"Your rebase strategy is 'panic and force push.'",
		"You treat peer review as optional. Quality agrees.",
		"Your standup updates are fiction novels.",
		"You estimate in 'optimistic hours' not 'actual hours.'",
		"Your sprint planning is sprint panicking.",
		"You commit directly to production. Brave and stupid.",
		"Your CI builds pass because you disabled the tests.",
		"You have deployment windows but ignore them.",
		"Your rollout strategy is 'big bang and bigger problems.'",
		"You do A/B testing: A is broken, B is also broken.",
		"Your canary deployment ate the canary.",
		"You version bump major for typo fixes.",
		"Your changelog is more fiction than documentation.",
		"You tag releases retroactively after they break.",
		"Your workflow has more steps than a ballroom dance, all wrong.",
		"You pair program but both of you are confused.",
		"Your code ownership is 'not it' from everyone.",
		"You have trunk-based development, emphasis on 'trunk' over 'development.'",
		"Your gitflow looks like git-overflow.",
		"You squash commits to hide your mistakes. We can still see them.",
		"Your merge queue is a graveyard of abandoned dreams.",
		"You have continuous deployment of continuous disasters.",
		"Your pipeline artifacts are just broken builds.",
		"You deploy from local because CI 'takes too long.'",
		"Your workflow is a cautionary tale in project management books.",
	},

	"dependency_hell": {
		"Your node_modules folder is larger than your actual code.",
		"847 dependencies to print 'Hello World.' Efficient.",
		"Your dependency tree looks like a horror movie family tree.",
		"You depend on packages that haven't been updated since 2014.",
		"Your lockfile has more conflicts than a soap opera.",
		"npm install takes longer than your college degree.",
		"You have dependencies with dependencies with dependencies. It's turtles all the way down.",
		"Your package.json is a cry for help.",
		"Semver? You depend on ^0.0.1 packages in production.",
		"Your dependencies have 500 critical vulnerabilities. You have 0 updates.",
		"You added a library to capitalize a string. One function. 50MB.",
		"Your bundler bundles in your incompetence.",
		"Circular dependencies? Your entire project is a circle of despair.",
		"You depend on left-pad. The original one. Still.",
		"Your transitive dependencies are more connected than LinkedIn.",
		"You have 5 different versions of the same library. All broken.",
		"Your vendor folder is larger than most databases.",
		"You copy-pasted a package into your repo to 'avoid dependencies.'",
		"Your requirements.txt requires divine intervention.",
		"You pin dependencies to 'latest.' Chaos is your friend.",
		"Your Cargo.lock is a war crime.",
		"You use * for all dependency versions. Living dangerously.",
		"Your go.mod has more replace directives than actual dependencies.",
		"You vendored dependencies and then modified them. Why.",
		"Your dependency resolution takes 45 minutes. Java's is faster.",
		"You have peer dependency conflicts before you even start.",
		"Your package manager gave up. So should you.",
		"You install global packages and wonder why nothing works.",
		"Your monorepo has 15 different versions of React. None compatible.",
		"You npm link in production. Bold strategy.",
		"Your workspace configuration is a workspace catastrophe.",
		"You have hoisting issues and they're not going away.",
		"Your lockfile drift is continental drift speed.",
		"You committed node_modules. All 2GB.",
		"Your dependency audit shows 'critical' in red. All of them.",
		"You override peer dependencies like you override good judgment.",
		"Your resolution strategy is 'hope it works.'",
		"You have phantom dependencies everywhere.",
		"Your build tool can't resolve half your imports.",
		"You use deprecated packages like they're vintage wine.",
		"Your dependency hell is a multilevel inferno.",
		"You have dev dependencies in production. Professional.",
		"Your optional dependencies are mandatory for anything to work.",
		"You use workspace: protocol and everything is broken.",
		"Your pnpm config is more complex than quantum mechanics.",
		"You have type definition conflicts for every package.",
		"Your bundler is bundling your mistakes efficiently.",
		"You have duplicate dependencies and duplicate problems.",
		"Your shrinkwrap doesn't shrink the problems.",
		"You rely on side effects in dependencies. Chaos engineering.",
	},

	"api_disasters": {
		"Your API design is a REST in peace.",
		"Your endpoints are so inconsistent, they have multiple personalities.",
		"You return 200 OK with error messages in the body. Creative.",
		"Your API versioning is 'break everything with each release.'",
		"You use POST for everything. GET doesn't exist in your world.",
		"Your response times are measured in geological epochs.",
		"You return HTML in a JSON API. Why.",
		"Your API documentation is 'read the source code.'",
		"You have /api/v1, /v2, /api/v2, /v3/api. Pick a pattern.",
		"Your rate limiting is 'unlimited until the server dies.'",
		"You return different schemas for the same endpoint. Surprise!",
		"Your pagination starts at 1 on page 0. Makes sense to nobody.",
		"You use semicolons in URLs. Semicolons!",
		"Your error messages are 'Error: error.' Very helpful.",
		"You return 500 for validation errors. Everything is a server error.",
		"Your API accepts anything and does nothing correctly.",
		"You use camelCase, snake_case, and kebab-case. Sometimes all at once.",
		"Your timestamps are strings without timezone. Chaos achieved.",
		"You don't use HTTPS. In 2025. Wow.",
		"Your CORS policy allows everything. Security? Never heard of it.",
		"You nest JSON 15 levels deep for a simple value.",
		"Your API returns null, 'null', and undefined randomly.",
		"You use query params for POST bodies. Backwards.",
		"Your sorting is broken for anything with special characters.",
		"You filter with GET body params. That's not how this works.",
		"Your search endpoint searches nothing useful.",
		"You return 404 for permission denied. Confusing by design.",
		"Your batch endpoints process one at a time. 'Batch.'",
		"You don't support partial updates. Full PUT or nothing.",
		"Your webhook retries retry infinitely. DDoS yourself.",
		"You use XML in 2025. Are you ok?",
		"Your GraphQL schema is deeply concerning and deeply nested.",
		"You expose internal IDs in URLs. Database schema leak speedrun.",
		"Your API versioning header is required but undocumented.",
		"You return entire database rows with all internal fields.",
		"Your cursor-based pagination cursors expire immediately.",
		"You rate limit per endpoint. 1000 endpoints, 1000 times the requests.",
		"Your idempotency keys aren't idempotent.",
		"You return 201 for failed creation. Optimistic.",
		"Your HATEOAS links link to nothing.",
		"You use cookies for API auth. Why.",
		"Your multipart form data handling is a disaster.",
		"You return different content types based on moon phase.",
		"Your API gateway is a gateway to disappointment.",
		"You version via query param: ?version=broken.",
		"Your OPTIONS requests return 404. CORS says no.",
		"You cache errors. Now everyone gets fast failures.",
		"Your webhook signatures don't verify. Security theater.",
		"You use JSON-RPC in REST endpoints. Pick one.",
		"Your API is so bad, Postman crashes trying to import it.",
	},

	"naming_things": {
		"Your variable names look like cat walked across the keyboard.",
		"'data' and 'data2' - the pinnacle of descriptive naming.",
		"Your function 'doStuff()' does stuff. Which stuff? All the stuff. Worst stuff.",
		"You name booleans 'flag1' through 'flag47.' Helpful.",
		"Your class 'Manager' manages nothing except confusion.",
		"temp, tmp, temp1, temporary, t - pick a naming convention challenge (failed).",
		"Your constant is named 'VARIABLE.' Ironic.",
		"You have MyClass, MyClass2, MyClassNew, MyClassFinal. Evolution of bad ideas.",
		"Your function 'handleData' handles no data correctly.",
		"You name everything 'util.' Utils utils utils.",
		"Your 'foo' and 'bar' made it to production. Really.",
		"DatabaseConnectionManagerFactoryBuilderImplProxy - you're a Java developer, aren't you?",
		"Your Hungarian notation is Hungarian gibberish.",
		"You abbreviate everything: usrMgrFctryBldr. Vowels are expensive apparently.",
		"Your snake_case_Variable_Names_Are_Inconsistent_EVERYWHERE.",
		"You name functions after what they should do, not what they actually do.",
		"get() that actually sets. set() that actually gets. Opposite day.",
		"Your 'helper' class helps nobody.",
		"You name your test file 'test.' Which test? All tests. No tests.",
		"async function sync() - the irony is lost on you.",
		"Your calculateTotal() calculates nothing and returns undefined.",
		"is_valid returns strings 'true' and 'false.' Booleans exist.",
		"You have MyComponent and MyComponentComponent. Redundant redundancy.",
		"Your processUserInputDataManagerFactoryImpl processes nothing but confusion.",
		"obj, obj1, obj2, newObj, objFinal, objActual - a naming disaster timeline.",
		"Your onClick handles form submission. Names mean nothing.",
		"getData() modifies data. getters shouldn't do that.",
		"Your constants CHANGE. They're not constant except in disappointment.",
		"IInterfaceInterface - the 'I' stands for 'I give up.'",
		"You name classes after design patterns. FactorySingletonObserverBridge. Why.",
		"Your result variable holds errors. Your error variable holds results.",
		"index, i, idx, ind, index1 - in the same function.",
		"Your doSomething() does everything and nothing all at once.",
		"AbstractSingletonProxyFactoryBean - Spring called, they want their naming back.",
		"You name promises 'callback.' You name callbacks 'promise.'",
		"Your 'new' variable is 6 years old in the codebase.",
		"You name files index.js in every folder. Good luck debugging.",
		"main1(), main2(), actualMain(), realMain() - which one runs?",
		"Your boolean is named 'status.' True/false status of what?",
		"You have utils, helpers, common, shared, lib - all doing the same nothing.",
		"processData, handleData, manageData, dataProcess, dataHandler - pick one challenge (impossible).",
		"Your function 'run' runs nothing. It walks. Slowly. Into failure.",
		"validateInput() that doesn't validate input.",
		"Your 'TODO' variable made it to production. Still TODO.",
		"You name files 'new_new_final_v2_ACTUAL.js' - version control exists.",
		"execute() that doesn't execute. prepare() that doesn't prepare.",
		"Your 'user' class handles database connections. Makes sense to nobody.",
		"You name your error class 'Success.' Optimism or confusion?",
		"Your singleton has multiple instances. Name doesn't match reality.",
		"component.component.ts in component/component directory. Component.",
	},

	"premature_optimization": {
		"You optimized the wrong thing. Now it's fast and wrong.",
		"Premature optimization is the root of all evil. You're the root.",
		"You spent 10 hours optimizing a function that runs once a year.",
		"Your micro-optimizations created macro-disasters.",
		"You optimized for speed. Now it's fast at being broken.",
		"Shaving 2ms off a 10-second function. Priorities.",
		"You cached everything. Including bugs.",
		"Your code is unreadable but 0.01% faster. Trade-off failed.",
		"You hand-rolled crypto for 'performance.' Please don't.",
		"Your bit-shifting obfuscation is impressive and completely unnecessary.",
		"You optimized memory and leaked it everywhere else.",
		"Your assembly inline is slower than the compiler output.",
		"You removed all error handling for 'speed.' Fast crashes.",
		"Your object pool is slower than garbage collection.",
		"You memoized a function that returns random values. Think.",
		"Your custom hash map is slower than the standard library.",
		"You unrolled loops that are called once.",
		"Your lock-free data structure has race conditions.",
		"You optimized the cold path and ignored the hot path.",
		"Your SIMD implementation is slower than scalar. Impressive failure.",
		"You removed bounds checking. Segfault speedrun any%.",
		"Your database stored procedure is slower than the ORM.",
		"You index every column. Queries are slower. Writes are glacial.",
		"Your compression algorithm is slower than network transfer.",
		"You cache-aligned structs nobody reads.",
		"Your prefetching prefetches into cache misses.",
		"You optimized CPU and killed the cache hit rate.",
		"Your async code is slower than synchronous. How.",
		"You removed abstraction for speed and created spaghetti.",
		"Your bit flags saved 3 bytes and cost 3 weeks of debugging.",
		"You optimized Big-O but the constants are huge.",
		"Your zero-copy implementation copies more than before.",
		"You memory-mapped a 5KB file.",
		"Your thread pool has 1000 threads for 2 tasks.",
		"You rewrote std::sort. It's slower. Use the standard library.",
		"Your branchless code has more branches than a tree.",
		"You SIMDed a loop that runs 4 times.",
		"Your JIT compilation takes longer than interpreted execution.",
		"You optimized for x86 and broke every other architecture.",
		"Your lookup table is larger than the computation it replaces.",
		"You traded readability for 'speed.' Both are gone now.",
		"Your const everything didn't make it faster.",
		"You inlined functions the compiler wouldn't inline for good reason.",
		"Your memory arena allocator fragments worse than malloc.",
		"You optimized tail call and the compiler doesn't support it.",
		"Your register hints made it slower. Compiler knows better.",
		"You removed virtual for 'speed' and broke polymorphism.",
		"Your template metaprogramming compiles for 20 minutes.",
		"You optimized for cache when the bottleneck was disk I/O.",
		"Your 'fast path' is the slow path in disguise.",
	},

	// ==================== MASSIVE EXPANSION ROUND 3: 600+ MORE BRUTAL INSULTS ====================
	// These are particularly savage and technically sophisticated

	"code_crimes": {
		// 50 insults about code that should be illegal
		"Your code violates the Geneva Convention on programmer rights.",
		"If code could be a war crime, yours would be tried at The Hague.",
		"Your commit is a felony in 47 states.",
		"You're wanted by Interpol for crimes against computer science.",
		"Your code is exhibit A in 'Crimes Against Humanity: Digital Edition.'",
		"You've committed first-degree murder. Of productivity.",
		"Your pull request is a confession to multiple coding felonies.",
		"Grand theft auto-complete: You steal from Stack Overflow badly.",
		"You're guilty of malicious intent. Intent to destroy code.",
		"Your code should be classified as a dangerous weapon.",
		"Breaking and entering. Breaking: builds. Entering: production.",
		"You commit fraud. Fraudulent commit messages daily.",
		"Identity theft: You claim to be a developer.",
		"Your code is racketeering: organized criminal activity.",
		"Money laundering: Laundering bad code into worse code.",
		"Embezzlement: Stealing company time to produce nothing.",
		"Tax evasion: Evading the tax of quality code.",
		"Perjury: Every standup you lie about progress.",
		"Obstruction of justice: Obstructing team progress.",
		"Contempt of court: Contempt for code review.",
		"Assault and battery: Assaulting codebases, battering logic.",
		"Arson: Setting production on fire regularly.",
		"Vandalism: Vandalizing clean code.",
		"Trespassing: Trespassing into senior developer territory.",
		"Burglary: Burglarizing competence from the team.",
		"Forgery: Forging fake understanding of concepts.",
		"Counterfeiting: Counterfeit developer credentials.",
		"Kidnapping: Holding codebases hostage with your bugs.",
		"Extortion: 'Deploy my code or I'll deploy it anyway.'",
		"Conspiracy: Conspiring with bugs to destroy production.",
		"Treason: Betraying the trust of your team daily.",
		"Espionage: Spying on good code to copy it wrong.",
		"Sabotage: Sabotaging the entire development process.",
		"Terrorism: Terrorizing teams with your deployments.",
		"Piracy: Pirating code you don't understand.",
		"Smuggling: Smuggling bugs into production.",
		"Trafficking: Trafficking in broken dependencies.",
		"Racketeering: Running a racket of incompetence.",
		"Your code is organized crime. Organized chaos.",
		"Statutory violations: Violating every best practice statute.",
		"Misdemeanors: Every commit is a misdemeanor.",
		"Felony: Your career is a felony in progress.",
		"Aggravated assault: Aggravating everyone with your code.",
		"Your bug reports are criminal confessions.",
		"You plead the fifth. Fifth time breaking production today.",
		"Miranda rights: You have the right to remain silent. Please do.",
		"Bail denied: You're too dangerous to release into production.",
		"Life sentence: Your code lives forever in infamy.",
		"Death penalty: Your code deserves execution. Immediate.",
		"You're on death row: Row 847 in your broken database.",
	},

	"ai_ml_disasters": {
		// 50 AI/ML specific insults
		"Your AI model has 0% accuracy. It's consistently wrong.",
		"Your neural network is neural nothing.",
		"Your training data trained nothing except disaster.",
		"Overfitting? Your model fits nothing, not even training data.",
		"Underfitting? Your understanding underfits basic concepts.",
		"Your loss function is your team's morale.",
		"Gradient descent? Your career is in gradient descent.",
		"Backpropagation: Propagating failures backwards through time.",
		"Your activation function: Deactivated.",
		"ReLU: Really Embarrassing Learning Underachiever.",
		"Your CNN can't see. Your RNN can't remember. Your LSTM forgot.",
		"Attention mechanism: Nobody's paying attention to your model.",
		"Transformer: Transform garbage in, garbage out.",
		"Your GPT: Garbage Producing Transformer.",
		"BERT: Badly Engineered, Rarely Tested.",
		"Your embeddings embed incompetence in vector space.",
		"Dimensionality reduction: Reducing your career dimensions to zero.",
		"Your feature engineering features no engineering.",
		"Hyperparameter tuning: Tuning the parameters of failure.",
		"Cross-validation: Cross with you for validating nothing.",
		"Train/test split: Split decision on whether you're incompetent. Verdict: Yes.",
		"Your confusion matrix confuses everyone. It shows 100% failure.",
		"Precision: 0%. Recall: Recalling why we hired you. Can't recall.",
		"F1 score: F for Failure.",
		"ROC curve: Your career trajectory. Area under curve: Negative.",
		"Your model bias: Biased toward failure.",
		"Variance: Variable incompetence. High variance.",
		"Ensemble methods: Ensemble of disasters.",
		"Boosting: Boosting your failure rate.",
		"Bagging: Bagging your employment.",
		"Random forest: Randomly failing in forest of mistakes.",
		"Decision tree: Decision is clear. You failed.",
		"Support Vector Machine: Machine doesn't support you.",
		"K-means clustering: Clustering K disasters. K approaches infinity.",
		"PCA: Principal Component of Failure.",
		"Your batch size is infinite. Your patience is finite.",
		"Learning rate: Rate of learning: 0.",
		"Epoch: Each epoch is an epoch of failure.",
		"Your dataset is biased. Toward showing you're incompetent.",
		"Augmentation: Augmenting disasters.",
		"Transfer learning: Transferring incompetence between domains.",
		"Fine-tuning: Finely tuned disaster.",
		"Zero-shot learning: Zero shots at success.",
		"Few-shot learning: Few shots all missed.",
		"Meta-learning: Meta-disaster learning.",
		"Your AI is artificial. Intelligence is absent.",
		"Machine learning: Machine learned to avoid you.",
		"Deep learning: Deep in the hole of incompetence.",
		"Your model converged. To failure.",
		"Early stopping: Should've stopped at career choice.",
		"Dropout: You should drop out of development.",
	},

	"frontend_nightmares": {
		// 50 frontend-specific brutal insults
		"Your CSS is Cascading Style Shit.",
		"Your HTML is HyperText Markup Lunacy.",
		"Your JavaScript is Just Awful Scripts.",
		"Your React components react to nothing correctly.",
		"Your Vue is a view of disaster.",
		"Your Angular is acutely terrible.",
		"Your Svelte is anything but svelte.",
		"Your Next.js is next-level terrible.",
		"Your Nuxt.js nukes performance.",
		"Your Gatsby is a great scare.",
		"Your Redux state is stated incompetence.",
		"Your component lifecycle died at birth.",
		"Your hooks hooked into disaster.",
		"useState: State: Perpetual failure.",
		"useEffect: Effect: Destroy everything.",
		"useContext: Context: You're incompetent.",
		"useReducer: Reduce your participation.",
		"useMemo: Memo: Don't hire.",
		"useCallback: Callback to reality. You failed.",
		"useRef: Reference: Disaster.",
		"Your Virtual DOM is virtually broken.",
		"Your shadow DOM casts shadow of incompetence.",
		"Your Web Components are web disasters.",
		"Your props drilling drills holes in logic.",
		"Your state management is state chaos.",
		"Your event handlers handle nothing.",
		"Your lifecycle methods live short, die young.",
		"Your render function renders disasters.",
		"Your JSX is JSON: eXtremely terrible.",
		"Your TypeScript types are typed wrong.",
		"Your interfaces interface with failure.",
		"Your generics are generically terrible.",
		"Your webpack config weighs a ton. Works: Never.",
		"Your babel config babbles incomprehensibly.",
		"Your polyfills fill nothing.",
		"Your CSS-in-JS is CSS-in-WTF.",
		"Your styled-components are styled disasters.",
		"Your Tailwind blows away competence.",
		"Your Bootstrap lifts nothing.",
		"Your flexbox is flexible in failure.",
		"Your grid layout is gridlocked in incompetence.",
		"Your media queries query why you code.",
		"Your animations animate disasters.",
		"Your transitions transition from bad to worse.",
		"Your accessibility is inaccessible.",
		"Your semantic HTML is semantically incorrect.",
		"Your SEO: Search Engine Obstruction.",
		"Your meta tags are meta-disasters.",
		"Your bundle size is elephantine. Your skill is microscopic.",
		"Your lazy loading lazily loads failures.",
		"Your code splitting splits competence from you.",
	},

	"backend_brutality": {
		// 50 backend-specific savage insults
		"Your server-side logic is server-side tragic.",
		"Your API endpoints end in disappointment.",
		"Your middleware is middling at best.",
		"Your routes route to nowhere productive.",
		"Your controllers control nothing except chaos.",
		"Your models model incompetence.",
		"Your views are bleak views.",
		"Your ORM maps Objects to Regrets Massively.",
		"Your queries question your competence.",
		"Your migrations migrate away from functionality.",
		"Your seeds seed disasters.",
		"Your factories manufacture failures.",
		"Your validators validate your incompetence.",
		"Your serializers serialize disasters.",
		"Your authentication can't authenticate competence.",
		"Your authorization: Unauthorized developer.",
		"Your JWT: Just Wrong Token.",
		"Your sessions expire. Your career should too.",
		"Your cookies crumble under scrutiny.",
		"Your CORS policy is cross-origin disaster.",
		"Your rate limiting limits nothing.",
		"Your caching caches crashes.",
		"Your Redis is rarely working.",
		"Your Memcached is memory-wasted.",
		"Your RabbitMQ: Rabbit hole of mistakes.",
		"Your Kafka produces streams of failure.",
		"Your gRPC is gRPC: greatly Ridiculous Protocol Catastrophe.",
		"Your GraphQL resolvers resolve nothing.",
		"Your REST API rests in failure.",
		"Your SOAP: Service-Oriented Awful Programming.",
		"Your microservices are micro-competent.",
		"Your monolith is monolithic disaster.",
		"Your serverless functions serve nothing.",
		"Your Lambda functions are Lambda disasters.",
		"Your containers contain catastrophes.",
		"Your Docker images image your incompetence.",
		"Your Kubernetes orchestrates chaos.",
		"Your pods are PODs: Perpetually Operating Disasters.",
		"Your deployments deploy doom.",
		"Your services serve disappointment.",
		"Your workers work at failing.",
		"Your queues queue disasters.",
		"Your jobs are jobs nobody wants.",
		"Your cron jobs are crime jobs.",
		"Your background tasks background your career.",
		"Your webhooks hook into failure.",
		"Your pub/sub publishes problems.",
		"Your event bus is an event catastrophe.",
		"Your message broker broke everything.",
		"Your load balancer can't balance your failures.",
		"Your reverse proxy reverses progress.",
	},

	"infrastructure_insults": {
		// 50 infrastructure and ops insults
		"Your infrastructure is infra-structure collapse.",
		"Your servers serve disasters.",
		"Your load balancers are overloaded with failure.",
		"Your firewall can't wall off your incompetence.",
		"Your VPN is Very Poor Network management.",
		"Your CDN: Content Delivery Never.",
		"Your DNS: Doesn't Navigate Sensibly.",
		"Your SSL certificate is certified disaster.",
		"Your proxy is approximate: approximately terrible.",
		"Your NAT is naturally awful.",
		"Your subnet is sub-competent.",
		"Your VLAN is virtually lacking.",
		"Your routing tables route to failure.",
		"Your switching logic switches off competence.",
		"Your bandwidth is band-narrow.",
		"Your latency is late to everything. Including competence.",
		"Your throughput puts through disasters.",
		"Your packet loss loses everything including hope.",
		"Your TCP handshake shakes with incompetence.",
		"Your UDP: Unreliably Delivered Programming.",
		"Your HTTP is HyperText Transfer Problems.",
		"Your HTTPS is HTTP Seriously broken.",
		"Your SSH: Secure Shell of incompetence.",
		"Your FTP: Failure Transfer Protocol.",
		"Your SFTP: Secure Failure Transfer.",
		"Your rsync is re-sync your career.",
		"Your cron schedule schedules disasters.",
		"Your systemd system died.",
		"Your init scripts initiate failure.",
		"Your daemon is demonic.",
		"Your process is in process of failing.",
		"Your thread is hanging by thread.",
		"Your fork forked up everything.",
		"Your pipe is piping disasters.",
		"Your socket is socketing into failure.",
		"Your port is ported to disaster.",
		"Your protocol is protocol of failure.",
		"Your stack is stacked with mistakes.",
		"Your layer is layered with incompetence.",
		"Your OSI model is OSI disaster.",
		"Your packet is packaged disaster.",
		"Your frame is framed for failure.",
		"Your byte is bitten by incompetence.",
		"Your bit is a bit terrible. Very terrible.",
		"Your kernel panic is your daily state.",
		"Your segfault is your signature.",
		"Your core dump dumps your career.",
		"Your memory leak leaks competence.",
		"Your buffer overflow overflows with mistakes.",
		"Your race condition races to failure.",
	},

	"agile_apocalypse": {
		// 50 agile/scrum specific insults
		"Your sprint is a sprint to unemployment.",
		"Your backlog is backed up with incompetence.",
		"Your user stories are user tragedies.",
		"Your acceptance criteria: Can't accept your code.",
		"Your definition of done: Never done right.",
		"Your velocity is velocity toward disaster.",
		"Your burndown chart burns down your career.",
		"Your standup is a fall down.",
		"Your retrospective is a perspective on failure.",
		"Your planning poker: You're bluffing. Everyone knows.",
		"Your story points point to incompetence.",
		"Your epic is an epic fail.",
		"Your feature is a future disaster.",
		"Your spike is spiking failure rates.",
		"Your tech debt is technical bankruptcy.",
		"Your MVP is Minimum Viable Programmer. Not viable.",
		"Your iteration iterates disasters.",
		"Your increment increments mistakes.",
		"Your release is releasing chaos.",
		"Your milestone is a millstone around the team.",
		"Your roadmap is a road to nowhere.",
		"Your timeline is a time bomb.",
		"Your deadline is your death line.",
		"Your estimate is estimated incompetence.",
		"Your commitment is committed to failure.",
		"Your capacity is capacity for disaster.",
		"Your WIP limit is Work In Progress: All disaster.",
		"Your kanban board is a can't-ban your incompetence board.",
		"Your scrum master scrums up everything.",
		"Your product owner owns product disasters.",
		"Your stakeholder holds stake in your failure.",
		"Your demo is demonstrating incompetence.",
		"Your showcase showcases disasters.",
		"Your review is reviewing disasters.",
		"Your refinement refines nothing.",
		"Your grooming grooms disasters.",
		"Your ceremony is ceremoniously terrible.",
		"Your artifact is artifact of failure.",
		"Your product backlog is product disaster log.",
		"Your sprint backlog is sprint disaster log.",
		"Your increment is incrementally terrible.",
		"Your shippable product is unshippable disaster.",
		"Your potentially releasable is potentially catastrophic.",
		"Your working software is working disaster.",
		"Your sustainable pace: Sustainably failing.",
		"Your self-organizing team: Organizing your exit.",
		"Your cross-functional: Cross with your dysfunction.",
		"Your empirical process: Empirically terrible.",
		"Your transparency: Transparently incompetent.",
		"Your inspection inspects your failures.",
		"Your adaptation: Can't adapt to competence.",
	},

	"communication_catastrophes": {
		// 50 communication and soft skill insults
		"Your technical writing is technically illiterate.",
		"Your documentation documents disasters.",
		"Your comments comment on your incompetence.",
		"Your README is read-me: you're terrible.",
		"Your changelog changes nothing except morale.",
		"Your pull request description describes disasters.",
		"Your commit message messages incompetence.",
		"Your bug report reports your existence.",
		"Your ticket is ticketing your exit.",
		"Your email is emailing your failures.",
		"Your Slack message slacks off competence.",
		"Your presentation presents disasters.",
		"Your demo demonstrates incompetence.",
		"Your explanation explains nothing.",
		"Your documentation is undocumented chaos.",
		"Your wiki is wiki-weakly documented.",
		"Your confluence is confused influence.",
		"Your JIRA is just incompetence recorded accurately.",
		"Your standup update updates disasters.",
		"Your retrospective comment comments on your failures.",
		"Your code review comment comments on obvious disasters.",
		"Your PR description describes nothing useful.",
		"Your meeting notes note your incompetence.",
		"Your action items act on disasters.",
		"Your follow-up follows up on failures.",
		"Your status update: Status: Failing.",
		"Your progress report reports no progress.",
		"Your weekly update weekly updates disasters.",
		"Your quarterly review reviews your failures quarterly.",
		"Your annual review annually reviews consistent failure.",
		"Your performance review performs review of disasters.",
		"Your self-assessment assesses yourself incorrectly. You're worse.",
		"Your peer review: Peers reviewed: You failed.",
		"Your 360 review: 360 degrees of failure.",
		"Your feedback is feeding back disasters.",
		"Your one-on-one is one-to-one with HR.",
		"Your skip-level is skip-you-level.",
		"Your town hall halls your failures.",
		"Your all-hands is all-hands to block you.",
		"Your team meeting meets to discuss your removal.",
		"Your brainstorming storms incompetence.",
		"Your whiteboard session boards up your career.",
		"Your architecture review reviews your architecture: Terrible.",
		"Your design doc designs disasters.",
		"Your RFC: Request For Competence. Denied.",
		"Your proposal proposes nothing workable.",
		"Your recommendation recommends your exit.",
		"Your suggestion suggests you leave.",
		"Your advice advises against taking your advice.",
		"Your mentoring mentors in failure techniques.",
		"Your teaching teaches what not to do.",
	},

	"tooling_terrors": {
		// 50 development tools and IDE insults
		"Your IDE is Integrated Disaster Environment.",
		"Your VSCode is Very Sad Code.",
		"Your IntelliJ isn't intelligent.",
		"Your vim is victim of your incompetence.",
		"Your emacs is emasculating your code.",
		"Your Sublime Text is sub-lime competence.",
		"Your Atom atomized productivity.",
		"Your Eclipse eclipsed competence.",
		"Your NetBeans nets zero value.",
		"Your Xcode is ex-code after you touch it.",
		"Your PyCharm is pie-charmed disaster.",
		"Your WebStorm is web-storming disasters.",
		"Your PhpStorm is PHP-storming failures.",
		"Your RubyMine is ruby-mining disasters.",
		"Your GoLand is go-landing in failure.",
		"Your Rider is riding to disaster.",
		"Your CLion is client of incompetence.",
		"Your DataGrip grips no data correctly.",
		"Your terminal is terminating competence.",
		"Your shell is shell of a developer.",
		"Your bash is bashing productivity.",
		"Your zsh is zero skills here.",
		"Your fish is fishing for competence. Catches nothing.",
		"Your PowerShell powers failures.",
		"Your CMD commands disasters.",
		"Your tmux is too much incompetence.",
		"Your screen screens your incompetence. Badly.",
		"Your git client is guilty of enabling you.",
		"Your diff tool diffs competence from you.",
		"Your merge tool merges disasters.",
		"Your debugger debugs nothing. Bugs everywhere.",
		"Your profiler profiles your incompetence.",
		"Your linter lints at your failures.",
		"Your formatter can't format this mess.",
		"Your compiler compiles complaints about your code.",
		"Your interpreter interprets your incompetence.",
		"Your transpiler trans-piles disasters.",
		"Your bundler bundles disasters efficiently.",
		"Your minifier minifies your competence to zero.",
		"Your obfuscator obfuscates nothing except your intent.",
		"Your package manager packages disasters.",
		"Your build tool builds regrets.",
		"Your task runner runs from your code.",
		"Your test runner runs into failures.",
		"Your coverage tool covers your incompetence.",
		"Your CI server serves continuous incompetence.",
		"Your deployment tool deploys disasters.",
		"Your monitoring tool monitors your failures.",
		"Your logging tool logs your mistakes. Storage: Full.",
		"Your analytics analyze your incompetence.",
		"Your dashboard boards up your career.",
	},

	"language_lashings": {
		// 50 programming language choice insults
		"You chose PHP. First mistake of many.",
		"You chose JavaScript. Weakly typed, weakly skilled.",
		"You chose Java. Verbose code, verbose failures.",
		"You chose Python. Indentation errors match your career.",
		"You chose C++. Segfaults in code and career.",
		"You chose C. Memory leaks, competence leaks.",
		"You chose Go. Goroutines of failure.",
		"You chose Rust. Borrow checker rejects your logic.",
		"You chose Ruby. Gems of failure.",
		"You chose Swift. Swiftly failing.",
		"You chose Kotlin. Null safety. Null competence.",
		"You chose Scala. Scalable disasters.",
		"You chose Haskell. Purely functional at failing.",
		"You chose Erlang. Error handling everything including you.",
		"You chose Elixir. Elixir of incompetence.",
		"You chose Clojure. Parentheses (of (disaster)).",
		"You chose F#. F sharp, you flat.",
		"You chose OCaml. O-camel through the needle: You can't.",
		"You chose Perl. Perl of wisdom: Quit.",
		"You chose Lua. Lua-ser.",
		"You chose R. R for Regret.",
		"You chose MATLAB. Matrix of mistakes.",
		"You chose Fortran. Formula translation: Incompetence.",
		"You chose COBOL. Common Business-Oriented Language: Commonly terrible.",
		"You chose Assembly. Assembling disasters.",
		"You chose BASIC. Basically incompetent.",
		"You chose Pascal. Pass-call to unemployment.",
		"You chose Ada. Ada-mantly terrible.",
		"You chose Dart. Darting toward failure.",
		"You chose TypeScript. Types can't type-cast incompetence away.",
		"You chose Groovy. Groovy at grooving disasters.",
		"You chose Objective-C. Objectively terrible.",
		"You chose VB.NET. Visual Basic: Visually broken.",
		"You chose C#. C-sharp, code dull.",
		"You chose Zig. Zig-zagging to failure.",
		"You chose Nim. Nimble at disaster.",
		"You chose Crystal. Crystal clear incompetence.",
		"You chose Julia. July-august-september of failure.",
		"You chose Scheme. Scheming disasters.",
		"You chose Racket. Racket-eering incompetence.",
		"You chose Bash. Bashing productivity again.",
		"You chose PowerShell. Powering disasters.",
		"You chose Lisp. List processing: [disaster, failure, incompetence].",
		"You chose Prolog. Pro-log of failures.",
		"You chose Smalltalk. Small-talk, smaller competence.",
		"You chose APL. A Programming Language: Actually Poor Logic.",
		"You chose Forth. Fourth choice was better.",
		"You chose J. J for Joke of a language choice.",
		"You chose Brainfuck. Appropriate choice.",
		"You chose Malbolge. Also appropriate.",
		"Your language choice is the least of your problems.",
	},

	"system_design_sins": {
		// 50 system design and architecture insults
		"Your system design is systematically terrible.",
		"Your architecture is architectural disaster.",
		"Your high-level design is high-level incompetence.",
		"Your low-level design is low-level logic.",
		"Your component diagram diagrams disasters.",
		"Your sequence diagram sequences failures.",
		"Your class diagram classes you as incompetent.",
		"Your ER diagram ERrors in design.",
		"Your flow chart flows to failure.",
		"Your state diagram states incompetence.",
		"Your deployment diagram deploys disasters.",
		"Your network diagram networks nothing.",
		"Your topology is top-ologically terrible.",
		"Your layers are layered with mistakes.",
		"Your tiers are tears from teammates.",
		"Your separation of concerns: Can't separate disasters.",
		"Your coupling is tightly coupled to failure.",
		"Your cohesion is cohesively terrible.",
		"Your modularity modulates disasters.",
		"Your reusability: Reusable mistakes.",
		"Your maintainability: Can't maintain this.",
		"Your scalability scales disasters.",
		"Your availability is available failure.",
		"Your reliability reliably fails.",
		"Your fault tolerance tolerates your faults. Shouldn't.",
		"Your redundancy is redundantly terrible.",
		"Your load balancing balances toward failure.",
		"Your caching caches mistakes.",
		"Your sharding shards logic.",
		"Your partitioning partitions competence from you.",
		"Your replication replicates disasters.",
		"Your consistency is consistently terrible.",
		"Your availability is availability of disasters.",
		"Your partition tolerance tolerates your incompetence.",
		"Your CAP theorem: Choose All Problems.",
		"Your BASE: Basically Available, Sometimes Effective, Eventually terrible.",
		"Your ACID: All Code Is Defective.",
		"Your idempotency is idempotently broken.",
		"Your atomicity atomically fails.",
		"Your isolation isolates competence from you.",
		"Your durability: Durable disasters.",
		"Your transaction transacts failures.",
		"Your two-phase commit: Phase 1: Fail. Phase 2: Also fail.",
		"Your consensus algorithm: Consensus you're incompetent.",
		"Your leader election: Nobody votes for you.",
		"Your distributed lock locks out competence.",
		"Your service discovery discovers disasters.",
		"Your circuit breaker breaks everything.",
		"Your bulkhead pattern: Bulkheads breached.",
		"Your saga pattern: Saga of incompetence.",
		"Your event sourcing sources disasters.",
	},

	"career_epitaphs": {
		// 50 career-ending final insults
		"Here lies a developer. Code: Buried. Career: Also buried.",
		"RIP: Rest In Production. Your code broke it.",
		"Epitaph: 'I committed to main.' Fitting.",
		"Tombstone: 'Git blame points here.' Forever.",
		"Memorial: 'Compiled once. Crashed forever.'",
		"Eulogy: 'They shipped bugs. Bugs shipped them.'",
		"Gravestone: 'Force pushed to main. Pushed out of career.'",
		"Obituary: 'Died as they coded. Poorly.'",
		"In memoriam: 'Deployed on Friday. Unemployed by Monday.'",
		"Headstone: 'Their code lives on. Unfortunately.'",
		"Epitaph: 'Merged without review. Merged with unemployment.'",
		"Rest in peace: 'Piece of code broke everything.'",
		"Final commit: 'fix: career'",
		"Last words: 'It works on my machine.'",
		"Famous last deploy: 'YOLO to production.'",
		"Career summary: 'Exception: LifeExpectancyException.'",
		"Final PR: 'Closed: by life.'",
		"Last standup: 'Stood up. Fell down. Stayed down.'",
		"Final retrospective: 'In retrospect: Bad idea.'",
		"Closing issue: 'Closed as: Won't fix developer.'",
		"Exit interview: 'Why are you leaving?' 'I'm not. You're firing me.'",
		"Performance review: 'Performance: N/A. Review: Termination.'",
		"Final day: 'Badge access: Denied. Career access: Also denied.'",
		"Severance: 'Severed from competence long ago.'",
		"Termination date: 'Terminated like their buggy code.'",
		"Notice: 'Two weeks notice. Team rejoices for two weeks.'",
		"Resignation: 'I resign to my fate of unemployment.'",
		"Fired: 'Fire-wall couldn't protect them.'",
		"Laid off: 'Laid off like their commented-out code.'",
		"Let go: 'Let go. Team holds on to sanity.'",
		"Career expired: 'Expiration date: Today. Freshness: Never.'",
		"Professional death: 'Cause of death: Terminal incompetence.'",
		"Code legacy: 'Legacy: Technical debt.'",
		"Final words: 'But it passed linting!'",
		"Last commit message: 'WIP' - was in progress, now in regress.",
		"Farewell: 'Fare thee well. Fare thee far from here.'",
		"Goodbye: 'Good. Bye.'",
		"So long: 'So long it should've been sooner.'",
		"Adios: 'Adios means goodbye. Finally.'",
		"Au revoir: 'Au revoir. Don't revoir.'",
		"Sayonara: 'Say-onara to this career.'",
		"Ciao: 'Ciao down to reality check.'",
		"Cheerio: 'Cheerio-ously time to go.'",
		"Toodles: 'Toodles to your tenure.'",
		"Peace out: 'Peace out. Pieces of broken code remain.'",
		"Later: 'Later means never. Perfect.'",
		"See you: 'See you never.'",
		"Take care: 'Take care. Of finding new employment.'",
		"Best wishes: 'Best wishes: That you find a new career.'",
		"Good luck: 'Good luck. You'll need it. Lots.'",
	},
}
