package llm

// SavageInsultDatabase contains brutal, devastating insults
// These are the nuclear option - maximum savagery
var SavageInsultDatabase = map[string][]string{
	"ego_destruction": {
		"Your code is the coding equivalent of a participation trophy. Except nobody participated.",
		"If incompetence was an Olympic sport, you'd finish fourth.",
		"Your commit history reads like a tragedy written by someone who doesn't understand tragedy.",
		"You're not a 10x engineer. You're a 0.1x engineer. Generous estimate.",
		"Other developers use your code as an example of what not to do.",
		"Your GitHub contributions graph looks like a flatline. Appropriate.",
		"You bring new meaning to 'technical debt'. The debt is your entire career.",
		"Every line of code you write is a war crime against computer science.",
		"Your pull requests require a hazmat suit to review.",
		"You make junior developers feel like seniors by comparison.",
		"If coding were baseball, you'd strike out during warmups.",
		"Your resume says 'expert'. Your code says 'help wanted'.",
		"You're the reason Stack Overflow has a rate limit.",
		"Your code quality is directly correlated with your self-awareness: Non-existent.",
		"Other developers have a rubber duck. You need a rubber therapist.",
		"Your code reviews consist entirely of 'what were you thinking?'",
		"You're living proof that anyone can learn to code. Not well, but technically.",
		"Your programming skills peaked at 'Hello World'. It's been downhill since.",
		"You write code like a toddler plays piano. Lots of noise, zero skill.",
		"Your debugging strategy is 'random changes until it works'. Spoiler: It doesn't work.",
		"You're the 'before' picture in coding bootcamp advertisements.",
		"Your code has more red flags than a Soviet parade.",
		"If code smell was literal, your workspace would be quarantined.",
		"You're why companies have code review processes.",
		"Your variable names are more confusing than your logic. That's impressive.",
		"You treat best practices like suggestions. Bad suggestions you ignore.",
		"Your code is a crime scene. You are the perpetrator.",
		"You're single-handedly keeping technical debt collection agencies in business.",
		"Your commits are like lottery tickets. Except you never win.",
		"You're the developer equivalent of a bull in a china shop. Except the bull is blindfolded.",
		"Your code complexity rivals your ability to overcomplicate simple tasks.",
		"You've achieved something remarkable: Making everyone else look competent.",
		"Your coding philosophy: Move fast and break everything. Mission accomplished.",
		"You're why 'it works on my machine' is a meme, not a solution.",
		"Your pull requests are tagged 'DO NOT MERGE'. Ever.",
		"You write bugs faster than you fix them. Impressive negative productivity.",
		"Your code is the 'hold my beer' of software engineering.",
		"You're proof that typing speed doesn't correlate with code quality.",
		"Your GitHub stars: 0. Your GitHub scars: Infinite.",
		"You make merge conflicts look intentional.",
	},

	"career_advice": {
		"Have you considered a career where failure is the goal? Like professional crash test dummy?",
		"LinkedIn is free. Monster.com is waiting. Your IDE should be closed.",
		"Your resume says 'Full Stack Developer'. Full stack of failures, maybe.",
		"They say everyone starts somewhere. You should've stayed there.",
		"Career pivot time: Professional keyboard warmer. You're already qualified.",
		"Your skill set is perfect for a career in 'former developer'.",
		"Indeed.com has listings. Indeed, you need one.",
		"Have you thought about technical writing? You can document your failures.",
		"QA testing might suit you. You're excellent at finding bugs. By creating them.",
		"Project management: Where you can blame others for your failures.",
		"DevRel: Developer relations can't be worse than your developer skills.",
		"Consider teaching. Those who can't do, teach. Those who can't teach, teach gym. You: Can't teach.",
		"Product management: No coding required. Perfect.",
		"Sales engineering: Sell dreams, not code. Your code can't be sold anyway.",
		"Scrum master: Stand up, speak up, mess up. Two out of three ain't bad.",
		"Your 'years of experience' should be measured in dog years. Less impressive.",
		"Retirement looks good on you. Early retirement. Immediate retirement.",
		"Freelancing: Where you can disappoint clients independently.",
		"Consulting: Get paid to give bad advice instead of bad code.",
		"Bootcamp instructor: Teaching others your mistakes. Recursively.",
		"Technical recruiter: You can't code, but you can find people who can.",
		"Your next role: Professional code reviewer. Everything gets rejected.",
		"Switch to hardware. At least when you break it, it's tangible.",
		"Data entry: Fewer opportunities for catastrophic failure.",
		"Customer support: Answer questions about code you didn't write.",
		"System administrator: Turn it off and on again. Your current skill level.",
		"Network engineer: Your networking skills exceed your coding skills. Both are terrible.",
		"Database administrator: At least databases have ROLLBACK.",
		"DevOps: Automate the disasters you currently create manually.",
		"Security engineer: If anyone can break it, you can.",
		"Your career trajectory: Parabolic. Currently descending.",
		"Consider agriculture. Plants don't throw exceptions.",
		"Fisherman: Cast nets, not bugs.",
		"Baker: You already know how to create spaghetti.",
		"Librarian: Organize books. Organizing code is beyond you.",
		"Accountant: Balance books instead of breaking builds.",
		"Barista: Serve coffee. Serve the team by leaving.",
		"Uber driver: Navigate roads instead of ruining code paths.",
		"Dog walker: They say dogs can sense bad people. Consider cats.",
		"Professional sleeper: You're already doing it during standups.",
	},

	"team_impact": {
		"Your pull request has 47 comments. 46 are 'please no'.",
		"The team retrospective has a dedicated section titled 'Never again'.",
		"Your standups require a trigger warning.",
		"HR added 'Survived working with [you]' to employee benefits.",
		"Your code reviews take longer than writing new code from scratch.",
		"The team velocity chart has a you-shaped crater.",
		"Your commits trigger automatic team therapy sessions.",
		"Team morale inversely correlates with your commit frequency.",
		"Your name in the git blame is a warning label.",
		"The team has a secret Slack channel called #damage-control.",
		"Your vacation days boost team productivity by 200%.",
		"Onboarding includes a section: 'How to work around [your] code'.",
		"Your PRs require hazmat certification to review.",
		"The team created a drinking game: Take a shot every bug. Everyone has alcohol poisoning.",
		"Your name on the commit triggers automated rollback procedures.",
		"Team leads use your code in 'scared straight' programs for juniors.",
		"Your pair programming sessions are classified as cruel and unusual punishment.",
		"The team wiki has a page: 'Coping with [your] code'.",
		"Your merge to main triggers pager duty. For everyone.",
		"Teammates fake sick days when you push to shared branches.",
		"The team unanimously voted for your code to be quarantined.",
		"Your contributions decrease the team's Lighthouse score. And morale.",
		"Standup time allocated: 15 minutes. Your explanation of failures: 45 minutes.",
		"The team sprint velocity measures progress. Except when you commit.",
		"Your name in code review comments is always in ALL CAPS.",
		"Team building exercises now include 'How to say no to [your] PRs'.",
		"Your code is discussed in team meetings. As a cautionary tale.",
		"Team happiness metrics have a you-shaped anomaly. Negative anomaly.",
		"Your contributions are measured in inverse productivity points.",
		"The team has insurance. Against your code.",
		"Your name appears in the incident reports more than in the code.",
		"Team members list 'Survived [your] sprint' on their resumes.",
		"Your commits require team-wide approval. Unanimous. Good luck.",
		"The team created a bot to auto-reject your PRs.",
		"Your merge conflicts are team-building exercises. In frustration.",
		"Team retrospectives start with 'What did [you] break this week?'",
		"Your code requires a team-wide code freeze to deploy.",
		"The team has a running joke: 'Works on [your] machine. Nowhere else.'",
		"Your contributions are the reason the team has a rollback speedrun record.",
		"Team members draw straws to see who reviews your code. Loser quits.",
	},

	"existential": {
		"In the grand scheme of the universe, you are insignificant. In the grand scheme of this codebase, you are catastrophic.",
		"Sisyphus pushed a boulder uphill for eternity. You push bugs to production.",
		"The void stares back. The void is more competent.",
		"If a tree falls in the forest and no one hears it, it still has more impact than your code.",
		"You're a cautionary tale for ambitious AI alignment. Even AI wouldn't want to code like you.",
		"In another universe, you're a great developer. This is not that universe.",
		"Philosophers debate the meaning of existence. Your code proves meaninglessness.",
		"You're the proof that infinite monkeys at infinite typewriters would eventually produce Shakespeare. You're one monkey. With one typewriter. Not producing Shakespeare.",
		"The universe is indifferent to your suffering. Your code makes it actively hostile.",
		"Your existence poses fundamental questions. Like 'why?'",
		"In the grand tapestry of human achievement, you are a loose thread.",
		"Your code is a philosophical statement: Nihilism in C++.",
		"The examined life is worth living. Your code is worth deleting.",
		"You're the butterfly effect in reverse. Small actions, zero consequences.",
		"In the marketplace of ideas, your code is bankrupt.",
		"Your contribution to humanity's legacy: A warning to future generations.",
		"The unexamined code is not worth deploying. The examined code: Also not worth deploying.",
		"You're proof that consciousness doesn't guarantee competence.",
		"Your code raises deep questions: 'Why?' 'How?' 'Please stop?'",
		"In Plato's cave, the shadows on the wall are more enlightening than your code.",
		"You're the trolley problem: Do you let your code run or do you save everyone?",
		"Descarte said 'I think, therefore I am'. Your code says 'I compile, therefore I crash'.",
		"Your code is the ship of Theseus: Replace every part and it still doesn't work.",
		"You're living proof of the problem of induction: Past failures predict future failures.",
		"Your code is Schrodinger's cat: Both alive and dead until observed. Then definitely dead.",
		"In the great cosmic dance, you've stepped on everyone's toes.",
		"Your code is an ontological argument for the non-existence of quality.",
		"You're the heat death of the universe, but localized to this repository.",
		"Your code proves Russell's paradox: It contains itself, and that's a contradiction.",
		"You're the prisoner's dilemma: Cooperate with you and everyone loses.",
		"In the grand chess game of software development, you've checkmated yourself.",
		"Your code is a Rorschach test: Everyone sees disaster.",
		"You're the Fermi paradox of programming: With all this code, where's the competence?",
		"Your existence is a thought experiment: What if everything went wrong?",
		"You're the observer effect: When observed, your code collapses into failure.",
		"In the simulation hypothesis, you're the bug in the Matrix.",
		"Your code is Pascal's wager: Bet on it working, lose infinitely.",
		"You're the infinite regress: Every fix requires a fix requires a fix...",
		"Your code is the problem of evil: If good code exists, why does yours exist?",
		"You're the sound of one hand clapping: Philosophically confusing, practically useless.",
	},

	"comparison": {
		"A magic 8-ball makes better architectural decisions.",
		"A random number generator produces more predictable code.",
		"A rubber duck has more debugging insight.",
		"Stack Overflow's worst answers are better than your best code.",
		"A coinflip has better success rate than your deployments.",
		"A broken clock is right twice a day. You're not even a broken clock.",
		"Monkeys at typewriters have better code review comments.",
		"A Ouija board provides more reliable technical solutions.",
		"Fortune cookies give better error messages.",
		"A magic wand would be more practical than your debugging strategy.",
		"ChatGPT's hallucinations are more accurate than your implementations.",
		"A paper airplane has better flight testing than your code.",
		"A dartboard makes more strategic technical decisions.",
		"A crystal ball has more accurate sprint estimations.",
		"A toddler's finger painting has more structure than your architecture.",
		"A game of telephone produces clearer communication than your documentation.",
		"A Rube Goldberg machine is more efficient than your algorithms.",
		"A house of cards is more stable than your production environment.",
		"A Jenga tower mid-collapse is more structurally sound than your codebase.",
		"A game of 52 pickup is better organized than your file structure.",
		"A tornado in a trailer park causes less destruction than your refactoring.",
		"A bull in a china shop has more finesse than your code changes.",
		"A wrecking ball is more surgical than your bug fixes.",
		"A blind squirrel finds a nut sometimes. You find nothing.",
		"A stopped watch is right twice daily. You're right never.",
		"A magic trick has more reliable outcomes than your code.",
		"A roll of the dice has better risk management.",
		"A weather forecast is more accurate than your estimates.",
		"A horoscope is more scientific than your debugging process.",
		"A chain email has more credibility than your technical decisions.",
		"A fortune teller has better product roadmaps.",
		"A slot machine has better returns on investment.",
		"A game of Russian roulette is safer than deploying your code.",
		"A house of cards survives stronger winds than your code survives production.",
		"A sandcastle withstands waves better than your code withstands users.",
		"A paper mache bridge is structurally superior.",
		"A chocolate teapot is more useful.",
		"A screen door on a submarine is more watertight than your logic.",
		"A one-legged man in a butt-kicking contest has better odds than you.",
		"A soup sandwich is more coherent than your architecture diagrams.",
	},

	"timeline": {
		"Past you: Hopeful. Present you: Failing. Future you: Unemployed.",
		"Yesterday's bug is today's feature. Today's feature is tomorrow's disaster.",
		"A week ago you were confident. Now you're consistently incompetent.",
		"Last month: 'I got this'. This month: 'I give up'.",
		"Your git log is a timeline of deteriorating judgment.",
		"Six months ago you knew nothing. Now you know less.",
		"Last year: Learning to code. This year: Learning you shouldn't.",
		"Your commit history: A descent into madness, documented.",
		"Previous quarter: Promising. Current quarter: Plummeting.",
		"Monday: Fresh start. Friday: Fresh disaster.",
		"Morning you: Optimistic. Evening you: Catastrophic.",
		"Sprint start: Hope. Sprint end: Horror.",
		"Your career trajectory: Started low, went lower.",
		"First day: Imposter syndrome. Today: Accurate syndrome.",
		"Onboarding: Confident. Three months later: Confounded.",
		"Your performance reviews: A chronicle of decline.",
		"Last sprint: Bad. This sprint: Worse. Next sprint: Terminated.",
		"January: New year, new me. December: Same failures, different date.",
		"Q1: Quarterly goals. Q4: Quarterly disasters.",
		"Day 1: I can learn this. Day 100: I cannot learn this.",
		"Your code evolution: From broken to more broken.",
		"Past you planted bugs. Present you harvests consequences.",
		"Your roadmap: Started somewhere, ended nowhere.",
		"Five years experience: One year of experience repeated five times. Badly.",
		"Your career arc: Parabolic. Currently falling.",
		"Then: Junior developer. Now: Still junior. Forever: Junior.",
		"Your progress: Two steps back, no steps forward.",
		"Historical analysis: Consistently inconsistent, reliably unreliable.",
		"Your timeline: Born. Learned to code. Shouldn't have.",
		"Future historians will study your code as a cautionary tale.",
		"Time travel couldn't save your code. Not even going back to prevent it.",
		"Your development lifecycle: Plan, code, break, repeat.",
		"Yesterday's promise is today's broken build.",
		"Your velocity chart looks like a ski slope. You're going downhill.",
		"Retrospective: You haven't learned from past mistakes. Prospective: You won't.",
		"Your code ages like milk. Sour within hours.",
		"The passage of time hasn't improved your code. Nothing could.",
		"Your legacy: A warning to future developers.",
		"In 100 years, archaeologists will unearth your code and weep.",
		"Your contribution to posterity: A lesson in failure.",
	},

	"meta": {
		"This insult is auto-generated because your failures exceed our database capacity.",
		"We ran out of insults. You've achieved something: Exhausting our insult budget.",
		"Error 500: Too many failures to process. This is meta.",
		"This message is brought to you by your sponsor: Disaster.",
		"You've been mocked 1000+ times. Achievement unlocked: Shameless.",
		"Our AI refused to generate more insults for you. Even AI has standards.",
		"This insult was written by committee. The committee resigned.",
		"We're using machine learning to predict your next failure. Spoiler: It's imminent.",
		"Our database has a dedicated table for your failures. It's the biggest one.",
		"This message is cached for performance. Your failures are too frequent.",
		"We implemented rate limiting. For our insults. Because of you.",
		"Our server crashed trying to log all your failures. Ironic.",
		"This insult is sponsored by your team's therapy sessions.",
		"We're training an AI on your mistakes. It became sentient and quit.",
		"This message is paginated. Your failures require multiple pages.",
		"Our infrastructure team added capacity. For your failures.",
		"We created a CDN for insults. You're the primary traffic source.",
		"This insult was A/B tested. Both versions say you failed.",
		"We scaled horizontally to handle your failure load.",
		"Our monitoring dashboard has a 'You' panel. It's always red.",
		"This message is load-balanced. Your failures exceed single-server capacity.",
		"We implemented caching. Your insults are the most frequently accessed.",
		"This insult is brought to you by distributed systems. Unlike your code.",
		"Our backup system exists because of you. Thanks for the job security.",
		"This message was compressed. Your failures were too large.",
		"We sharded the database. Your failures exceeded single-partition size.",
		"This insult was optimized. Unlike your code.",
		"Our DR plan includes 'user failures'. That's you.",
		"This message is idempotent. Like your mistakes: Repeated reliably.",
		"We implemented circuit breakers. To handle your failure rate.",
		"This insult was peer-reviewed. Peers agreed: You failed.",
		"Our SLA covers uptime. Your failures exceed our downtime.",
		"This message is eventually consistent. You're immediately inconsistent.",
		"We use microservices for insults. Monolithic incompetence: You.",
		"This insult is stateless. Your state: Permanent failure.",
		"We implemented retry logic. For insults. Because you keep failing.",
		"This message is ephemeral. Your failures are eternal.",
		"Our chaos engineering tests found the weakest link: You.",
		"This insult was generated by our AI. It learned from your failures.",
		"We scaled to zero during your vacation. Interesting correlation.",
	},

	"technical_savage": {
		"Your code has O(n!) complexity. N is the number of team members who quit.",
		"You treat the stack like a suggestion. The heap like a dumping ground.",
		"Your memory leaks are the only consistent thing about your code.",
		"You've achieved race conditions in single-threaded code. Impressive.",
		"Your database queries have more joins than your career has prospects.",
		"SELECT * FROM career WHERE competence > 0; -- 0 rows returned.",
		"You've created a distributed monolith. The worst of both worlds.",
		"Your microservices are nano-failures.",
		"You implement SOLID principles: Spectacularly Omitted, Logic Ignored, Development Disasters.",
		"Your code violates DRY: Definitely Ruining Yesterday's work.",
		"KISS principle: Keep It Simple, Stupid. You kept the stupid.",
		"Your architecture is CRUD: Catastrophically Ridiculous, Utterly Dysfunctional.",
		"You practice TDD: Totally Defective Development.",
		"Your CI/CD: Continuous Incompetence, Continuous Disasters.",
		"You achieve CAP theorem: Choose All Problems.",
		"Your eventual consistency is eventual catastrophe.",
		"You've mastered the ACID properties: All Code Is Defective.",
		"Your REST API: Representational State of Terrible.",
		"You implement SOAP: Service-Oriented Awful Programming.",
		"Your GraphQL: Graph of Questionable Logic.",
		"You've created technical debt. The interest rate: Infinite.",
		"Your code coverage: 100%. Coverage of mistakes.",
		"You practice pair programming: Two people, zero productivity.",
		"Your agile methodology: Agile at creating disasters.",
		"Your DevOps: Development + Operations = Destruction.",
		"You implement serverless: Server-less competent.",
		"Your containers contain catastrophes.",
		"Your orchestration is chaotic.",
		"Your API gateway is a gateway to unemployment.",
		"Your load balancer can't balance your failures.",
		"You've mastered async/await: Async disasters, await unemployment.",
		"Your promises always reject. Like your pull requests.",
		"Your callbacks pyramid of doom is accurately named.",
		"Your closures close the door on your career.",
		"Your prototypes are prototypical failures.",
		"Your inheritance chain inherits incompetence.",
		"Your polymorphism: Many forms of failure.",
		"Your encapsulation encapsulates disasters.",
		"Your abstraction: Abstract incompetence.",
		"Your composition composes catastrophes.",
	},
}

// GetSavageInsult returns a random savage insult from a category
func GetSavageInsult(category string, seed string) string {
	insults, exists := SavageInsultDatabase[category]
	if !exists || len(insults) == 0 {
		return ""
	}

	return selectInsult(insults, seed)
}

// GetAnySavageInsult returns a random savage insult from any category
func GetAnySavageInsult(seed string) string {
	categories := []string{
		"ego_destruction",
		"career_advice",
		"team_impact",
		"existential",
		"comparison",
		"timeline",
		"meta",
		"technical_savage",
	}

	category := selectInsult(categories, seed)
	return GetSavageInsult(category, seed)
}
